### ISSUE TITLE
NPE in setHeader

### ISSUE THREAD

**Issue by r-52** [koush/ion#201]
I'm getting the following NPE:

```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.koushikdutta.async.http.libcore.RawHeaders.set(java.lang.String, java.lang.String)' on a null object reference
            at com.koushikdutta.ion.IonRequestBuilder.setHeader(IonRequestBuilder.java:903)
            at com.koushikdutta.ion.IonRequestBuilder.setHeader(IonRequestBuilder.java:75)
```

The NPE occurs when I call the  "/api/me.json" reddit.com API. (http://www.reddit.com/dev/api). 

The API should response with data about your current logged-in account. If I call the API with the NamedValuePair Ion gives me the NPE.

``` Java
NameValuePair[] arrayHeader = new NameValuePair[1];
        arrayHeader[0] = new BasicNameValuePair("cookie", "reddit_session=xxx");


        Ion.with(this, "http://www.reddit.com/api/me.json")
                .setHeader(arrayHeader)
                .asJsonObject()
                .setCallback(new FutureCallback<JsonObject>() {
                    @Override
                    public void onCompleted(Exception e, JsonObject result) {
                    }
                });
```

Or is it an error on my side? I couldn't find a matching testcase.

**Comment by homedevs** [comment]
How can I pass  Map<String, String>  as setHeader ? I am expecting dynamic headers from 3rd party.
