### ISSUE TITLE
What does this error mean: "Not all data was consumed by Util.emitAllData"?

### ISSUE THREAD

**Issue by elmehalawi** [koush/ion#252]
I'm using Ion in my Android app to download text, byte arrays, and images.

For certain downloads (and unfortunately I have not been able to isolate them), the app will crash with a `java.lang.RuntimeException` with the following message:

```
Not all data was consumed by Util.emitAllData
```

I can see that `com.koushikdutta.async.Util` is throwing the exception, but I don't understand why. What does the error even mean so I can try to fix it?

**Comment by raylee4204** [comment]
@koush still experiencing this issue - using the latest version.
```
.koushikdutta.async.Util.emitAllData (Util.java:47)
com.koushikdutta.async.FilteredDataEmitter.onDataAvailable (FilteredDataEmitter.java:56)
com.koushikdutta.async.http.cache.ResponseCacheMiddleware$CachedBodyEmitter.spewInternal (ResponseCacheMiddleware.java:428)
com.koushikdutta.async.http.cache.ResponseCacheMiddleware$1.run (ResponseCacheMiddleware.java:172)
com.koushikdutta.async.AsyncServer.lockAndRunQueue (AsyncServer.java:708)
com.koushikdutta.async.AsyncServer.runLoop (AsyncServer.java:722)
com.koushikdutta.async.AsyncServer.run (AsyncServer.java:626)
com.koushikdutta.async.AsyncServer.access$300 (AsyncServer.java:41)
com.koushikdutta.async.AsyncServer$13.run (AsyncServer.java:568)
```

**Comment by eugenkiss** [comment]
As another data point, I'm getting this error with exactly the same stack trace on version 2.0.5, too, and I do cancel requests in my application.

**Comment by koush** [comment]
I think I have another fix for this. Going to force emitter into pause state after its closed.

**Comment by JoshElias** [comment]
I'm having this issue on AndroidAsync 2.1 as well.

**Comment by schwiz** [comment]
Still having this issue, I don't understand why this exception isn't swallowed anywhere. But I'm getting close to being forced to switch off ion last second since this won't stop.

**Comment by battlmonstr** [comment]
This still happens, see #615 .

**Comment by senhor** [comment]
I have got the same issue with Ion 2.+ when downloading a file from server. Here is the log:

```
11-13 10:51:43.344 3743-3955/com.pinq.ozbetik I/System.out: handler: null
11-13 10:51:43.344 3743-3955/com.pinq.ozbetik I/System.out: emitter: HTTP/1.1 200 OK
11-13 10:51:43.344 3743-3955/com.pinq.ozbetik I/System.out: Date: Sun, 13 Nov 2016 10:51:42 GMT
11-13 10:51:43.344 3743-3955/com.pinq.ozbetik I/System.out: Server: Apache/2.4.23 (Amazon) PHP/5.6.26
11-13 10:51:43.344 3743-3955/com.pinq.ozbetik I/System.out: Last-Modified: Sun, 30 Oct 2016 08:52:08 GMT
11-13 10:51:43.344 3743-3955/com.pinq.ozbetik I/System.out: ETag: "57713-5401134cc9e00"
11-13 10:51:43.344 3743-3955/com.pinq.ozbetik I/System.out: Accept-Ranges: bytes
11-13 10:51:43.345 3743-3955/com.pinq.ozbetik I/System.out: Content-Length: 358163
11-13 10:51:43.345 3743-3955/com.pinq.ozbetik I/System.out: Keep-Alive: timeout=5, max=100
11-13 10:51:43.345 3743-3955/com.pinq.ozbetik I/System.out: Connection: Keep-Alive
11-13 10:51:43.345 3743-3955/com.pinq.ozbetik I/System.out: Content-Type: application/pdf
11-13 10:51:43.346 3743-3955/com.pinq.ozbetik E/MyLogs: (160 ms) http://www.ozbetik.com/magazines/example.pdf: exception during response
11-13 10:51:43.346 3743-3955/com.pinq.ozbetik E/MyLogs: Not all data was consumed by Util.emitAllData
                                                        java.lang.RuntimeException: Not all data was consumed by Util.emitAllData
                                                            at com.koushikdutta.async.Util.emitAllData(Util.java:54)
                                                            at com.koushikdutta.async.FilteredDataEmitter.onDataAvailable(FilteredDataEmitter.java:56)
                                                            at com.koushikdutta.async.Util.emitAllData(Util.java:23)
                                                            at com.koushikdutta.async.FilteredDataEmitter.onDataAvailable(FilteredDataEmitter.java:56)
                                                            at com.koushikdutta.async.http.cache.ResponseCacheMiddleware$BodyCacher.onDataAvailable(ResponseCacheMiddleware.java:385)
                                                            at com.koushikdutta.async.Util.emitAllData(Util.java:23)
                                                            at com.koushikdutta.async.FilteredDataEmitter.onDataAvailable(FilteredDataEmitter.java:56)
                                                            at com.koushikdutta.async.http.filter.ContentLengthFilter.onDataAvailable(ContentLengthFilter.java:33)
                                                            at com.koushikdutta.async.Util.emitAllData(Util.java:23)
                                                            at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:152)
                                                            at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:820)
                                                            at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:657)
                                                            at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44)
                                                            at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:599)
```

**Comment by ravenfeld** [comment]
I have got the same issue with Ion 2.2.1 when downloading a file from server

**Comment by DominikNozka** [comment]
It may happen if you do not have external storage permissions
