### ISSUE TITLE
Connection closed before response completed for SSL requests

### ISSUE THREAD

**Issue by nathanjones** [koush/ion#260]
I'm attempting to connect to make a GET request over SSL using the following code:

```
Ion.with(getActivity())
      .load("https://api.clyp.it/featuredlist/popular")
      .asJsonArray();
```

and I get the following error:

```
06-18 00:16:50.075    4530-5072/it.clyp E/Clyp﹕ connection closed before response completed.
    com.koushikdutta.async.http.ConnectionClosedException: connection closed before response completed.
            at com.koushikdutta.async.http.AsyncHttpResponseImpl$3.onCompleted(AsyncHttpResponseImpl.java:95)
            at com.koushikdutta.async.AsyncNetworkSocket.reportEnd(AsyncNetworkSocket.java:256)
            at com.koushikdutta.async.AsyncNetworkSocket.reportEndPending(AsyncNetworkSocket.java:268)
            at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:185)
            at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:755)
            at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:600)
            at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:37)
            at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:549)
     Caused by: java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)
            at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:545)
            at libcore.io.IoBridge.recvfrom(IoBridge.java:521)
            at java.nio.SocketChannelImpl.readImpl(SocketChannelImpl.java:327)
            at java.nio.SocketChannelImpl.read(SocketChannelImpl.java:289)
            at com.koushikdutta.async.SocketChannelWrapper.read(SocketChannelWrapper.java:24)
            at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:157)
            at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:755)
            at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:600)
            at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:37)
            at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:549)
     Caused by: libcore.io.ErrnoException: recvfrom failed: ECONNRESET (Connection reset by peer)
            at libcore.io.Posix.recvfromBytes(Native Method)
            at libcore.io.Posix.recvfrom(Posix.java:136)
            at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:159)
            at libcore.io.IoBridge.recvfrom(IoBridge.java:518)
            at java.nio.SocketChannelImpl.readImpl(SocketChannelImpl.java:327)
            at java.nio.SocketChannelImpl.read(SocketChannelImpl.java:289)
            at com.koushikdutta.async.SocketChannelWrapper.read(SocketChannelWrapper.java:24)
            at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:157)
            at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:755)
            at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:600)
            at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:37)
            at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:549)
```

If I attempt to make the same request using a regular HTTP request, it works fine: 

```
Ion.with(getActivity())
      .load("http://api.clyp.it/featuredlist/popular")
      .asJsonArray();
```

The server has a valid, signed certificate and uses a TLS connection. 

Any idea what's causing the connection to close?

**Comment by ahmadalibaloch** [comment]
This is a problem in Ion which happens on https. When I changed same call with retrofit, it started working like a charm.
