### ISSUE TITLE
com.koushikdutta.async.http.ConnectionClosedException: connection closed before response completed. only on Android L

### ISSUE THREAD

**Issue by alikslee** [koush/ion#278]
<pre>
    com.koushikdutta.async.http.ConnectionClosedException: connection closed before response completed.
            at com.koushikdutta.async.http.AsyncHttpResponseImpl$3.onCompleted(AsyncHttpResponseImpl.java:95)
            at com.koushikdutta.async.AsyncSSLSocketWrapper.report(AsyncSSLSocketWrapper.java:382)
            at com.koushikdutta.async.AsyncSSLSocketWrapper.handleResult(AsyncSSLSocketWrapper.java:247)
            at com.koushikdutta.async.AsyncSSLSocketWrapper.write(AsyncSSLSocketWrapper.java:356)
            at com.koushikdutta.async.Util$7.onWriteable(Util.java:192)
            at com.koushikdutta.async.Util.writeAll(Util.java:199)
            at com.koushikdutta.async.Util.writeAll(Util.java:207)
            at com.koushikdutta.async.http.AsyncHttpResponseImpl.setSocket(AsyncHttpResponseImpl.java:66)
            at com.koushikdutta.async.http.AsyncHttpClient$3.onConnectCompleted(AsyncHttpClient.java:358)
            at com.koushikdutta.async.http.AsyncSocketMiddleware$2$2$1.onConnectCompleted(AsyncSocketMiddleware.java:246)
            at com.koushikdutta.async.http.AsyncSSLSocketMiddleware$1.onConnectCompleted(AsyncSSLSocketMiddleware.java:41)
            at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:743)
            at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:583)
            at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:36)
            at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:531)
     Caused by: com.koushikdutta.async.AsyncSSLException: Peer not trusted by any of the system trust managers.
            at com.koushikdutta.async.AsyncSSLSocketWrapper.handleResult(AsyncSSLSocketWrapper.java:246)
            at com.koushikdutta.async.AsyncSSLSocketWrapper.write(AsyncSSLSocketWrapper.java:356)
            at com.koushikdutta.async.Util$7.onWriteable(Util.java:192)
            at com.koushikdutta.async.Util.writeAll(Util.java:199)
            at com.koushikdutta.async.Util.writeAll(Util.java:207)
            at com.koushikdutta.async.http.AsyncHttpResponseImpl.setSocket(AsyncHttpResponseImpl.java:66)
            at com.koushikdutta.async.http.AsyncHttpClient$3.onConnectCompleted(AsyncHttpClient.java:358)
            at com.koushikdutta.async.http.AsyncSocketMiddleware$2$2$1.onConnectCompleted(AsyncSocketMiddleware.java:246)
            at com.koushikdutta.async.http.AsyncSSLSocketMiddleware$1.onConnectCompleted(AsyncSSLSocketMiddleware.java:41)
            at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:743)
            at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:583)
            at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:36)
            at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:531)
</pre>

**Comment by alfredayibonte** [comment]
I am having the same issue.
com.koushikdutta.async.http.ConnectionClosedException: connection closed before response completed.
I even taught may be the data I'm sending is too large.

**Comment by alfredayibonte** [comment]
@koush I am having issues passing Json.
The stack trace is as follows:
com.google.gson.JsonParseException: unable to parse json
at com.koushikdutta.ion.gson.GsonParser$1.transform(GsonParser.java:38)
at com.koushikdutta.ion.gson.GsonParser$1.transform(GsonParser.java:32)
at com.koushikdutta.async.future.TransformFuture.onCompleted(TransformFuture.java:14)
at com.koushikdutta.async.future.SimpleFuture.handleCallbackUnlocked(SimpleFuture.java:107)
