### ISSUE TITLE
Simple POST - connection timeout exception

### ISSUE THREAD

**Issue by clickslide** [koush/ion#293]
Hi, 

Here is what I'm seeing in my verbose Log:

```
V/ION_VERBOSE_LOGGING( 5440): (1168 ms) http://nycwaste.herokuapp.com/api/hooks: socket connected
D/ION_VERBOSE_LOGGING( 5440): (0 ms) http://nycwaste.herokuapp.com/api/hooks: preparing request
V/ION_VERBOSE_LOGGING( 5440): (1174 ms) http://nycwaste.herokuapp.com/api/hooks: 
V/ION_VERBOSE_LOGGING( 5440): POST /api/hooks HTTP/1.1
V/ION_VERBOSE_LOGGING( 5440): Host: nycwaste.herokuapp.com
V/ION_VERBOSE_LOGGING( 5440): User-Agent: Dalvik/1.6.0 (Linux; U; Android 4.4.4; Nexus 7 Build/KTU84P)
V/ION_VERBOSE_LOGGING( 5440): Accept-Encoding: gzip, deflate
V/ION_VERBOSE_LOGGING( 5440): Connection: keep-alive
V/ION_VERBOSE_LOGGING( 5440): Accept: */*
V/ION_VERBOSE_LOGGING( 5440): Cookie: sessionID=9694ca92dae0629908cc2ea815ebff9d05450ec3
V/ION_VERBOSE_LOGGING( 5440): Content-Type: application/x-www-form-urlencoded
V/ION_VERBOSE_LOGGING( 5440): Content-Length: 263
V/ION_VERBOSE_LOGGING( 5440): 
V/ION_VERBOSE_LOGGING( 5440): (1175 ms) http://nycwaste.herokuapp.com/api/hooks: request completed
I/ION_VERBOSE_LOGGING( 5440): (0 ms) http://nycwaste.herokuapp.com/api/hooks: Using loader: com.koushikdutta.ion.loader.HttpLoader@4216e280
D/ION_VERBOSE_LOGGING( 5440): (0 ms) http://nycwaste.herokuapp.com/api/hooks: Executing request.
D/ION_VERBOSE_LOGGING( 5440): (3 ms) http://nycwaste.herokuapp.com/api/hooks: Reusing keep-alive socket
V/ION_VERBOSE_LOGGING( 5440): (4 ms) http://nycwaste.herokuapp.com/api/hooks: socket connected
V/ION_VERBOSE_LOGGING( 5440): (5 ms) http://nycwaste.herokuapp.com/api/hooks: 
V/ION_VERBOSE_LOGGING( 5440): POST /api/hooks HTTP/1.1
V/ION_VERBOSE_LOGGING( 5440): Host: nycwaste.herokuapp.com
V/ION_VERBOSE_LOGGING( 5440): User-Agent: Dalvik/1.6.0 (Linux; U; Android 4.4.4; Nexus 7 Build/KTU84P)
V/ION_VERBOSE_LOGGING( 5440): Accept-Encoding: gzip, deflate
V/ION_VERBOSE_LOGGING( 5440): Connection: keep-alive
V/ION_VERBOSE_LOGGING( 5440): Accept: */*
V/ION_VERBOSE_LOGGING( 5440): Cookie: sessionID=9694ca92dae0629908cc2ea815ebff9d05450ec3
V/ION_VERBOSE_LOGGING( 5440): Content-Type: application/x-www-form-urlencoded
V/ION_VERBOSE_LOGGING( 5440): Content-Length: 514
V/ION_VERBOSE_LOGGING( 5440): 
V/ION_VERBOSE_LOGGING( 5440): (6 ms) http://nycwaste.herokuapp.com/api/hooks: request completed
E/ION_VERBOSE_LOGGING( 5440): (30002 ms) http://nycwaste.herokuapp.com/api/hooks: Connection error
E/ION_VERBOSE_LOGGING( 5440): null
E/ION_VERBOSE_LOGGING( 5440): java.util.concurrent.TimeoutException
E/ION_VERBOSE_LOGGING( 5440):   at com.koushikdutta.async.http.AsyncHttpClient$2.run(AsyncHttpClient.java:196)
E/ION_VERBOSE_LOGGING( 5440):   at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:678)
E/ION_VERBOSE_LOGGING( 5440):   at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:695)
E/ION_VERBOSE_LOGGING( 5440):   at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:603)
E/ION_VERBOSE_LOGGING( 5440):   at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:37)
E/ION_VERBOSE_LOGGING( 5440):   at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:552)
D/ION_VERBOSE_LOGGING( 5440): (31655 ms) http://nycwaste.herokuapp.com/api/hooks: Recycling extra socket leftover from cancelled operation
V/ION_VERBOSE_LOGGING( 5440): (3438 ms) http://nycwaste.herokuapp.com/api/hooks: socket connected
```

This happens on nearly every request I'm sending. 
The code I'm using to do this looks like this:

```
private void sendDataToServer(JSONArray json){
        Log.i(TAG, "Sending POST request to Service.");
        Ion.with(this)
        .load("http://nycwaste.herokuapp.com/api/hooks")
        .setLogging("ION_VERBOSE_LOGGING", Log.VERBOSE)
        .setBodyParameter("payload", json.toString())
        .asString()
        .withResponse()
        .setCallback(new FutureCallback<Response<String>>() {
            @Override
            public void onCompleted(Exception e, Response<String> result) {
                sending = false;
                if(e == null) {
                    Log.i(TAG, "ION SENT MESSAGE WITH RESULT CODE: " + result.getHeaders().getResponseCode());
                }else{
                    Log.i(TAG, "ION SENT MESSAGE WITH EXCEPTION");
                    e.printStackTrace();
                }
            }
        });
    }
```

This method is called in a loop sending sensor data. I think it's called 3-5 times per-second. Possibly more often.

Is there anything you see that might be the problem? Perhaps there is a better way for me to get more information about the error? 

Any help would be greatly appreciated.

Best,
Aaron

**Comment by markeins** [comment]
Hi, I'm using version 2.0.8 and facing the same problem with the socket connection. The only weird thing is that when I'm executing the POST request based on a user action (click), it ALWAYS WORKS; but, when I have it executed as a post-delayed action with 20 secs timer, if user does not select the action, then MOST of the times, IT FAILS, only several times it worked automatically...

Here is the logcat:

03-30 22:22:31.152    5432-6356/COM.MY.APP D/COM.MY.APP﹕ (0 ms) http://localhost:8080/server/api/device/sendRequest: preparing request
03-30 22:22:31.172    5432-5432/COM.MY.APP I/COM.MY.APP﹕ (0 ms) http://localhost:8080/server/api/device/sendRequest: Using loader: com.koushikdutta.ion.loader.HttpLoader@41b370f0
03-30 22:22:31.172    5432-6341/COM.MY.APP D/COM.MY.APP﹕ (0 ms) http://localhost:8080/server/api/device/sendRequest: Executing request.
03-30 22:22:31.182    5432-6341/COM.MY.APP D/COM.MY.APP﹕ (2 ms) http://localhost:8080/server/api/device/sendRequest: Reusing keep-alive socket
03-30 22:22:31.182    5432-6341/COM.MY.APP V/COM.MY.APP﹕ (2 ms) http://localhost:8080/server/api/device/sendRequest: socket connected
03-30 22:22:31.182    5432-6341/COM.MY.APP V/COM.MY.APP﹕ (10 ms) http://localhost:8080/server/api/device/sendRequest:
    POST /server/api/device/sendRequest HTTP/1.1
    Host: localhost:8080
    User-Agent: Dalvik/1.6.0 (Linux; U; Android 4.4.2; LG-V400 Build/KOT49I.A1403851534)
    Accept-Encoding: gzip, deflate
    Connection: keep-alive
    Accept: */*
    Content-Type: application/json
    Content-Length: 150
03-30 22:22:31.192    5432-6341/COM.MY.APP V/COM.MY.APP﹕ (12 ms) http://localhost:8080/server/api/device/sendRequest: request completed
03-30 22:22:31.202    5432-6341/COM.MY.APP V/COM.MY.APP﹕ (28 ms) http://localhost:8080/server/api/device/sendRequest: closing out socket (exception)
03-30 22:22:37.192    5432-6341/COM.MY.APP E/COM.MY.APP﹕ (6020 ms) http://localhost:8080/server/api/device/sendRequest: Connection error
03-30 22:22:37.212    5432-6341/COM.MY.APP E/COM.MY.APP﹕ null
    java.util.concurrent.TimeoutException
            at com.koushikdutta.async.http.AsyncHttpClient$2.run(AsyncHttpClient.java:247)
            at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:708)
            at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:725)
            at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
            at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
            at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)
03-30 22:22:37.262    5432-5432/COM.MY.APP E/COM.MY.APP/DashboardActivity.java:465﹕ main java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException
            at com.koushikdutta.async.future.SimpleFuture.getResultOrThrow(SimpleFuture.java:71)
            at com.koushikdutta.async.future.SimpleFuture.get(SimpleFuture.java:66)
            at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:73)
            at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:42)
            at rx.Observable.unsafeSubscribe(Observable.java:7495)
            at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
            at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
     Caused by: java.util.concurrent.TimeoutException
            at com.koushikdutta.async.http.AsyncHttpClient$2.run(AsyncHttpClient.java:247)
            at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:708)
            at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:725)
            at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
            at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
            at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)

**Comment by NiklasMerz** [comment]
I have the same problem with the latest ION Version only for PUT requests. Get perfectly works.

```java
public void upvoteDoc(View view) {

		String url = doc.apiURL + doc.getName() + "?apiKey=" + apiKey;
		Ion.with(getBaseContext()).load("PUT", url)
				.setTimeout(6000) 
				.setLogging("NPA_ION", Log.DEBUG)
				.setBodyParameter("Points", "1").asString()
				.setCallback(new FutureCallback<String>() {

					@Override
					public void onCompleted(Exception arg0, String arg1) {
						// TODO Auto-generated method stub

					}

				});
	}
```
![bildschirmfoto vom 2015-09-24 18 48 49](https://cloud.githubusercontent.com/assets/3585860/10079910/f42320fa-62ec-11e5-9956-f6bf45cc8821.png)

**Comment by WasimMemon** [comment]
Have any progress on this ?
because i am facing this issue in latest version also.

please can you provide some exception handler so we can display proper message to user.

Thanks for library...

**Comment by maarcosd** [comment]
Has anyone found a solution for this?

Having same issue only for PUT requests.

**Comment by BapaiahMandava** [comment]
hi,

what does setTimeout(-1) do?
And even the public void onCompleted(Exception ex, WebSocket webSocket) method is being calling the webscoket every minute?

Pls throw some light why is this behaviour.

**Comment by navid-dada** [comment]
i have same problem.... is there any solution?
