### ISSUE TITLE
TimeoutException while connecting

### ISSUE THREAD

**Issue by cimnine** [koush/ion#312]
When connecting to a certain webserver, I get the following exception:

```
java.util.concurrent.TimeoutException
    at com.koushikdutta.async.future.SimpleFuture.get(SimpleFuture.java:84)
    at ch.cimnine.xxx.testString(SecvestIPTest.java:82)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
    at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
    at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
    at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1840)
```

Testcase (No TimeoutException):

```
public class FailTest extends AndroidTestCase {
    public void testString() throws Exception {
        Future<Response<String>> responseFuture = Ion.with(getContext())
                .load("POST", "http://google.com:80/")
                .followRedirect(false)
                //.setBodyParameter("UserName", "foo")
                .setBodyParameter("q", "foo")
                .asString()
                .withResponse();

        Response<String> response = responseFuture.get(5000, TimeUnit.MILLISECONDS);
        assertNotNull(response.getResult());
    }
}
```

Testcase (TimeoutException occurs):

```
public class FailTest extends AndroidTestCase {
    public void testString() throws Exception {
        Future<Response<String>> responseFuture = Ion.with(getContext())
                .load("POST", "http://192.168.1.49:8080/")
                .followRedirect(false)
                .setBodyParameter("UserName", "foo")
                .setBodyParameter("Password", "foo")
                .asString()
                .withResponse();

        Response<String> response = responseFuture.get(5000, TimeUnit.MILLISECONDS);
        assertNotNull(response.getResult());
    }
}
```

I have captured the (not working) response. To use it, copy it from below and then inject it like this:

```
$ pbpaste | base64 -D > responseDump
$ nc -l 8080 < responseDump
```

Here is the response:

```
SFRUUC8xLjAgMzAyIEZvdW5kDQpTZXQtQ29va2ll
OlNFU1NJT049NUJBRDlERTEwQjY0NjgwNDsKTG9j
YXRpb246IGhvbWUuY2dpCkNvbnRlbnQtdHlwZTog
dGV4dC9odG1sCgo8aHRtbD48aGVhZD48bWV0YSBo
dHRwLWVxdWl2PSdyZWZyZXNoJyBjb250ZW50PScw
OyB1cmw9aG9tZS5jZ2knPjwvbWV0YT48L2hlYWQ+
PGJvZHk+PC9ib2R5PjwvaHRtbD4K
```

Verify:

```
$ md5 responseDump
MD5 (responseDump) = 810a10ef0023bf11105f3a5012f7b191
```

It is not the influence of `nc`. You can test that:

```
$ nc -l 8080 > req & curl "http://localhost:8080"
$ nc google.com 80 < req > res
$ nc -l 8080 < res
# now use the testcase above to connect to this machine on port 8080
# it will work
```

That's why I think this is an ion bug.

**Comment by navid-dada** [comment]
i have this problem to
