### ISSUE TITLE
Uncatchable exception

### ISSUE THREAD

**Issue by schwiz** [koush/ion#422]
When trying to cancel a request in flight using cancelAll sometimes the callback will throw a CancellationException. However, a few milliseconds later I get an uncatchable exception with the stacktrace below. Using version 201.

```
                        E  java.lang.RuntimeException: Not all data was consumed by Util.emitAllData
                        E      at com.koushikdutta.async.Util.emitAllData(Util.java:47)
                        E      at com.koushikdutta.async.http.cache.ResponseCacheMiddleware$CachedBodyEmitter.spewInternal(ResponseCacheMiddleware.java:428)
                        E      at com.koushikdutta.async.http.cache.ResponseCacheMiddleware$1.run(ResponseCacheMiddleware.java:172)
                        E      at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:708)
                        E      at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:725)
                        E      at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
                        E      at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
                        E      at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)
```

**Comment by koush** [comment]
Lemme see if I can reproduce this in a unit test...

**Comment by vibol** [comment]
Happening for us in 202 as well:

```
java.lang.RuntimeException: Not all data was consumed by Util.emitAllData
       at com.koushikdutta.async.Util.emitAllData(Util.java:47)
       at com.koushikdutta.async.FilteredDataEmitter.onDataAvailable(FilteredDataEmitter.java:56)
       at com.koushikdutta.async.http.cache.ResponseCacheMiddleware$CachedBodyEmitter.spewInternal(ResponseCacheMiddleware.java:428)
       at com.koushikdutta.async.http.cache.ResponseCacheMiddleware$1.run(ResponseCacheMiddleware.java:172)
       at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:708)
       at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:725)
       at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
       at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
       at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)
```

**Comment by schwiz** [comment]
Just saw this again today with 2.1.3 @koush can you please re-open?

        AndroidRuntime  E  FATAL EXCEPTION: ion-exoplayer_instance
                        E  Process: com.pinsightmedia.starshop, PID: 31374
                        E  java.lang.RuntimeException: Not all data was consumed by Util.emitAllData
                        E      at com.koushikdutta.async.Util.emitAllData(Util.java:47)
                        E      at com.koushikdutta.async.FilteredDataEmitter.onDataAvailable(FilteredDataEmitter.java:56)
                        E      at com.koushikdutta.async.http.cache.ResponseCacheMiddleware$CachedBodyEmitter.spewInternal(ResponseCacheMiddleware.java:428)
                        E      at com.koushikdutta.async.http.cache.ResponseCacheMiddleware$1.run(ResponseCacheMiddleware.java:172)
                        E      at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:708)
                        E      at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:725)
                        E      at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
                        E      at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
                        E      at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)
