### ISSUE TITLE
GifDecoder, DeepZoom, and IonBitmapCache Memory Issues

### ISSUE THREAD

**Issue by afollestad** [koush/ion#435]
Hopefully this wasn't already reported or fixed, but just in case:

**GifDecoder**

```xml
java.lang.OutOfMemoryError: Failed to allocate a 3831276 byte allocation with 2073998 free bytes and 2025KB until OOM
       at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
       at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:890)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:914)
       at com.koushikdutta.ion.gif.GifDecoder.setPixels(GifDecoder.java:279)
       at com.koushikdutta.ion.gif.GifDecoder.readImage(GifDecoder.java:526)
       at com.koushikdutta.ion.gif.GifDecoder.nextFrame(GifDecoder.java:140)
       at com.koushikdutta.ion.IonDrawable$IonGifDecoder$1.run(IonDrawable.java:164)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

**Deep Zoom**:

```xml
java.lang.OutOfMemoryError
       at android.graphics.BitmapRegionDecoder.nativeDecodeRegion(BitmapRegionDecoder.java)
       at android.graphics.BitmapRegionDecoder.decodeRegion(BitmapRegionDecoder.java:373)
       at com.koushikdutta.ion.LoadDeepZoom$1.run(LoadDeepZoom.java:75)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
```

**IonBitmapCache**:

```xml
java.lang.OutOfMemoryError: Failed to allocate a 262156 byte allocation with 2912856 free bytes
       at android.graphics.BitmapRegionDecoder.nativeDecodeRegion(BitmapRegionDecoder.java)
       at android.graphics.BitmapRegionDecoder.decodeRegion(BitmapRegionDecoder.java:188)
       at com.koushikdutta.ion.bitmap.IonBitmapCache.loadRegion(IonBitmapCache.java:193)
       at com.koushikdutta.ion.LoadBitmapRegion$1.run(LoadBitmapRegion.java:22)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:811)
```

This is a great library, so these don't stop me from using it. It runs perfectly fine on my Nexus 5, but it seems to have issues with lower end Motorola, HTC, and Samsung devices.

If you're interested about testing these on a device, the app it's being used in (Impression) is in alpha and I publish updates to a Google+ community. https://plus.google.com/communities/103090123257670799691

**Comment by afollestad** [comment]
@koush I was wondering if you could give usage advice.

I have a view pager that shows pages of full screen images. I currently show 4 offscreen pages at a time, but this eventually causes out of memory crashes once you've paged to around 6 images. Is there any optimization that can be done without sacrificing quality?

**Comment by koush** [comment]
Is this still happening on ion 2.0+? There were memory improvements made to the gif decoder.

**Comment by koush** [comment]
@afollestad loading 4 offscreen pages (4 on each side = 8) means you are loading 8 full resolution images off screen. You may want to lower that number to something like 2 or 1.

Or load smaller resized/scaled versions that come in at full resolution on setPrimaryItem.

**Comment by afollestad** [comment]
Well now it's mostly deep zoom and general large images

**Comment by afollestad** [comment]
And right, I didn't think of how many pages are loaded. Thanks for your advice.
