### ISSUE TITLE
HTTP HEAD Query for Just Headers

### ISSUE THREAD

**Issue by dortamur** [koush/ion#45]
I need to be able to perform a HTTP HEAD (not GET/POST) query, to just get the response headers for a URL. Is this possible with Ion currently?

My app deals with all sorts of URLs, and I want to be able to pre-fetch things like the content type, size, modified date, to then decide which Action to handball the URL to.

I can do this already with load() and withResponse(), but this fetches the entire content back, which if large is slow, and unnecessary bandwidth usage.

Thanks.

**Comment by zkrige** [comment]
This seems to be happening in 3.0.8 again

**Comment by zkrige** [comment]
@koush this seems to be happening in 3.0.8 again

**Comment by zkrige** [comment]
```
04-25 11:03:48.695 8606-8769/za.co.snapplify D/snappbox-debug: (0 ms) http://192.168.8.108/asset/5782240313/queue: preparing request
04-25 11:03:48.705 8606-8769/za.co.snapplify D/snappbox-debug: (0 ms) http://192.168.8.108/asset/5782240313/queue: preparing request
04-25 11:03:48.705 8606-8606/za.co.snapplify I/snappbox-debug: (0 ms) http://192.168.8.108/asset/5782240313/queue: Using loader: com.koushikdutta.ion.loader.HttpLoader@9d11c700
04-25 11:03:48.715 8606-8677/za.co.snapplify D/snappbox-debug: (0 ms) http://192.168.8.108/asset/5782240313/queue: Executing request.
04-25 11:03:48.725 8606-8677/za.co.snapplify D/snappbox-debug: (10 ms) http://192.168.8.108/asset/5782240313/queue: Reusing keep-alive socket
04-25 11:03:48.745 8606-8677/za.co.snapplify D/snappbox-debug: (31 ms) http://192.168.8.108/asset/5782240313/queue: Response is not cacheable
04-25 11:03:48.745 8606-8677/za.co.snapplify D/snappbox-debug: (32 ms) http://192.168.8.108/asset/5782240313/queue: Connection successful
04-25 11:04:48.795 8606-8677/za.co.snapplify E/snappbox-debug: (60086 ms) http://192.168.8.108/asset/5782240313/queue: exception during response
04-25 11:04:48.795 8606-8677/za.co.snapplify E/snappbox-debug: End of data reached before content length was read: 0/10801957 Paused: false
    com.koushikdutta.async.http.filter.PrematureDataEndException: End of data reached before content length was read: 0/10801957 Paused: false
        at com.koushikdutta.async.http.filter.ContentLengthFilter.report(ContentLengthFilter.java:15)
        at com.koushikdutta.async.FilteredDataEmitter$1.onCompleted(FilteredDataEmitter.java:24)
        at com.koushikdutta.async.AsyncNetworkSocket.reportEnd(AsyncNetworkSocket.java:241)
        at com.koushikdutta.async.AsyncNetworkSocket.reportEndPending(AsyncNetworkSocket.java:253)
        at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:170)
        at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:869)
        at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:717)
        at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:46)
        at com.koushikdutta.async.AsyncServer$11.run(AsyncServer.java:671)

```
