### ISSUE TITLE
getting exception when showing gif.

### ISSUE THREAD

**Issue by kirte** [koush/ion#451]
When i tried to show gif images I got follwoing exception
 --- SkImageDecoder::Factory returned null
 com.koushikdutta.ion.bitmap.BitmapDecodeException size=-1x-1
 at com.koushikdutta.ion.bitmap.IonBitmapCache.prepareBitmapOptions(IonBitmapCache.java:129)
 at com.koushikdutta.ion.bitmap.IonBitmapCache.prepareBitmapOptions(IonBitmapCache.java:151)
 at com.koushikdutta.ion.LoadBitmap$1.run(LoadBitmap.java:54)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
at java.lang.Thread.run(Thread.java:856)

my code is:
 Ion.with(context).load("http://forgifs.com/gallery/d/84222-3/Pool_backflip_faceplant.gif").withBitmap().fitCenter().intoImageView(vh.userrecent_Stream_Image).setCallback(new FutureCallback<ImageView>() {
                            @Override
                            public void onCompleted(Exception e, ImageView imageView) {
                                if(e==null){
                                    imageView.setVisibility(View.VISIBLE);
                                }else{
                                    e.printStackTrace();
                                }
                            }
                        });

I tried with many other gif but getting same result. I just wondering I only able to show gif I used sample url which is added in sample, Aprt from then I always as get above exception.

Any suggestion ?

**Comment by alouanemed** [comment]
Try to change the url

**Comment by afollestad** [comment]
@koush recently Gifs stopped loading altogether. Not sure if this issue is related.

**Comment by koush** [comment]
I think this may be caused by last night's release. Let me check.

**Comment by koush** [comment]
Works fine here on v208.

What version are you on?

**Comment by afollestad** [comment]
The latest, just with simple code too:

```java
Ion.with(this)
                .centerCrop()
                .animateGif(AnimateGifMode.NO_ANIMATE)
                .load(pathToLoad);
```

pathToLoad is a GIF file path. Removing `centerCrop()` didn't seem to make a difference. NO_ANIMATE doesn't make a difference but it's used here because it only animates in the detail view (which also does not load GIFs without an "unable to load bitmap" error).

@koush

**Comment by koush** [comment]
@afollestad What is "this"? An ImageView or a subclass of ImageView?

**Comment by afollestad** [comment]
@koush it's an ImageView subclass: http://pastebin.com/V1fTGfEE

It doesn't load until the view finishes measuring itself. Not sure if that'd be an issue. I override `onDraw()` but it still calls the super method.

**Comment by afollestad** [comment]
@koush also, it worked fine before, I don't think anything in my own code was changed.

**Comment by afollestad** [comment]
@koush I can't reproduce it in another app of mine that doesn't use any custom ImageViews (https://play.google.com/store/apps/details?id=com.afollestad.cabinet)

It always loads the fallback image.

**Comment by koush** [comment]
@afollestad interesting, thanks. I've been unable to reproduce this. I think I may have an idea of what is happening though. Will push a new version sometime over the next few days and you can let me know if it resolves it.

**Comment by afollestad** [comment]
@koush awesome, will do. Thank you

**Comment by afollestad** [comment]
@koush it seems to work fine now, it turns out it was partly a different issue in the detail view. I loading the image as a Bitmap instead of letting Ion handle setting it to the ImageView.

I have another issue related to transparent-background GIFs that I'm about to log with a video though.
