### ISSUE TITLE
Fatal Exception: java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by afollestad** [koush/ion#461]
```gradle
java.util.ConcurrentModificationException
       at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:569)
       at org.apache.harmony.security.fortress.Services.updateServiceInfo(Services.java:186)
       at org.apache.harmony.security.fortress.Services.refresh(Services.java:234)
       at org.apache.harmony.security.fortress.Engine.getInstance(Engine.java:137)
       at java.security.MessageDigest.getInstance(MessageDigest.java:91)
       at com.koushikdutta.async.util.FileCache.toKeyString()
       at com.koushikdutta.ion.IonBitmapRequestBuilder.computeDecodeKey()
       at com.koushikdutta.ion.IonBitmapRequestBuilder.computeDecodeKey()
       at com.koushikdutta.ion.IonBitmapRequestBuilder.executeCache()
       at com.koushikdutta.ion.IonImageViewRequestBuilder.intoImageView()
       at com.koushikdutta.ion.IonImageViewRequestBuilder.load()
```

I'm assuming you'd just want to add a **synchronized** statement in when accessing the iterator.

**Comment by koush** [comment]
This is crashing in MessageDigest.getInstance. Not something I can fix.

**Comment by koush** [comment]
Likely some bad OEM firmware or something.
