### ISSUE TITLE
StackOverflow in AsyncSocketMiddleware

### ISSUE THREAD

**Issue by robUx4** [koush/ion#465]
With Ion 2.0.5

```
java.lang.StackOverflowError
       at libcore.io.BlockGuardOs.close(BlockGuardOs.java:60)
       at libcore.io.IoBridge.closeSocket(IoBridge.java:188)
       at java.net.PlainSocketImpl.close(PlainSocketImpl.java:162)
       at java.net.Socket.close(Socket.java:316)
       at java.nio.SocketChannelImpl$SocketAdapter.close(SocketChannelImpl.java:539)
       at java.nio.SocketChannelImpl.implCloseSelectableChannel(SocketChannelImpl.java:442)
       at java.nio.channels.spi.AbstractSelectableChannel.implCloseChannel(AbstractSelectableChannel.java:174)
       at java.nio.channels.spi.AbstractInterruptibleChannel.close(AbstractInterruptibleChannel.java:80)
       at com.koushikdutta.async.ChannelWrapper.close(SourceFile:46)
       at com.koushikdutta.async.AsyncNetworkSocket.closeInternal(SourceFile:186)
       at com.koushikdutta.async.AsyncNetworkSocket.close(SourceFile:179)
       at com.koushikdutta.async.AsyncSSLSocketWrapper.close(SourceFile:456)
       at com.koushikdutta.async.http.AsyncSocketMiddleware.maybeCleanupConnectionInfo(SourceFile:282)
       at com.koushikdutta.async.http.AsyncSocketMiddleware.access$200(SourceFile:22)
       at com.koushikdutta.async.http.AsyncSocketMiddleware$2.onCompleted(SourceFile:307)
       at com.koushikdutta.async.AsyncNetworkSocket.reportClose(SourceFile:172)
       at com.koushikdutta.async.AsyncNetworkSocket.close(SourceFile:180)
       at com.koushikdutta.async.AsyncSSLSocketWrapper.close(SourceFile:456)

...

       at com.koushikdutta.async.http.AsyncSocketMiddleware.maybeCleanupConnectionInfo(SourceFile:282)
       at com.koushikdutta.async.http.AsyncSocketMiddleware.access$200(SourceFile:22)
       at com.koushikdutta.async.http.AsyncSocketMiddleware$2.onCompleted(SourceFile:307)
       at com.koushikdutta.async.AsyncNetworkSocket.reportClose(SourceFile:172)
       at com.koushikdutta.async.AsyncNetworkSocket.close(SourceFile:180)
       at com.koushikdutta.async.AsyncSSLSocketWrapper.close(SourceFile:456)
       at com.koushikdutta.async.http.AsyncSocketMiddleware.maybeCleanupConnectionInfo(SourceFile:282)
       at com.koushikdutta.async.http.AsyncSocketMiddleware.access$200(SourceFile:22)
       at com.koushikdutta.async.http.AsyncSocketMiddleware$2.onCompleted(SourceFile:307)
       at com.koushikdutta.async.AsyncNetworkSocket.reportClose(SourceFile:172)
       at com.koushikdutta.async.AsyncNetworkSocket.close(SourceFile:180)
       at com.koushikdutta.async.AsyncSSLSocketWrapper.close(SourceFile:456)
       at com.koushikdutta.async.http.AsyncSocketMiddleware.maybeCleanupConnectionInfo(SourceFile:282)
       at com.koushikdutta.async.http.AsyncSocketMiddleware.access$200(SourceFile:22)
       at com.koushikdutta.async.http.AsyncSocketMiddleware$2.onCompleted(SourceFile:307)
       at com.koushikdutta.async.AsyncNetworkSocket.reportClose(SourceFile:172)
       at com.koushikdutta.async.AsyncNetworkSocket.close(SourceFile:180)
       at com.koushikdutta.async.AsyncSSLSocketWrapper.close(SourceFile:456)
       at com.koushikdutta.async.http.AsyncSocketMiddleware.maybeCleanupConnectionInfo(SourceFile:282)
       at com.koushikdutta.async.http.AsyncSocketMiddleware.access$200(SourceFile:22)
       at com.koushikdutta.async.http.AsyncSocketMiddleware$2.onCompleted(SourceFile:307)
       at com.koushikdutta.async.AsyncNetworkSocket.reportClose(SourceFile:172)
       at com.koushikdutta.async.AsyncNetworkSocket.close(SourceFile:180)
       at com.koushikdutta.async.AsyncSSLSocketWrapper.close(SourceFile:456)
       at com.koushikdutta.async.http.AsyncSocketMiddleware.maybeCleanupConnectionInfo(SourceFile:282)
       at com.koushikdutta.async.http.AsyncSocketMiddleware.access$200(SourceFile:22)
       at com.koushikdutta.async.http.AsyncSocketMiddleware$2.onCompleted(SourceFile:307)
       at com.koushikdutta.async.AsyncNetworkSocket.reportClose(SourceFile:172)
       at com.koushikdutta.async.AsyncNetworkSocket.close(SourceFile:180)
       at com.koushikdutta.async.AsyncSSLSocketWrapper.close(SourceFile:456)
       at com.koushikdutta.async.http.AsyncSocketMiddleware.maybeCleanupConnectionInfo(SourceFile:282)
       at com.koushikdutta.async.http.AsyncSocketMiddleware.access$200(SourceFile:22)
       at com.koushikdutta.async.http.AsyncSocketMiddleware$2.onCompleted(SourceFile:307)
       at com.koushikdutta.async.AsyncNetworkSocket.reportClose(SourceFile:172)
       at com.koushikdutta.async.AsyncNetworkSocket.close(SourceFile:180)
       at com.koushikdutta.async.AsyncSSLSocketWrapper.close(SourceFile:456)
       at com.koushikdutta.async.http.AsyncSocketMiddleware.maybeCleanupConnectionInfo(SourceFile:282)
       at com.koushikdutta.async.http.AsyncSocketMiddleware.access$200(SourceFile:22)
       at com.koushikdutta.async.http.AsyncSocketMiddleware$2.onCompleted(SourceFile:307)
       at com.koushikdutta.async.AsyncNetworkSocket.reportClose(SourceFile:172)
       at com.koushikdutta.async.AsyncNetworkSocket.close(SourceFile:180)
       at com.koushikdutta.async.AsyncSSLSocketWrapper.close(SourceFile:456)
       at com.koushikdutta.async.http.AsyncSocketMiddleware.maybeCleanupConnectionInfo(SourceFile:282)
       at com.koushikdutta.async.http.AsyncSocketMiddleware.access$200(SourceFile:22)
       at com.koushikdutta.async.http.AsyncSocketMiddleware$2.onCompleted(SourceFile:307)
       at com.koushikdutta.async.AsyncNetworkSocket.reportClose(SourceFile:172)
       at com.koushikdutta.async.AsyncNetworkSocket.close(SourceFile:180)
       at com.koushikdutta.async.AsyncSSLSocketWrapper.close(SourceFile:456)
       at com.koushikdutta.async.http.AsyncSocketMiddleware.maybeCleanupConnectionInfo(SourceFile:282)
       at com.koushikdutta.async.http.AsyncSocketMiddleware.access$200(SourceFile:22)
       at com.koushikdutta.async.http.AsyncSocketMiddleware$2.onCompleted(SourceFile:307)
       at com.koushikdutta.async.AsyncNetworkSocket.reportClose(SourceFile:172)
       at com.koushikdutta.async.AsyncNetworkSocket.close(SourceFile:180)
       at com.koushikdutta.async.AsyncSSLSocketWrapper.close(SourceFile:456)
       at com.koushikdutta.async.http.AsyncSocketMiddleware.maybeCleanupConnectionInfo(SourceFile:282)
       at com.koushikdutta.async.http.AsyncSocketMiddleware.access$200(SourceFile:22)
       at com.koushikdutta.async.http.AsyncSocketMiddleware$2.onCompleted(SourceFile:307)
       at com.koushikdutta.async.AsyncNetworkSocket.reportClose(SourceFile:172)
       at com.koushikdutta.async.AsyncNetworkSocket.close(SourceFile:180)
       at com.koushikdutta.async.AsyncSSLSocketWrapper.close(SourceFile:456)
       at com.koushikdutta.async.http.AsyncSocketMiddleware.maybeCleanupConnectionInfo(SourceFile:282)
       at com.koushikdutta.async.http.AsyncSocketMiddleware.access$200(SourceFile:22)
       at com.koushikdutta.async.http.AsyncSocketMiddleware$2.onCompleted(SourceFile:307)
       at com.koushikdutta.async.AsyncNetworkSocket.reportClose(SourceFile:172)
       at com.koushikdutta.async.AsyncNetworkSocket.close(SourceFile:180)
       at com.koushikdutta.async.AsyncSSLSocketWrapper.close(SourceFile:456)
       at com.koushikdutta.async.http.AsyncSocketMiddleware.maybeCleanupConnectionInfo(SourceFile:282)
       at com.koushikdutta.async.http.AsyncSocketMiddleware.access$200(SourceFile:22)
       at com.koushikdutta.async.http.AsyncSocketMiddleware$2.onCompleted(SourceFile:307)
       at com.koushikdutta.async.AsyncNetworkSocket.reportClose(SourceFile:172)
       at com.koushikdutta.async.AsyncNetworkSocket.close(SourceFile:180)
       at com.koushikdutta.async.AsyncSSLSocketWrapper.close(SourceFile:456)
       at com.koushikdutta.async.http.AsyncSocketMiddleware.maybeCleanupConnectionInfo(SourceFile:282)
       at com.koushikdutta.async.http.AsyncSocketMiddleware.access$200(SourceFile:22)
       at com.koushikdutta.async.http.AsyncSocketMiddleware$2.onCompleted(SourceFile:307)
       at com.koushikdutta.async.AsyncNetworkSocket.reportClose(SourceFile:172)
       at com.koushikdutta.async.AsyncNetworkSocket.close(SourceFile:180)
       at com.koushikdutta.async.AsyncSSLSocketWrapper.close(SourceFile:456)
       at com.koushikdutta.async.http.AsyncSocketMiddleware.maybeCleanupConnectionInfo(SourceFile:282)
       at com.koushikdutta.async.http.AsyncSocketMiddleware.access$200(SourceFile:22)
       at com.koushikdutta.async.http.AsyncSocketMiddleware$2.onCompleted(SourceFile:307)
       at com.koushikdutta.async.AsyncNetworkSocket.reportClose(SourceFile:172)
       at com.koushikdutta.async.AsyncNetworkSocket.close(SourceFile:180)
       at com.koushikdutta.async.AsyncSSLSocketWrapper.close(SourceFile:456)
       at com.koushikdutta.async.http.AsyncSocketMiddleware.maybeCleanupConnectionInfo(SourceFile:282)
       at com.koushikdutta.async.http.AsyncSocketMiddleware.access$200(SourceFile:22)
       at com.koushikdutta.async.http.AsyncSocketMiddleware$2.onCompleted(SourceFile:307)
       at com.koushikdutta.async.AsyncNetworkSocket.reportClose(SourceFile:172)
       at com.koushikdutta.async.AsyncNetworkSocket.close(SourceFile:180)
       at com.koushikdutta.async.AsyncSSLSocketWrapper.close(SourceFile:456)
       at com.koushikdutta.async.http.AsyncSocketMiddleware.maybeCleanupConnectionInfo(SourceFile:282)
       at com.koushikdutta.async.http.AsyncSocketMiddleware.access$200(SourceFile:22)
       at com.koushikdutta.async.http.AsyncSocketMiddleware$2.onCompleted(SourceFile:307)
       at com.koushikdutta.async.AsyncNetworkSocket.reportClose(SourceFile:172)
       at com.koushikdutta.async.AsyncNetworkSocket.close(SourceFile:180)
       at com.koushikdutta.async.AsyncSSLSocketWrapper.close(SourceFile:456)
       at com.koushikdutta.async.http.AsyncSocketMiddleware.maybeCleanupConnectionInfo(SourceFile:282)
       at com.koushikdutta.async.http.AsyncSocketMiddleware.access$200(SourceFile:22)
       at com.koushikdutta.async.http.AsyncSocketMiddleware$2.onCompleted(SourceFile:307)
       at com.koushikdutta.async.AsyncNetworkSocket.reportClose(SourceFile:172)
       at com.koushikdutta.async.AsyncNetworkSocket.close(SourceFile:180)
       at com.koushikdutta.async.AsyncSSLSocketWrapper.close(SourceFile:456)
       at com.koushikdutta.async.http.AsyncSocketMiddleware.maybeCleanupConnectionInfo(SourceFile:282)
       at com.koushikdutta.async.http.AsyncSocketMiddleware.access$200(SourceFile:22)
       at com.koushikdutta.async.http.AsyncSocketMiddleware$2.onCompleted(SourceFile:307)
       at com.koushikdutta.async.AsyncNetworkSocket.reportClose(SourceFile:172)
       at com.koushikdutta.async.AsyncNetworkSocket.close(SourceFile:180)
       at com.koushikdutta.async.AsyncSSLSocketWrapper.close(SourceFile:456)
       at com.koushikdutta.async.http.AsyncSocketMiddleware.getSocket(SourceFile:149)
       at com.koushikdutta.async.http.spdy.SpdyMiddleware.getSocket(SourceFile:311)
       at com.koushikdutta.async.http.AsyncHttpClient.executeAffinity(SourceFile:303)
       at com.koushikdutta.async.http.AsyncHttpClient.access$100(SourceFile:50)
       at com.koushikdutta.async.http.AsyncHttpClient$1.run(SourceFile:189)
       at com.koushikdutta.async.AsyncServer.lockAndRunQueue(SourceFile:708)
       at com.koushikdutta.async.AsyncServer.runLoop(SourceFile:722)
       at com.koushikdutta.async.AsyncServer.run(SourceFile:626)
       at com.koushikdutta.async.AsyncServer.access$700(SourceFile:41)
       at com.koushikdutta.async.AsyncServer$13.run(SourceFile:568)
```

**Comment by robUx4** [comment]
Oops, this is likely and AndroidAsync issue, not Ion.
https://github.com/koush/AndroidAsync/issues/309
