### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by yolapop** [koush/ion#473]
So today Ion misteriously didnt work at all... It usually worked. The url points to a zip file and my internet connection is fine.

    01-25 15:54:19.433    3411-3411/com.me W/System.err﹕ java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)
    01-25 15:54:19.437    3411-3411/com.me W/System.err﹕ at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:585)
    01-25 15:54:19.438    3411-3411/com.me W/System.err﹕ at libcore.io.IoBridge.recvfrom(IoBridge.java:560)
    01-25 15:54:19.438    3411-3411/com.me W/System.err﹕ at java.nio.SocketChannelImpl.readImpl(SocketChannelImpl.java:305)
    01-25 15:54:19.438    3411-3411/com.me W/System.err﹕ at java.nio.SocketChannelImpl.read(SocketChannelImpl.java:267)
    01-25 15:54:19.439    3411-3411/com.me W/System.err﹕ at com.koushikdutta.async.SocketChannelWrapper.read(SocketChannelWrapper.java:24)
    01-25 15:54:19.439    3411-3411/com.me W/System.err﹕ at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:128)
    01-25 15:54:19.439    3411-3411/com.me W/System.err﹕ at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:788)
    01-25 15:54:19.439    3411-3411/com.me W/System.err﹕ at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
    01-25 15:54:19.440    3411-3411/com.me W/System.err﹕ at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
    01-25 15:54:19.440    3411-3411/com.me W/System.err﹕ at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)
    01-25 15:54:19.441    3411-3411/com.me W/System.err﹕ Caused by: libcore.io.ErrnoException: recvfrom failed: ECONNRESET (Connection reset by peer)
    01-25 15:54:19.442    3411-3411/com.me W/System.err﹕ at libcore.io.Posix.recvfromBytes(Native Method)
    01-25 15:54:19.442    3411-3411/com.me W/System.err﹕ at libcore.io.Posix.recvfrom(Posix.java:126)
    01-25 15:54:19.442    3411-3411/com.me W/System.err﹕ at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:159)
    01-25 15:54:19.443    3411-3411/com.me W/System.err﹕ at libcore.io.IoBridge.recvfrom(IoBridge.java:557)
    01-25 15:54:19.443    3411-3411/com.me W/System.err﹕ ... 8 more

Uhh, I just ran sample app and it ran fine... What's wrong with my app suddenly

EDIT: the sample app failed too.. turns out it only happen when I'm downloading a ZIP file.....

**Comment by yolapop** [comment]
Ok it turns out that my connection is really slow when downloading zip file.. sorry
