### ISSUE TITLE
SSL handshake_exception

### ISSUE THREAD

**Issue by Ke3rthi** [koush/ion#482]
Hey Koush,

I have recently implemented ION in my application as below : 

        // Trust Manager
           TrustManager[] trustAllCerts = new TrustManager[]{new X509TrustManager() {
            public java.security.cert.X509Certificate[] getAcceptedIssuers() {
                return null;
            }

            public void checkClientTrusted(java.security.cert.X509Certificate[] certs, String authType) {
            }

            public void checkServerTrusted(java.security.cert.X509Certificate[] certs, String authType) {
            }
        }};
        //Install the all-trusting trust manager
        SSLContext sc = null;
        try {
            sc = SSLContext.getInstance("TLS");
            sc.init(null, trustAllCerts, new java.security.SecureRandom());
            sc.setDefault(sc);

        } catch (Exception e) {
        }

       Ion.getDefault(context).getHttpClient().getSSLSocketMiddleware().setTrustManagers(trustAllCerts);
        Ion.getDefault(context).getHttpClient().getSSLSocketMiddleware().setSSLContext(sc);
                   
                 Ion.getDefault(context).getHttpClient().getSSLSocketMiddleware().setHostnameVerifier(org.apache.http.conn.ssl.SSLSocketFactory.ALLOW_ALL_HOSTNAME_VERIFIER);

              Ion.with(context)
                .load(url)
                .setHeader("Cookie", headers.get("Cookie"))
                .setLogging("ImageLoaderTest", Log.DEBUG)
                .withBitmap()
                .placeholder(R.drawable.default_thumbnail)
                .error(R.drawable.default_thumbnail)
                .intoImageView(iView);

Even after adding all trusting trust manager, i still keep running into the SSL handshake exception  ;(  as below. Please have a look and let me know if i should look into something particular to solve this error :

02-06 18:04:11.610  16102-22890/com.locationguru.jiofriends E/ImageLoaderTest﹕ (94 ms) https://jiofriends.st.ril.com//thumbs/tejas_512_9665423493_1423222090923.jpeg: exception during response
02-06 18:04:11.610  16102-22890/com.locationguru.jiofriends E/ImageLoaderTest﹕ connection closed before response completed.
    com.koushikdutta.async.http.ConnectionClosedException: connection closed before response completed.
            at com.koushikdutta.async.http.AsyncHttpResponseImpl$2.onCompleted(AsyncHttpResponseImpl.java:54)
            at com.koushikdutta.async.AsyncSSLSocketWrapper.report(AsyncSSLSocketWrapper.java:431)
            at com.koushikdutta.async.AsyncSSLSocketWrapper.access$100(AsyncSSLSocketWrapper.java:30)
            at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:221)
            at com.koushikdutta.async.Util.emitAllData(Util.java:22)
            at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:146)
            at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:788)
            at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
            at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
            at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)
     Caused by: javax.net.ssl.SSLException: Fatal alert received handshake_failure
            at com.android.org.conscrypt.SSLEngineImpl.unwrap(SSLEngineImpl.java:484)
            at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:383)
            at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:191)
            at com.koushikdutta.async.Util.emitAllData(Util.java:22)
            at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:146)
            at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:788)
            at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
            at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
            at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)
02-06 18:04:11.610  16102-22890/com.locationguru.jiofriends E/ImageLoaderTest﹕ (95 ms) https://jiofriends.st.ril.com//thumbs/tejas_512_9665423493_1423222090923.jpeg: Connection error
02-06 18:04:11.610  16102-22890/com.locationguru.jiofriends E/ImageLoaderTest﹕ connection closed before response completed.
    com.koushikdutta.async.http.ConnectionClosedException: connection closed before response completed.
            at com.koushikdutta.async.http.AsyncHttpResponseImpl$2.onCompleted(AsyncHttpResponseImpl.java:54)
            at com.koushikdutta.async.AsyncSSLSocketWrapper.report(AsyncSSLSocketWrapper.java:431)
            at com.koushikdutta.async.AsyncSSLSocketWrapper.access$100(AsyncSSLSocketWrapper.java:30)
            at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:221)
            at com.koushikdutta.async.Util.emitAllData(Util.java:22)
            at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:146)
            at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:788)
            at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
            at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
            at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)
     Caused by: javax.net.ssl.SSLException: Fatal alert received handshake_failure
            at com.android.org.conscrypt.SSLEngineImpl.unwrap(SSLEngineImpl.java:484)
            at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:383)
            at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:191)
            at com.koushikdutta.async.Util.emitAllData(Util.java:22)
            at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:146)
            at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:788)
            at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
            at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
            at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)

**Comment by Ke3rthi** [comment]
Above issue got resolved with changing cipher suite settings on server side. ^_^  Can you please let me know the cipher suites supported by ION ?

**Comment by koush** [comment]
Cipher suites are whatever is supported on Android which varies by version. SSLv3 is not supported on later versions of Android if I recall correctly.
