### ISSUE TITLE
IOn caused my app to crash

### ISSUE THREAD

**Issue by anti43** [koush/ion#495]
02-21 10:23:55.271  18808-29766﹕ (200 ms) http://***: Recycling keep-alive socket
02-21 10:26:27.403  18808-29766 W/dalvikvm﹕ threadid=36: thread exiting with uncaught exception (group=0x41bdeba0)
02-21 10:26:27.693  18808-29766 E/AndroidRuntime﹕ FATAL EXCEPTION: ion-ion
    java.lang.NullPointerException
            at com.koushikdutta.async.http.spdy.SpdyMiddleware.invokeConnect(SpdyMiddleware.java:180)
            at com.koushikdutta.async.http.spdy.SpdyMiddleware.access$200(SpdyMiddleware.java:39)
            at com.koushikdutta.async.http.spdy.SpdyMiddleware$2.onHandshakeCompleted(SpdyMiddleware.java:195)
            at com.koushikdutta.async.AsyncSSLSocketWrapper$2.onCompleted(AsyncSSLSocketWrapper.java:106)
            at com.koushikdutta.async.AsyncNetworkSocket.reportClose(AsyncNetworkSocket.java:172)
            at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:160)
            at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:788)
            at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
            at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
            at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)

**Comment by koush** [comment]
what version

**Comment by anti43** [comment]
compile 'com.koushikdutta.ion:ion:2.+'

**Comment by koush** [comment]
https://github.com/koush/AndroidAsync/commit/7b12b29536ebc08c2c790a1f16b2cd369fb6eb14

releasing 207 now
