### ISSUE TITLE
LoadDeepZoom.run FileCache NullPointerException When Loading Local Animated GIF

### ISSUE THREAD

**Issue by touhonoob** [koush/ion#499]
The issue is caused by loading local animated gif with DeepZoom
```java
 java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.FileInputStream com.koushikdutta.async.util.FileCache.get(java.lang.String)' on a null object reference
 	at com.koushikdutta.ion.LoadDeepZoom$1.run(LoadDeepZoom.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
```

**Comment by fuwaneko** [comment]
Same here with latest version.
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.FileInputStream com.koushikdutta.async.util.FileCache.get(java.lang.String)' on a null object reference
            at com.koushikdutta.ion.LoadDeepZoom$1.run(LoadDeepZoom.java:69)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
```

**Comment by MFlisar** [comment]
I could see this happening with a filename that ends with an upper case GIF. Renaming the file helped...

Probably calling ion with the `filename.toLowerCase ()` is a workaround for that... haven't tried it yet though, but will try this soon

**Comment by mcp98252302** [comment]
Still got this problem with latest version. Anyone help?
