### ISSUE TITLE
OOM when play gif

### ISSUE THREAD

**Issue by xufan** [koush/ion#510]
i am using this awesome lib only to show some gif from network in my app:
Ion.with(mImageView).animateGif(AnimateGifMode.ANIMATE).fitXY().load(url);

Stack Trace:
java.lang.OutOfMemoryError: (Heap Size=196608KB, Allocated=191868KB)
at java.nio.ByteBuffer.allocate(ByteBuffer.java:56)
at com.koushikdutta.async.ByteBufferList.obtain(ByteBufferList.java:504)
at com.koushikdutta.async.util.Allocator.allocate(Allocator.java:28)
at com.koushikdutta.async.util.Allocator.allocate(Allocator.java:24)
at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:124)
at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:788)
at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)

**Comment by koush** [comment]
ion version?

**Comment by xufan** [comment]
my bad , this issue happened on 2.0.4 ion version 
yesterday update to the least version and no more OOM issue for now.
