### ISSUE TITLE
DataFormatException: incorrect header check. Using mobile network

### ISSUE THREAD

**Issue by khoabboy** [koush/ion#512]
03-10 10:57:55.580: E/ION(27509): java.util.zip.DataFormatException: incorrect header check
03-10 10:57:55.580: E/ION(27509): 	at java.util.zip.Inflater.inflateImpl(Native Method)
03-10 10:57:55.580: E/ION(27509): 	at java.util.zip.Inflater.inflate(Inflater.java:228)
03-10 10:57:55.580: E/ION(27509): 	at com.koushikdutta.async.http.filter.InflaterInputFilter.onDataAvailable(InflaterInputFilter.java:36)
03-10 10:57:55.580: E/ION(27509): 	at com.koushikdutta.async.Util.emitAllData(Util.java:22)
03-10 10:57:55.580: E/ION(27509): 	at com.koushikdutta.async.http.filter.ChunkedInputFilter.onDataAvailable(ChunkedInputFilter.java:87)
03-10 10:57:55.580: E/ION(27509): 	at com.koushikdutta.async.Util.emitAllData(Util.java:22)
03-10 10:57:55.580: E/ION(27509): 	at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:146)
03-10 10:57:55.580: E/ION(27509): 	at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:788)
03-10 10:57:55.580: E/ION(27509): 	at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
03-10 10:57:55.580: E/ION(27509): 	at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
03-10 10:57:55.580: E/ION(27509): 	at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)

code: 
Ion.with(MoboApp.getInstance()).load(url).setLogging("ION", Log.DEBUG)
			.setTimeout(timeOut <= 0 ? 30000 : timeOut)
			.setBodyParameter("data", jsonData)
			.setBodyParameter("command", command.toString())
			.setBodyParameter("device_id", deviceId)
			.setBodyParameter("token", accessToken)			
			.asString().setCallback(new FutureCallback<String>() {
			
			@Override
			public void onCompleted(Exception ex, String data) {
}

**Comment by koush** [comment]
i need a url to test against.

**Comment by khoabboy** [comment]
http://203.162.56.190/

some devices have this issue
user_argent:  CorporationDalvik/1.6.0 (Linux; U; Android 4.4.2; IM-A900S Build/KOT49H)
device name: sky a900

**Comment by TruongHuynh** [comment]
Hi Koush, did you get this issue?, let me khow if you need more info to test for this issue, thanks.

**Comment by tamdinh** [comment]
How about this issue? I also catche this one.

**Comment by Alamgir** [comment]
Check if you're on a data-compressing VPN like Opera Max or Onavo - I was hitting this issue when using those services as it seems they're doing something to the actual byte stream and malforming the data coming through

**Comment by JaseElder** [comment]
I was getting this issue when using the blocking call (.get()) to a server that was working fine with the asynch call.
In both cases the response Content-Encoding was deflate.
When I set the Accept-Encoding header to gzip explicitly, the issue stopped in the blocking call.

**Comment by koush** [comment]
@JaseElder I'll take a look and see if the deflater has a hang in it, but the gzip version actually inherits from it, so i doubt it...

**Comment by JaseElder** [comment]
@koush Let me know if you need a stack trace or anything...
