### ISSUE TITLE
ClassCastException with minifyEnabled

### ISSUE THREAD

**Issue by warmax** [koush/ion#515]
Since version 210 or 209 I'm getting this error when compiling with minifyEnabled.

     Caused by: java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
            at com.koushikdutta.async.parser.AsyncParserBase.getType(Unknown Source)
            at com.koushikdutta.ion.ao.a(Unknown Source)
            at com.koushikdutta.ion.ao.a(Unknown Source)
            at com.koushikdutta.ion.ao.asJsonObject(Unknown Source)

Do i have to add something to proguard-rules?

**Comment by koush** [comment]
What Ion call are you using asJsonObject or something?

**Comment by afollestad** [comment]
I noticed this issue today

```bash
java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
```

Will these fixes go out soon? @koush

**Comment by koush** [comment]
yeah, i'll do a release in a bit

**Comment by afollestad** [comment]
Cool, thank you!
