### ISSUE TITLE
The  App crashed while using proguard.

### ISSUE THREAD

**Issue by TryToBeAExcellentCoder** [koush/ion#525]
The jar worked normally in debug mode, but when I used proguard, it crashed immediately;
Here is the error, can anybody help me? Thx a lot.

java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
	at com.koushikdutta.async.parser.AsyncParserBase.getType(Unknown Source)
	at com.koushikdutta.ion.IonRequestBuilder.execute(Unknown Source)
	at com.koushikdutta.ion.IonRequestBuilder.execute(Unknown Source)

**Comment by TryToBeAExcellentCoder** [comment]
The problem is solved, just upgrade to the lastest version(from ver. 2.5.0 to ver. 2.5.3). Maybe the bug had been fixed.
