### ISSUE TITLE
Timeout Exception on GET calls. Same calls work fine on browser or when retried immediately

### ISSUE THREAD

**Issue by subodh-malgonde** [koush/ion#528]
I am on Ion 2.1.3. Some of my GET calls randomly fail with a TimoutException. The same calls work fine in a browser. Other apps on my device seem to be working fine. The call gets through when it is executed again immediately after the TimoutException.

This issue happens only on some calls and usually happens when 2-3 calls happen sequentially or simultaneously.

I have enabled verbose logging on my calls, here is one such log:

    D/Ion Logs - cities fetch﹕ (0 ms) http://api.peppertap.com/location/v1/cities/: preparing request
    D/Ion Logs - cities fetch﹕ (0 ms) http://api.peppertap.com/location/v1/cities/: preparing request
    D/Ion Logs - cities fetch﹕ (0 ms) http://api.peppertap.com/location/v1/cities/: Executing request.
    I/Ion Logs - cities fetch﹕ (9 ms) http://api.peppertap.com/location/v1/cities/: Response may be served from conditional cache
    D/Ion Logs - cities fetch﹕ (9 ms) http://api.peppertap.com/location/v1/cities/: Reusing keep-alive socket
    I/Ion Logs - cities fetch﹕ (2 ms)  http://api.peppertap.com/location/v1/cities/: Using loader: com.koushikdutta.ion.loader.HttpLoader@41c92148
    E/Ion Logs - cities fetch﹕ (30022 ms) http://api.peppertap.com/location/v1/cities/: Connection error
    E/Ion Logs - cities fetch﹕ null
    java.util.concurrent.TimeoutException
            at com.koushikdutta.async.http.AsyncHttpClient$2.run(AsyncHttpClient.java:247)
            at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:708)
            at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:725)
            at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
            at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
            at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)

**Comment by koush** [comment]
sweet, i'll put together a test case and see if i can reproduce it. this is the exact server and url i can test against?

**Comment by subodh-malgonde** [comment]
Yes - you can test this exact server and url.

**Comment by KingOfBeer** [comment]
i faced the same problem.....is this problem only occur on the latest build 2.1.3?

**Comment by subodh-malgonde** [comment]
@KingOfBeer I have been faced this problem in earlier versions as well.

**Comment by KingOfBeer** [comment]
but there is something odd... try to run your app on wifi mode...because in my case the problem only occurs when i use 3g/4g network.....

**Comment by subodh-malgonde** [comment]
@KingOfBeer Yes this problem gets worse on 3g network.

**Comment by IvanWooll** [comment]
I've seen this problem on mobile connections also. The same call will work fine in Chrome but fail when I use Ion(versions 2.0.5 and 2.1.3 both do this). 

The connection fails every single time when on a mobile connection and succeeds every time over wifi.

I turned on logging and got the output below. Note the 504 gateway timeout.

04-24 16:48:09.956: V/ION LOGGING(15781): Host: ourserver.com
04-24 16:48:09.956: V/ION LOGGING(15781): User-Agent: Dalvik/2.1.0 (Linux; U; Android 5.0.1; HTC One_M8 Build/LRX22C)
04-24 16:48:09.956: V/ION LOGGING(15781): Accept-Encoding: gzip, deflate
04-24 16:48:09.956: V/ION LOGGING(15781): Connection: keep-alive
04-24 16:48:09.956: V/ION LOGGING(15781): Accept: */*
04-24 16:48:09.956: V/ION LOGGING(15781): Cookie: PHPSESSID=58945368726efsjg
04-24 16:48:09.956: V/ION LOGGING(15781): 
04-24 16:48:09.956: V/ION LOGGING(15781): (1282 ms) ourserver.com?: request completed
04-24 16:48:20.856: V/ION LOGGING(15781): (12181 ms) http://ourserver.com?: Received headers:
04-24 16:48:20.856: V/ION LOGGING(15781): HTTP/1.1 504 Gateway Time-out
04-24 16:48:20.856: V/ION LOGGING(15781): Server: WebProxy/1.0 Pre-Alpha
04-24 16:48:20.856: V/ION LOGGING(15781): Date: Fri, 24 Apr 2015 15:48:21 GMT
04-24 16:48:20.856: V/ION LOGGING(15781): Content-Length: 0
04-24 16:48:20.856: V/ION LOGGING(15781): Connection: keep-alive
04-24 16:48:20.856: V/ION LOGGING(15781): 
04-24 16:48:20.916: D/ION LOGGING(15781): (12244 ms) http://ourserver.com/?: Response is not cacheable
04-24 16:48:20.916: V/ION LOGGING(15781): (12245 ms) http://ourserver.com?: Final (post cache response) headers:
04-24 16:48:20.916: V/ION LOGGING(15781): HTTP/1.1 504 Gateway Time-out
04-24 16:48:20.916: V/ION LOGGING(15781): Server: WebProxy/1.0 Pre-Alpha
04-24 16:48:20.916: V/ION LOGGING(15781): Date: Fri, 24 Apr 2015 15:48:21 GMT
04-24 16:48:20.916: V/ION LOGGING(15781): Content-Length: 0
04-24 16:48:20.916: V/ION LOGGING(15781): Connection: keep-alive

**Comment by koush** [comment]
Reproduced. Investigating.

**Comment by koush** [comment]
Hm only reproduced this once, and it was when I was switching between wifi and lte. hasn't happened since.

**Comment by nikoh-dev** [comment]
Hello,

I have also this problem on mobile connection.
  - If I use wifi network and call the url from my app with Ion, I have no problems.
  - If I use 3g network and call the url inside chrome, I have no problems.
  - If I use 3g network and call the url from my app with Ion, it fails one out three times

Unfortunately, I cannot share the adress of my server but I made the test with the url given above and I encouter the same issue.
Here are the logs :
04-28 11:42:45.905  28080-28080/com.nikoh.lab D/com.nikoh.test﹕ (0 ms) http://api.peppertap.com/location/v1/cities/: preparing request
04-28 11:42:45.905  28080-28080/com.nikoh.lab D/com.nikoh.test﹕ (0 ms) http://api.peppertap.com/location/v1/cities/: preparing request
04-28 11:42:45.906  28080-28080/com.nikoh.lab I/com.nikoh.test﹕ (0 ms) http://api.peppertap.com/location/v1/cities/: Using loader: com.koushikdutta.ion.loader.HttpLoader@428da460
04-28 11:42:45.906  28080-28303/com.nikoh.lab D/com.nikoh.test﹕ (0 ms) http://api.peppertap.com/location/v1/cities/: Executing request.
04-28 11:42:45.919  28080-28303/com.nikoh.lab I/com.nikoh.test﹕ (13 ms) http://api.peppertap.com/location/v1/cities/: Response may be served from conditional cache
04-28 11:42:45.920  28080-28303/com.nikoh.lab D/com.nikoh.test﹕ (13 ms) http://api.peppertap.com/location/v1/cities/: Reusing keep-alive socket
04-28 11:43:15.942  28080-28303/com.nikoh.lab E/com.nikoh.test﹕ (30036 ms) http://api.peppertap.com/location/v1/cities/: Connection error
04-28 11:43:15.943  28080-28303/com.nikoh.lab E/com.nikoh.test﹕ null
    java.util.concurrent.TimeoutException
            at com.koushikdutta.async.http.AsyncHttpClient$2.run(AsyncHttpClient.java:247)
            at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:708)
            at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:725)
            at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
            at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
            at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)

Thank you for great job !

**Comment by dominolog** [comment]
What is the status of this issue?

**Comment by KingOfBeer** [comment]
@dominolog  yeah .... progress please :)

**Comment by KingOfBeer** [comment]
does this problem still occur in the latest version? otherwise im planning to use this great lib on my next project :smile:

**Comment by yhz61010** [comment]
Same problem for me in 2.1.3 version. Unfortunately, it still happened when I upgrade to 2.1.6.
PS: I'm always using wifi network.

**Comment by KingOfBeer** [comment]
@yhz61010  i see... thank you for telling me :smile:

**Comment by Tuan-T-Nguyen** [comment]
> Hello,
> 
> I have also this problem on mobile connection.
> 
> * If I use wifi network and call the url from my app with Ion, I have no problems.
> * If I use 3g network and call the url inside chrome, I have no problems.
> * If I use 3g network and call the url from my app with Ion, it fails one out three times
> 
> Unfortunately, I cannot share the adress of my server but I made the test with the url given above and I encouter the same issue.
> 
> Here is my code :
> 
> ```
> Ion.with(this)
>            .load("http://api.peppertap.com/location/v1/cities/")
>            .setLogging("com.nikoh.test", Log.DEBUG)
>            .asString();
> ```
> Here are the logs :
> 
> ```
> 04-28 11:42:45.905  28080-28080/com.nikoh.lab D/com.nikoh.test﹕ (0 ms) http://api.peppertap.com/location/v1/cities/: preparing request
> 04-28 11:42:45.905  28080-28080/com.nikoh.lab D/com.nikoh.test﹕ (0 ms) http://api.peppertap.com/location/v1/cities/: preparing request
> 04-28 11:42:45.906  28080-28080/com.nikoh.lab I/com.nikoh.test﹕ (0 ms) http://api.peppertap.com/location/v1/cities/: Using loader: com.koushikdutta.ion.loader.HttpLoader@428da460
> 04-28 11:42:45.906  28080-28303/com.nikoh.lab D/com.nikoh.test﹕ (0 ms) http://api.peppertap.com/location/v1/cities/: Executing request.
> 04-28 11:42:45.919  28080-28303/com.nikoh.lab I/com.nikoh.test﹕ (13 ms) http://api.peppertap.com/location/v1/cities/: Response may be served from conditional cache
> 04-28 11:42:45.920  28080-28303/com.nikoh.lab D/com.nikoh.test﹕ (13 ms) http://api.peppertap.com/location/v1/cities/: Reusing keep-alive socket
> 04-28 11:43:15.942  28080-28303/com.nikoh.lab E/com.nikoh.test﹕ (30036 ms) http://api.peppertap.com/location/v1/cities/: Connection error
> 04-28 11:43:15.943  28080-28303/com.nikoh.lab E/com.nikoh.test﹕ null
>     java.util.concurrent.TimeoutException
>             at com.koushikdutta.async.http.AsyncHttpClient$2.run(AsyncHttpClient.java:247)
>             at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:708)
>             at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:725)
>             at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
>             at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
>             at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)
> ```
> Thank you for great job !

Are your resolved this solution? It happened to me. :(

**Comment by malik082009** [comment]
same here, i am using `com.koushikdutta.ion:ion:2.2.1`. I created a separate issue with error [TimeOutException](log:https://github.com/koush/ion/issues/912)
