### ISSUE TITLE
SSLException with Android 4.4.2

### ISSUE THREAD

**Issue by Sarriel** [koush/ion#531]
Hello, I am having an issue with Android 4.4.2 (API 19) while using SSL.
The same call works fine on API 21 and up.
Without SSL it works  just fine also on API 19.
Server has  proper certificate so that should be a non-issue.

Call:
Ion.with(getBaseContext())
                .load(JSON_URL)
                .progressDialog(pd)
                .asJsonObject()
                .setCallback(new FutureCallback<JsonObject>() {
                    @Override
                    public void onCompleted(Exception e, JsonObject result) {....

Stacktrace:
E/ION﹕ null
    javax.net.ssl.SSLException
            at com.koushikdutta.async.AsyncSSLSocketWrapper$2.onCompleted(AsyncSSLSocketWrapper.java:106)
            at com.koushikdutta.async.AsyncNetworkSocket.reportClose(AsyncNetworkSocket.java:172)
            at com.koushikdutta.async.AsyncNetworkSocket.close(AsyncNetworkSocket.java:180)
            at com.koushikdutta.async.AsyncSSLSocketWrapper.report(AsyncSSLSocketWrapper.java:424)
            at com.koushikdutta.async.AsyncSSLSocketWrapper.write(AsyncSSLSocketWrapper.java:400)
            at com.koushikdutta.async.AsyncSSLSocketWrapper.handleHandshakeStatus(AsyncSSLSocketWrapper.java:273)
            at com.koushikdutta.async.AsyncSSLSocketWrapper.access$000(AsyncSSLSocketWrapper.java:30)
            at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:210)
            at com.koushikdutta.async.Util.emitAllData(Util.java:22)
            at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:146)
            at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:788)
            at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
            at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
            at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)

**Comment by Xerosigma** [comment]
I'm gettng the same stack trace. My certs are trusted.

```
    compile 'com.koushikdutta.async:androidasync:2.1.3'
    compile 'com.koushikdutta.ion:ion:2.1.3'
```

```
javax.net.ssl.SSLException
at com.koushikdutta.async.AsyncSSLSocketWrapper$2.onCompleted(AsyncSSLSocketWrapper.java:106)
at com.koushikdutta.async.AsyncNetworkSocket.reportClose(AsyncNetworkSocket.java:172)
at com.koushikdutta.async.AsyncNetworkSocket.close(AsyncNetworkSocket.java:180)
at com.koushikdutta.async.AsyncSSLSocketWrapper.report(AsyncSSLSocketWrapper.java:424)
at com.koushikdutta.async.AsyncSSLSocketWrapper.access$100(AsyncSSLSocketWrapper.java:30)
at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:221)
at com.koushikdutta.async.Util.emitAllData(Util.java:22)
at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:146)
at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:788)
at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)
```

**Comment by victormx** [comment]
I resolved it updating the play store and google play services on 4.2.2
