### ISSUE TITLE
Ion won't follow HTTPS 302

### ISSUE THREAD

**Issue by caruizdiaz** [koush/ion#534]
If you do

<pre>
        Ion.with(this)
                .load("https://graph.facebook.com/1397238760592137/picture")
                .setLogging("", Log.DEBUG)
                .asBitmap()
                .setCallback(new FutureCallback<Bitmap>() {
                    @Override
                    public void onCompleted(final Exception e, final Bitmap response) {
                        if (e != null)
                            e.printStackTrace();

                        imageView.setImageBitmap(response);
                    }
                });
</pre>

You'll get:

<pre>
04-07 01:11:11.964    3932-3945/com.example.caruizdiaz.myapplication E/﹕ null
    javax.net.ssl.SSLException
            at com.koushikdutta.async.AsyncSSLSocketWrapper$2.onCompleted(AsyncSSLSocketWrapper.java:106)
            at com.koushikdutta.async.AsyncNetworkSocket.reportClose(AsyncNetworkSocket.java:172)
            at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:154)
            at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:788)
            at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
            at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
            at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)
</pre>

However, if you use HTTP instead, or use the final hop of the 302, no matter if it's HTTP or HTTPS, it works fine.

This works:
<pre>
        Ion.with(this)
               .load("https://fbcdn-profile-a.akamaihd.net/hprofile-ak-xfp1/v/t1.0-1/c57.0.337.337/10570344_1397233373926009_7641390626362848645_n.jpg?oh=ce5b931327b26f9d81e96b843482c47d&oe=55E4F6CD&__gda__=1437064944_b57ac5bfbc067c12d0529e52e2be7270")
                .setLogging("", Log.DEBUG)
                .asBitmap()
                .setCallback(new FutureCallback<Bitmap>() {
                    @Override
                    public void onCompleted(final Exception e, final Bitmap response) {
                        if (e != null)
                            e.printStackTrace();

                        imageView.setImageBitmap(response);
                    }
                });
</pre>

**Comment by caruizdiaz** [comment]
Happens on API < 21

**Comment by Xerosigma** [comment]
Related: https://github.com/koush/ion/issues/531
