### ISSUE TITLE
crash on CancelledKeyException

### ISSUE THREAD

**Issue by sandrom** [koush/ion#539]
This is one of the top performer crashes in my app using ion. Could you try to investigate? Seems like you dont check if a channel is closed from the outside, which obviously happens at times.

compile 'com.koushikdutta.ion:ion:2.0.0'

java.lang.RuntimeException: java.nio.channels.CancelledKeyException
    at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:819)
    at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
    at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
    at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)
Caused by: java.nio.channels.CancelledKeyException
    at java.nio.SelectionKeyImpl.checkValid(SelectionKeyImpl.java:99)
    at java.nio.SelectionKeyImpl.interestOps(SelectionKeyImpl.java:69)
    at com.koushikdutta.async.AsyncNetworkSocket.handleRemaining(AsyncNetworkSocket.java:102)
    at com.koushikdutta.async.AsyncNetworkSocket.write(AsyncNetworkSocket.java:84)
    at com.koushikdutta.async.Util$8.onWriteable(Util.java:194)
    at com.koushikdutta.async.Util.writeAll(Util.java:201)
    at com.koushikdutta.async.Util.writeAll(Util.java:209)
    at com.koushikdutta.async.http.HttpTransportMiddleware.exchangeHeaders(HttpTransportMiddleware.java:41)
    at com.koushikdutta.async.http.AsyncHttpClient.executeSocket(AsyncHttpClient.java:485)
    at com.koushikdutta.async.http.AsyncHttpClient.access$300(AsyncHttpClient.java:50)
    at com.koushikdutta.async.http.AsyncHttpClient$3.onConnectCompleted(AsyncHttpClient.java:287)
    at com.koushikdutta.async.http.AsyncSocketMiddleware$1$2$1.onConnectCompleted(AsyncSocketMiddleware.java:243)
    at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:816)
    ... 3 more

**Comment by sandrom** [comment]
try {
                        if (cancel.setComplete(newHandler))
                            cancel.callback.onConnectCompleted(null, newHandler);
                    }
                    catch (Exception e) {
                        throw new RuntimeException(e);
                    }

this is the part where it crashes. throwing a runtime exception that crashes the app isnt really the best of ideas here. I hope you can fix that.

**Comment by kaelitokael** [comment]
Any updates here?

**Comment by sandrom** [comment]
seems not ;)
