### ISSUE TITLE
Odd crash from Crashylytics

### ISSUE THREAD

**Issue by afollestad** [koush/ion#544]
I'm not really surprised that this happened to one user who's using Lollipop on a Samsung device (since Samsung devices have so many issues for whatever reason). Not sure if there's anything you can do, but just in case there is I'm posting it here:

```groovy
java.lang.ArithmeticException: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length
       at java.math.NativeBN.BN_new(NativeBN.java)
       at java.math.BigInt.makeValid(BigInt.java:51)
       at java.math.BigInt.putBigEndian(BigInt.java:171)
       at java.math.BigInteger.(BigInteger.java:284)
       at com.koushikdutta.async.util.FileCache.toKeyString()
       at com.koushikdutta.ion.IonBitmapRequestBuilder.computeDecodeKey()
       at com.koushikdutta.ion.IonBitmapRequestBuilder.computeDecodeKey()
       at com.koushikdutta.ion.IonBitmapRequestBuilder.executeCache()
       at com.koushikdutta.ion.IonImageViewRequestBuilder.intoImageView()
       at com.koushikdutta.ion.IonImageViewRequestBuilder.load()
       at com.afollestad.cabinet.adapters.FileAdapter.loadThumbnail()
```

**Comment by jaredsburrows** [comment]
I am seeing with with Google Admob/Analytics as well.

**Comment by acrespofn** [comment]
I'm seeing something similar on a Samsung device, Android 4.4.4.

```
java.lang.ArithmeticException: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length
	at java.math.NativeBN.BN_new()(NativeBN.java:-2)
	at java.math.BigInt.makeValid()(BigInt.java:51)
	at java.math.BigInt.putLittleEndianInts()(BigInt.java:176)
	at java.math.BigInteger.getBigInt()(BigInteger.java:322)
	at java.math.BigInteger.abs()(BigInteger.java:390)
	at java.math.Conversion.bigInteger2String()(Conversion.java:76)
	at java.math.BigInteger.toString()(BigInteger.java:873)
	at com.0000.onCreate()(MyFragment.java:67)
	at android.support.v4.app.Fragment.performCreate()(Fragment.java:1766)
	at android.support.v4.app.FragmentManagerImpl.moveToState()(FragmentManagerImpl.java:917)
	at android.support.v4.app.FragmentManagerImpl.moveToState()(FragmentManagerImpl.java:1138)
	at android.support.v4.app.BackStackRecord.run()(BackStackRecord.java:740)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions()(FragmentManagerImpl.java:1501)
	at android.support.v4.app.FragmentActivity.onStart()(FragmentActivity.java:551)
	at android.app.Instrumentation.callActivityOnStart()(Instrumentation.java:1171)
	at android.app.Activity.performStart()(Activity.java:5241)
	at android.app.ActivityThread.performLaunchActivity()(ActivityThread.java:2178)
	at android.app.ActivityThread.handleLaunchActivity()(ActivityThread.java:2271)
	at android.app.ActivityThread.access$800()(ActivityThread.java:144)
	at android.app.ActivityThread$H.handleMessage()(ActivityThread.java:1205)
	at android.os.Handler.dispatchMessage()(Handler.java:102)
	at android.os.Looper.loop()(Looper.java:136)
	at android.app.ActivityThread.main()(ActivityThread.java:5146)
	at java.lang.reflect.Method.invokeNative()(Method.java:-2)
	at java.lang.reflect.Method.invoke()(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run()(ZygoteInit.java:732)
	at com.android.internal.os.ZygoteInit.main()(ZygoteInit.java:566)
	at dalvik.system.NativeStart.main()(NativeStart.java:-2)
```
