### ISSUE TITLE
Loading images from websites protected by CloudFlare with universal SSL on, gives javax.net.ssl.SSLHandshakeException 

### ISSUE THREAD

**Issue by Saren-Arterius** [koush/ion#559]
Below is an example cat photo.
![Cat](https://img.eservice-hk.net/upload/2015/04/30/234635_2f4ab923fd9be3e35dd1a0698d4773bd.jpg)
The photo can be loaded in my app using a 4.2.2 phone (Xperia C), while not on a 5.0.2 phone (HTC M9). It just gives the following stack trace.

```
05-08 18:12:49.727    2170-2343/net.wtako.dathkg W/System.err﹕ javax.net.ssl.SSLHandshakeException: Handshake failed
05-08 18:12:49.727    2170-2343/net.wtako.dathkg W/System.err﹕ at com.google.android.gms.org.conscrypt.OpenSSLEngineImpl.unwrap(SourceFile:441)
05-08 18:12:49.727    2170-2343/net.wtako.dathkg W/System.err﹕ at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:1006)
05-08 18:12:49.727    2170-2343/net.wtako.dathkg W/System.err﹕ at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:191)
05-08 18:12:49.727    2170-2343/net.wtako.dathkg W/System.err﹕ at com.koushikdutta.async.Util.emitAllData(Util.java:22)
05-08 18:12:49.727    2170-2343/net.wtako.dathkg W/System.err﹕ at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:146)
05-08 18:12:49.727    2170-2343/net.wtako.dathkg W/System.err﹕ at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:788)
05-08 18:12:49.727    2170-2343/net.wtako.dathkg W/System.err﹕ at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
05-08 18:12:49.727    2170-2343/net.wtako.dathkg W/System.err﹕ at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
05-08 18:12:49.727    2170-2343/net.wtako.dathkg W/System.err﹕ at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)
05-08 18:12:49.727    2170-2343/net.wtako.dathkg W/System.err﹕ Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: TrustAnchor found but certificate validation failed.
05-08 18:12:49.727    2170-2343/net.wtako.dathkg W/System.err﹕ at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:344)
05-08 18:12:49.727    2170-2343/net.wtako.dathkg W/System.err﹕ at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:209)
05-08 18:12:49.727    2170-2343/net.wtako.dathkg W/System.err﹕ at com.google.android.gms.org.conscrypt.Platform.checkServerTrusted(SourceFile:163)
05-08 18:12:49.727    2170-2343/net.wtako.dathkg W/System.err﹕ at com.google.android.gms.org.conscrypt.OpenSSLEngineImpl.verifyCertificateChain(SourceFile:666)
05-08 18:12:49.727    2170-2343/net.wtako.dathkg W/System.err﹕ at com.google.android.gms.org.conscrypt.NativeCrypto.SSL_do_handshake_bio(Native Method)
05-08 18:12:49.727    2170-2343/net.wtako.dathkg W/System.err﹕ at com.google.android.gms.org.conscrypt.OpenSSLEngineImpl.unwrap(SourceFile:426)
05-08 18:12:49.727    2170-2343/net.wtako.dathkg W/System.err﹕ ... 8 more
05-08 18:12:49.727    2170-2343/net.wtako.dathkg W/System.err﹕ Caused by: java.security.cert.CertPathValidatorException: TrustAnchor found but certificate validation failed.
05-08 18:12:49.727    2170-2343/net.wtako.dathkg W/System.err﹕ at com.android.org.bouncycastle.jce.provider.PKIXCertPathValidatorSpi.engineValidate(PKIXCertPathValidatorSpi.java:122)
05-08 18:12:49.727    2170-2343/net.wtako.dathkg W/System.err﹕ at java.security.cert.CertPathValidator.validate(CertPathValidator.java:191)
05-08 18:12:49.727    2170-2343/net.wtako.dathkg W/System.err﹕ at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:331)
05-08 18:12:49.727    2170-2343/net.wtako.dathkg W/System.err﹕ ... 13 more
05-08 18:12:49.727    2170-2343/net.wtako.dathkg W/System.err﹕ Caused by: com.android.org.bouncycastle.jce.provider.AnnotatedException: TrustAnchor found but certificate validation failed.
05-08 18:12:49.727    2170-2343/net.wtako.dathkg W/System.err﹕ at com.android.org.bouncycastle.jce.provider.CertPathValidatorUtilities.findTrustAnchor(CertPathValidatorUtilities.java:237)
05-08 18:12:49.727    2170-2343/net.wtako.dathkg W/System.err﹕ at com.android.org.bouncycastle.jce.provider.PKIXCertPathValidatorSpi.engineValidate(PKIXCertPathValidatorSpi.java:117)
05-08 18:12:49.727    2170-2343/net.wtako.dathkg W/System.err﹕ ... 15 more
05-08 18:12:49.727    2170-2343/net.wtako.dathkg W/System.err﹕ Caused by: java.security.NoSuchAlgorithmException: No provider found for ecdsa-with-SHA384
05-08 18:12:49.727    2170-2343/net.wtako.dathkg W/System.err﹕ at java.security.Signature.getSignature(Signature.java:178)
05-08 18:12:49.727    2170-2343/net.wtako.dathkg W/System.err﹕ at java.security.Signature.getInstance(Signature.java:105)
05-08 18:12:49.727    2170-2343/net.wtako.dathkg W/System.err﹕ at com.google.android.gms.org.conscrypt.OpenSSLX509Certificate.verifyInternal(SourceFile:367)
05-08 18:12:49.727    2170-2343/net.wtako.dathkg W/System.err﹕ at com.google.android.gms.org.conscrypt.OpenSSLX509Certificate.verify(SourceFile:388)
05-08 18:12:49.727    2170-2343/net.wtako.dathkg W/System.err﹕ at com.android.org.bouncycastle.jce.provider.CertPathValidatorUtilities.verifyX509Certificate(CertPathValidatorUtilities.java:1431)
05-08 18:12:49.727    2170-2343/net.wtako.dathkg W/System.err﹕ at com.android.org.bouncycastle.jce.provider.CertPathValidatorUtilities.findTrustAnchor(CertPathValidatorUtilities.java:224)
05-08 18:12:49.727    2170-2343/net.wtako.dathkg W/System.err﹕ ... 16 more
```

**Comment by shanetmoore** [comment]
I got hit by this guy in the last few days. totally blew my app out of the water. 
No code changes and I had no idea what it was.


How did you manage to trace it back to cloudflare? @Saren-Arterius

**Comment by koush** [comment]
Will take a look. It may be linked to GMS version.

**Comment by koush** [comment]
think i reproduced the issue, seems related to an http/2 switchover. Fixing.

**Comment by koush** [comment]
Oh, nuts. The handshake negotation is returning http/1.1 (vs null which is what it used to do before), which is exposing a bug in ion.

**Comment by shanetmoore** [comment]
I'm actually still seeing this guy

```
05-16 23:21:38.874  31288-31445/com.sweetapps.laughinggas W/System.err﹕ javax.net.ssl.SSLHandshakeException: Handshake failed
05-16 23:21:38.884  31288-31445/com.sweetapps.laughinggas W/System.err﹕ at com.google.android.gms.org.conscrypt.OpenSSLEngineImpl.unwrap(SourceFile:441)
05-16 23:21:38.884  31288-31445/com.sweetapps.laughinggas W/System.err﹕ at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:1006)
05-16 23:21:38.884  31288-31445/com.sweetapps.laughinggas W/System.err﹕ at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:191)
05-16 23:21:38.884  31288-31445/com.sweetapps.laughinggas W/System.err﹕ at com.koushikdutta.async.Util.emitAllData(Util.java:22)
05-16 23:21:38.884  31288-31445/com.sweetapps.laughinggas W/System.err﹕ at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:146)
05-16 23:21:38.884  31288-31445/com.sweetapps.laughinggas W/System.err﹕ at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:788)
05-16 23:21:38.884  31288-31445/com.sweetapps.laughinggas W/System.err﹕ at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
05-16 23:21:38.884  31288-31445/com.sweetapps.laughinggas W/System.err﹕ at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
05-16 23:21:38.884  31288-31445/com.sweetapps.laughinggas W/System.err﹕ at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)
05-16 23:21:38.884  31288-31445/com.sweetapps.laughinggas W/System.err﹕ Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: TrustAnchor found but certificate validation failed.
```

**Comment by shanetmoore** [comment]
Doesn't occur on 5.1.0. Happens on 5.0.1 and 4.4.4.

Not sure of the reason.

@koush Can we reopen this one?

**Comment by Saren-Arterius** [comment]
I am still seeing this too. I hope we can reopen this issue.

**Comment by Saren-Arterius** [comment]
I think it's the SNI issue again. An image hosting website recently switched CF pro plan to free plan, causing images failed to load.
CF free plan used SNI for universal SSL.

**Comment by koush** [comment]
Are your apps linked to Google Play services or no?

**Comment by koush** [comment]
Someone toss me a URL I can test this again please!

**Comment by Saren-Arterius** [comment]
My app is on Google Play but I am not using any Google Play services.

For the test url, any websites under CF free plan will do: https://saren.wtako.net/Teikoku.Shounen.jpg

**Comment by davidmurdoch** [comment]
Another CloudFlare Free SSL URL that this happens on: https://cashify.pxcoach.com/. If it makes any difference, I'm POSTing there.

The happens on my Nexus 7 (5.1.1). but not on my Moto X (Gen 1, 4.4.4).

**Comment by Saren-Arterius** [comment]
Currently I have 2 workarounds. 

1. Strip all https:// to http://

2. Make Ion ignore all SSLs


    Ion.getDefault(this).getHttpClient().getSSLSocketMiddleware().setSSLContext(DatPicasso.getTrustAllSSLContext());
    Ion.getDefault(this).getHttpClient().getSSLSocketMiddleware().setHostnameVerifier(DatPicasso.getHostnameVerifier());
    
The class is named DatPicasso because Picasso also has this problem. I am also figuring out how to make loopj asynchttpclient also ignore SSLs.
    
    package net.wtako.dathkg.handlers;
    
    import android.content.Context;
    
    import com.squareup.okhttp.OkHttpClient;
    import com.squareup.picasso.OkHttpDownloader;
    import com.squareup.picasso.Picasso;
    
    import javax.net.ssl.HostnameVerifier;
    import javax.net.ssl.SSLContext;
    import javax.net.ssl.SSLSession;
    import javax.net.ssl.TrustManager;
    import javax.net.ssl.X509TrustManager;
    
    public class DatPicasso {
    
        private static final OkHttpClient client = new OkHttpClient();
        private static Picasso mInstance;
        private static OkHttpDownloader downloader;
        private static SSLContext trustAllSSLContext;
        private static HostnameVerifier hostnameVerifier;
    
        private DatPicasso(Context context) {
            client.setHostnameVerifier(getHostnameVerifier());
            client.setSslSocketFactory(getTrustAllSSLContext().getSocketFactory());
            mInstance = new Picasso.Builder(context).downloader(getDownloader()).build();
        }
    
        public static HostnameVerifier getHostnameVerifier() {
            if (hostnameVerifier != null) {
                return hostnameVerifier;
            }
            hostnameVerifier = new HostnameVerifier() {
                @Override
                public boolean verify(String s, SSLSession sslSession) {
                    return true;
                }
            };
            return hostnameVerifier;
        }
    
        public static SSLContext getTrustAllSSLContext() {
            if (trustAllSSLContext != null) {
                return trustAllSSLContext;
            }
            try {
                trustAllSSLContext = SSLContext.getInstance("TLS");
                trustAllSSLContext.init(null, getTrustAllCerts(), new java.security.SecureRandom());
            } catch (Exception e) {
                e.printStackTrace();
            }
            return trustAllSSLContext;
        }
    
        public static TrustManager[] getTrustAllCerts() {
            return new TrustManager[]{new X509TrustManager() {
                @Override
                public void checkClientTrusted(
                        java.security.cert.X509Certificate[] x509Certificates,
                        String s) throws java.security.cert.CertificateException {
                }
    
                @Override
                public void checkServerTrusted(
                        java.security.cert.X509Certificate[] x509Certificates,
                        String s) throws java.security.cert.CertificateException {
                }
    
                @Override
                public java.security.cert.X509Certificate[] getAcceptedIssuers() {
                    return new java.security.cert.X509Certificate[]{};
                }
            }};
        }
    
        public static Picasso getInstance(Context context) {
            if (mInstance == null) {
                new DatPicasso(context);
            }
            return mInstance;
        }
    
        public static OkHttpDownloader getDownloader() {
            if (downloader == null) {
                downloader = new OkHttpDownloader(client);
            }
            return downloader;
        }
    
    
    }

**Comment by koush** [comment]
Investigating

**Comment by koush** [comment]
issue reproduced, figuring out why its doing this...

**Comment by koush** [comment]
@kruton

Any idea why this might be happening against cloudfare free certs, and how to resolve it?

java.util.concurrent.ExecutionException: javax.net.ssl.SSLHandshakeException: Handshake failed
	at com.koushikdutta.async.future.SimpleFuture.getResultOrThrow(SimpleFuture.java:71)
	at com.koushikdutta.async.future.SimpleFuture.get(SimpleFuture.java:66)
	at com.koushikdutta.ion.test.Issues.testIon559(Issues.java:333)
	at java.lang.reflect.Method.invoke(Native Method)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:115)
	at junit.framework.TestResult.runProtected(TestResult.java:133)
	at junit.framework.TestResult.run(TestResult.java:118)
	at junit.framework.TestCase.run(TestCase.java:124)
	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
	at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1862)
Caused by: javax.net.ssl.SSLHandshakeException: Handshake failed
	at com.google.android.gms.org.conscrypt.OpenSSLEngineImpl.unwrap(SourceFile:441)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:1006)
	at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:194)
	at com.koushikdutta.async.Util.emitAllData(Util.java:23)
	at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:146)
	at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:788)
	at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
	at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
	at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)
Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: TrustAnchor found but certificate validation failed.
	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:344)
	at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:209)
	at com.google.android.gms.org.conscrypt.Platform.checkServerTrusted(SourceFile:164)
	at com.google.android.gms.org.conscrypt.OpenSSLEngineImpl.verifyCertificateChain(SourceFile:666)
	at com.google.android.gms.org.conscrypt.NativeCrypto.SSL_do_handshake_bio(Native Method)
	at com.google.android.gms.org.conscrypt.OpenSSLEngineImpl.unwrap(SourceFile:426)
	... 8 more
Caused by: java.security.cert.CertPathValidatorException: TrustAnchor found but certificate validation failed.
	at com.android.org.bouncycastle.jce.provider.PKIXCertPathValidatorSpi.engineValidate(PKIXCertPathValidatorSpi.java:155)
	at java.security.cert.CertPathValidator.validate(CertPathValidator.java:191)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:331)
	... 13 more
Caused by: com.android.org.bouncycastle.jce.provider.AnnotatedException: TrustAnchor found but certificate validation failed.
	at com.android.org.bouncycastle.jce.provider.CertPathValidatorUtilities.findTrustAnchor(CertPathValidatorUtilities.java:235)
	at com.android.org.bouncycastle.jce.provider.PKIXCertPathValidatorSpi.engineValidate(PKIXCertPathValidatorSpi.java:150)
	... 15 more
Caused by: java.security.NoSuchAlgorithmException: No provider found for ecdsa-with-SHA384
	at java.security.Signature.getSignature(Signature.java:178)
	at java.security.Signature.getInstance(Signature.java:105)
	at com.google.android.gms.org.conscrypt.OpenSSLX509Certificate.verifyInternal(SourceFile:367)
	at com.google.android.gms.org.conscrypt.OpenSSLX509Certificate.verify(SourceFile:388)
	at com.android.org.bouncycastle.jce.provider.CertPathValidatorUtilities.verifyX509Certificate(CertPathValidatorUtilities.java:1347)
	at com.android.org.bouncycastle.jce.provider.CertPathValidatorUtilities.findTrustAnchor(CertPathValidatorUtilities.java:222)
	... 16 more
----- end exception -----

**Comment by koush** [comment]
@kruton Seems some cipher algorithm isn't available. Shouldn't algorithm be negotiated automatically by the openssl handshake?

**Comment by koush** [comment]
@kruton Confirmed hte issue is happening with a simple (after installing with ProviderInstaller): 


```java
                URLConnection conn = new URL("https://saren.wtako.net/Teikoku.Shounen.jpg").openConnection();
                StreamUtility.readToEndAsArray(conn.getInputStream());
```

**Comment by koush** [comment]
@Saren-Arterius @davidmurdoch @shanetmoore 

GMS Conscrypt middleware can be disabled, however conscrypt is still the default SSL provider in Android L onwards. So will only fix 95%, which is still pretty good I guess. I'm digging around to see if I can disable specific cipher algorithms from the handshake negotiation as a workaround.

**Comment by kruton** [comment]
It looks like this will only happen with Conscrypt's compat/ subtree due to
the way AlgNameMapper works. I'll submit a fix in the morning.

**Comment by shanetmoore** [comment]
@koush Thanks for sticking with this.

The app I've been working on works like a search engine so images can come from anywhere. In order to get up and running quickly I just added a fallback mechanism where if ION failed for any reason, it would use Glide instead.

Not the most ideal solution but I was kind of stuck.

I'm thinking of catching javax.net.ssl.SSLException exceptions instead as a workaround and converting the URI to http. Maybe there could be a configuration option in ION to turn off ssl validation for requests? Just spitballing

___
So will only fix 95%, which is still pretty good I guess. I'm digging around to see if I can disable specific cipher algorithms from the handshake negotiation as a workaround.
___

95% is pretty good. I'm not too up to speed on cipher algorithms but I'm surprised this guy is so complex. Perhaps an alternative http client to take the load of ion? EG the way retrofit uses okhttp if its present in the system.

**Comment by koush** [comment]
Try this:

```java
        Ion.getDefault(getContext()).getConscryptMiddleware().enable(false);
```

The bug is only in GMS conscrypt. Remove that line at a later time once GMS updates per @kruton fix.

**Comment by davidmurdoch** [comment]
Thanks, @koush. Working great on Nexus 7 with Android 5.1.1 on both the LMY47V release and LMY48G release!

Are there any disadvantages to disabling conscrypt?

> GMS Conscrypt middleware can be disabled, however conscrypt is still the default SSL provider in Android L onwards. So will only fix 95%

Are you saying that disabling conscrypt middleware when running on Android 5.0+ *shouldn't* actually fix the issue? It seems to have fixed it for me (my app requires Google Play Services, if it matters).

**Comment by koush** [comment]
@davidmurdoch it will fix the issue on all platforms.

disabling conscrypt disables spdy support on older platforms though. conscrypt is also a newer, more secure, updated ssl stack. i'll post on this issue once conscrypt has been fixed.

**Comment by davidmurdoch** [comment]
Awesome. Thanks!

**Comment by akshaal** [comment]
Any chances to have a new release soon? (if https://github.com/koush/AndroidAsync/commit/f585d5b7e48ae6ec87992185a0281ac92ba10d5d fixes it)

FutureCallback.onComplete is never called in case of
```
javax.net.ssl.SSLHandshakeException: Handshake failed
    W/System.err( 2314):    at com.google.android.gms.org.conscrypt.OpenSSLEngineImpl.unwrap(SourceFile:441)
    W/System.err( 2314):    at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:383)
    W/System.err( 2314):    at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:191)
```

**Comment by koush** [comment]
@kruton this is still happening in Android M. Did this ever get resolved?

**Comment by Saren-Arterius** [comment]
@koush Currently I have a workaround.

Ion loads CF https image fine for Android >= 5, and the fix below must not be applied. (Will throw NoSuchAlgorithmException when loading a CF https image url.l

For Android < 5, I used `ProviderInstaller.installIfNeededAsync` from Google Play library, then I create and set a new `SSLContext` for Ion.

The fix will not work on phones with Play services.

**Comment by davidmurdoch** [comment]
@koush, is there an official place to file a bug report for this issue? I know the Android security team is very responsive, is there a take on this issue that could affect Android security (more than developers defaulting to fetching via unsecured HTTP connections)? Or do we know of a way to get this issue to surface in a Google/Android application on stock Android M?

**Comment by kruton** [comment]
I did fix this in July and the fix should be in Google Play Services v8.4
that was released in December.
