### ISSUE TITLE
NullPointer exception in class LoadBitmap

### ISSUE THREAD

**Issue by norman-kapschefsky** [koush/ion#560]
Hi,
in recent time I got more often this null pointer exception when requesting images:
<code>java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Exception com.koushikdutta.ion.Response.getException()' on a null object reference
            at com.koushikdutta.ion.LoadBitmap.onCompleted(LoadBitmap.java:30)
            at com.koushikdutta.ion.LoadBitmap.onCompleted(LoadBitmap.java:17)
            at com.koushikdutta.async.future.SimpleFuture.handleCallbackUnlocked(SimpleFuture.java:107)
            at com.koushikdutta.async.future.SimpleFuture.setCallback(SimpleFuture.java:175)
            at com.koushikdutta.async.future.SimpleFuture.setCallback(SimpleFuture.java:10)
            at com.koushikdutta.ion.BitmapFetcher.execute(BitmapFetcher.java:146)
            at com.koushikdutta.ion.IonBitmapRequestBuilder$2.run(IonBitmapRequestBuilder.java:229)
            at com.koushikdutta.async.AsyncServer$RunnableWrapper.run(AsyncServer.java:57)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)</code>

In method <i>onCompleted</i> of <code>LoadBitmap</code> class how can you be sure that <code>response</code> object isn't null?

<code> 
@Override
    public void onCompleted(Exception e, final Response<ByteBufferList> response) {

        if (e == null)
            e = response.getException();
        if (e != null) {
            report(e, null);
            return;
        }  ...
</code>

<code>e = response.getException();</code> is the critical part here.

Thank you in advance for investigating this.

**Comment by abhi08singh** [comment]
Please resolve it ASAP, this crashes gradually increasing in the latest Android OS
