### ISSUE TITLE
Concurrent TimeoutException when Downloading a list of files.

### ISSUE THREAD

**Issue by tunjos** [koush/ion#563]
Hi @koush 
I am downloading a List of Files (about 400), using a Service with a Fixed Thread pool of 5 Threads.
The File types are images and pdfs.
I get this error for some files (over 100)

```java
05-16 01:20:12.755  10918-11094/x.y.z (30084 ms) http://a Random file.png: E/IONLogs Connection error
05-16 01:20:12.755  10918-11094/x.y.z E/IONLogs﹕ null
    java.util.concurrent.TimeoutException
            at com.koushikdutta.async.http.AsyncHttpClient$2.run(AsyncHttpClient.java:247)
            at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:708)
            at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:725)
            at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
            at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
            at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)
```

This is the simple code I have in my Runnable object
```java
Ion.with(getApplicationContext())
                    .load(FileUrl)
                    .progress(new ProgressCallback() {
                        @Override
                        public void onProgress(long downloaded, long total) {
                            if (downloaded == total) {
                            updateTotalDownload(downloaded);
                        }
                        }
                    })
                    .write(new File(FileDestination))
                    .setCallback(new FutureCallback<File>() {
                        @Override
                        public void onCompleted(Exception e, File file) {                          
                            // download done...
                            // do stuff with the File or error
                        }
                    });
```

Please what could be wrong?
Thank you.

**Comment by tunjos** [comment]
I also see this in my stacktrace

```
open failed: EMFILE (Too many open files)
```

Could it be that my Thread Pool is pointless?

**Comment by koush** [comment]
Yeah, Ion isnt using your thread pool.

**Comment by tunjos** [comment]
Is it possible to make the call synchronous?
Or perhaps a way to limit the number of the number active async calls?

**Comment by tunjos** [comment]
FIgured out
```
Future.get() 
```
Allows me to block on requests. 
Works perfectly now. Thanks for this awesome Library.
