### ISSUE TITLE
Why isn't cacheing working here?

### ISSUE THREAD

**Issue by schwiz** [koush/ion#573]
Future calls to this url do not use the etag and have the same request headers as the first request.

                         V  (32 ms) http://video.starshop.com/emma_cosmetics_paula_abdul/dash/dash_emma_cosmetics_paula_abdul_5500_1280x720_video_track1_7.m4s:
                         V  GET /emma_cosmetics_paula_abdul/dash/dash_emma_cosmetics_paula_abdul_5500_1280x720_video_track1_7.m4s HTTP/1.1
                         V  Host: video.starshop.com
                         V  User-Agent: Dalvik/2.1.0 (Linux; U; Android 5.0; SM-G900P Build/LRX21T)
                         V  Accept-Encoding: gzip, deflate
                         V  Connection: keep-alive
                         V  Accept: */*
                         V  (34 ms) http://video.starshop.com/emma_cosmetics_paula_abdul/dash/dash_emma_cosmetics_paula_abdul_5500_1280x720_video_track1_7.m4s: request completed
                         V  (67 ms) http://video.starshop.com/emma_cosmetics_paula_abdul/dash/dash_emma_cosmetics_paula_abdul_5500_1280x720_video_track1_7.m4s: Received headers:
                         V  HTTP/1.1 200 OK
                         V  Content-Type: application/octet-stream
                         V  Content-Length: 2666667
                         V  Connection: keep-alive
                         V  Date: Fri, 29 May 2015 16:56:45 GMT
                         V  Last-Modified: Fri, 22 May 2015 22:36:48 GMT
                         V  ETag: "a7d44ffd82ea90c12c9a7b399a133a27"
                         V  Accept-Ranges: bytes
                         V  Server: AmazonS3
                         V  Age: 170
                         V  X-Cache: Hit from cloudfront
                         V  Via: 1.1 8ba75adf2ce5d1824a6bd830b1c26122.cloudfront.net (CloudFront)
                         V  X-Amz-Cf-Id: nYRKm72uUhTddzcpIzlPNBvSsmh34ouUHzgJfk69AEU8V4PGZkSIjg==
                         D  (72 ms) http://video.starshop.com/emma_cosmetics_paula_abdul/dash/dash_emma_cosmetics_paula_abdul_5500_1280x720_video_track1_7.m4s: Caching response
                         V  (73 ms) http://video.starshop.com/emma_cosmetics_paula_abdul/dash/dash_emma_cosmetics_paula_abdul_5500_1280x720_video_track1_7.m4s: Final (post cache response) headers:
                         V  HTTP/1.1 200 OK
                         V  Content-Type: application/octet-stream
                         V  Content-Length: 2666667
                         V  Connection: keep-alive
                         V  Date: Fri, 29 May 2015 16:56:45 GMT
                         V  Last-Modified: Fri, 22 May 2015 22:36:48 GMT
                         V  ETag: "a7d44ffd82ea90c12c9a7b399a133a27"
                         V  Accept-Ranges: bytes
                         V  Server: AmazonS3
                         V  Age: 170
                         V  X-Cache: Hit from cloudfront
                         V  Via: 1.1 8ba75adf2ce5d1824a6bd830b1c26122.cloudfront.net (CloudFront)
                         V  X-Amz-Cf-Id: nYRKm72uUhTddzcpIzlPNBvSsmh34ouUHzgJfk69AEU8V4PGZkSIjg==

Edit: Sometimes it seems to use cache but then an uncatchable exception is thrown.

```
18559          IonDataSource  V  Host: video.starshop.com
 18559          IonDataSource  V  User-Agent: Dalvik/2.1.0 (Linux; U; Android 5.0; SM-G900P Build/LRX21T)
 18559          IonDataSource  V  Accept-Encoding: gzip, deflate
 18559          IonDataSource  V  Connection: keep-alive
 18559          IonDataSource  V  Accept: */*
 18559          IonDataSource  V  
 18559          IonDataSource  V  (17 ms) http://video.starshop.com/paula_abdul_thinn_optics/dash/dash_109_paula_abdul_thinn_optics_615_640x360_video_track1_init.mp4: request completed
 18559          IonDataSource  V  (17 ms) http://video.starshop.com/paula_abdul_thinn_optics/dash/dash_109_paula_abdul_thinn_optics_615_640x360_video_track1_init.mp4: Received headers:
 18559          IonDataSource  V  HTTP/1.1 200 OK
 18559          IonDataSource  V  accept-ranges: bytes
 18559          IonDataSource  V  connection: keep-alive
 18559          IonDataSource  V  content-type: application/octet-stream
 18559          IonDataSource  V  date: Fri, 29 May 2015 18:11:55 GMT
 18559          IonDataSource  V  etag: "b3125e54f812381d4928bb95ed5d4e62"
 18559          IonDataSource  V  last-modified: Wed, 20 May 2015 22:57:22 GMT
 18559          IonDataSource  V  server: AmazonS3
 18559          IonDataSource  V  via: 1.1 0a89ea2120045c528ee68bee490ab23f.cloudfront.net (CloudFront)
 18559          IonDataSource  V  x-amz-cf-id: vkKY6yeWHI_XNtjET-uVMwQjtGFwADhlhH8MCn-o0ZFPzg5noTcf8w==
 18559          IonDataSource  V  x-cache: Miss from cloudfront
 18559          IonDataSource  V  Content-Length: 890
 18559          IonDataSource  V  X-Android-Sent-Millis: 1432928412238
 18559          IonDataSource  V  X-Android-Received-Millis: 1432928412238
 18559          IonDataSource  V  
 18559          IonDataSource  V  (18 ms) http://video.starshop.com/paula_abdul_thinn_optics/dash/dash_109_paula_abdul_thinn_optics_615_640x360_video_track1_init.mp4: Final (post cache response) headers:
 18559          IonDataSource  V  HTTP/1.1 200 OK
 18559          IonDataSource  V  accept-ranges: bytes
 18559          IonDataSource  V  connection: keep-alive
 18559          IonDataSource  V  content-type: application/octet-stream
 18559          IonDataSource  V  date: Fri, 29 May 2015 18:11:55 GMT
 18559          IonDataSource  V  etag: "b3125e54f812381d4928bb95ed5d4e62"
 18559          IonDataSource  V  last-modified: Wed, 20 May 2015 22:57:22 GMT
 18559          IonDataSource  V  server: AmazonS3
 18559          IonDataSource  V  via: 1.1 0a89ea2120045c528ee68bee490ab23f.cloudfront.net (CloudFront)
 18559          IonDataSource  V  x-amz-cf-id: vkKY6yeWHI_XNtjET-uVMwQjtGFwADhlhH8MCn-o0ZFPzg5noTcf8w==
 18559          IonDataSource  V  x-cache: Miss from cloudfront
 18559          IonDataSource  V  Content-Length: 890
 18559          IonDataSource  V  X-Android-Sent-Millis: 1432928412238
 18559          IonDataSource  V  X-Android-Received-Millis: 1432928412238
 18559          IonDataSource  V  X-Served-From: cache
 18559          IonDataSource  V  
 18559          IonDataSource  D  (18 ms) http://video.starshop.com/paula_abdul_thinn_optics/dash/dash_109_paula_abdul_thinn_optics_615_640x360_video_track1_init.mp4: Connection successful
 18559    starshopEventLogger  D  loadCancel [28.91, 1, 31]
 18559    starshopEventLogger  V  loadStart [28.91, 1, 0, 0]
 18559          IonDataSource  I  (0 ms) http://video.starshop.com/paula_abdul_thinn_optics/dash/dash_109_paula_abdul_thinn_optics_128_lxw_audio_track1_init.mp4: Using loader: com.koushikdutta.ion.loader.
                                  HttpLoader@17caea40
 18559         AndroidRuntime  E  FATAL EXCEPTION: ion-exoplayer_instance
 18559         AndroidRuntime  E  Process: com.pinsightmedia.starshop, PID: 18559
 18559         AndroidRuntime  E  java.lang.RuntimeException: Not all data was consumed by Util.emitAllData
 18559         AndroidRuntime  E  	at com.koushikdutta.async.Util.emitAllData(Util.java:47)
 18559         AndroidRuntime  E  	at com.koushikdutta.async.FilteredDataEmitter.onDataAvailable(FilteredDataEmitter.java:56)
 18559         AndroidRuntime  E  	at com.koushikdutta.async.Util.emitAllData(Util.java:22)
 18559         AndroidRuntime  E  	at com.koushikdutta.async.FilteredDataEmitter.onDataAvailable(FilteredDataEmitter.java:56)
 18559         AndroidRuntime  E  	at com.koushikdutta.async.http.filter.ContentLengthFilter.onDataAvailable(ContentLengthFilter.java:33)
 18559         AndroidRuntime  E  	at com.koushikdutta.async.Util.emitAllData(Util.java:22)
 18559         AndroidRuntime  E  	at com.koushikdutta.async.FilteredDataEmitter.onDataAvailable(FilteredDataEmitter.java:56)
 18559         AndroidRuntime  E  	at com.koushikdutta.async.http.cache.ResponseCacheMiddleware$CachedBodyEmitter.spewInternal(ResponseCacheMiddleware.java:454)
 18559         AndroidRuntime  E  	at com.koushikdutta.async.http.cache.ResponseCacheMiddleware$1.run(ResponseCacheMiddleware.java:172)
 18559         AndroidRuntime  E  	at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:708)
 18559         AndroidRuntime  E  	at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:725)
 18559         AndroidRuntime  E  	at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
 18559         AndroidRuntime  E  	at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
 18559         AndroidRuntime  E  	at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)
```

**Comment by schwiz** [comment]
I'm no longer concerned with this issue. Not sure what the deal was...
