### ISSUE TITLE
SpewInternal crashing the process

### ISSUE THREAD

**Issue by schwiz** [koush/ion#575]
I'm on ion 2.1.4 and this crash is frequent enough and uncatchable that I'm going to have no option but to pull ion. Do you have any clue at all anything I can do to try to prevent this?

```
java.lang.RuntimeException: Not all data was consumed by Util.emitAllData
       at com.koushikdutta.async.Util.emitAllData(Util.java:47)
       at com.koushikdutta.async.FilteredDataEmitter.onDataAvailable(FilteredDataEmitter.java:56)
       at com.koushikdutta.async.http.cache.ResponseCacheMiddleware$CachedBodyEmitter.spewInternal(ResponseCacheMiddleware.java:428)
       at com.koushikdutta.async.http.cache.ResponseCacheMiddleware$1.run(ResponseCacheMiddleware.java:172)
       at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:708)
       at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:725)
       at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
       at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
       at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)
```

**Comment by schwiz** [comment]
I'm sorry this looks to be an AndroidAsync bug actually. I will open a bug there.
