### ISSUE TITLE
Uncaught Exception in IonDrawable

### ISSUE THREAD

**Issue by schwiz** [koush/ion#578]
Seeing this come through occasionally though crashlytics. Interestingly enough the app isn't loading any gifs.

```
java.lang.OutOfMemoryError
       at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:997)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:1021)
       at com.koushikdutta.ion.gif.GifDecoder.setPixels(GifDecoder.java:257)
       at com.koushikdutta.ion.gif.GifDecoder.readImage(GifDecoder.java:504)
       at com.koushikdutta.ion.gif.GifDecoder.nextFrame(GifDecoder.java:137)
       at com.koushikdutta.ion.IonDrawable$IonGifDecoder$1.run(IonDrawable.java:190)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
```

**Comment by koush** [comment]
Thanks for the report. This is a new OOM that I gotta catch since I switched to progressive GIF decoding.

**Comment by inktomi** [comment]
We're seeing this one too.

**Comment by koush** [comment]
fea0743
