### ISSUE TITLE
CloudFlare free plan SSL handshake exception

### ISSUE THREAD

**Issue by Saren-Arterius** [koush/ion#586]
It happens on my phones, **Android 4.2** (Xperia C) **5.0.2** (HTC M9) whenever AsyncHttpClient make a request toward a **CloudFlare free plan** protected server with **SSL on**. 

In this case one of the example is (https://cf-hkgpx.wtako.net).

I will be very happy to see a fix, but it's also OK to see a workaround that ignores SSL check, since I am requesting a foreign API that does not require any means of security.

How I instantiate a AsyncHttpClient object

    asyncClient = new AsyncHttpClient(true, 80, 443);
    asyncClient.setCookieStore(getCookieStore(ctx));
    asyncClient.setUserAgent(MiscUtils.getUserAgent());
    asyncClient.setEnableRedirects(true);
    asyncClient.setMaxRetriesAndTimeout(0, 0);

The stacktrace.

    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ javax.net.ssl.SSLHandshakeException: Handshake failed
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:374)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at com.android.org.conscrypt.OpenSSLSocketImpl.waitForHandshake(OpenSSLSocketImpl.java:598)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at com.android.org.conscrypt.OpenSSLSocketImpl.getInputStream(OpenSSLSocketImpl.java:560)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at org.apache.http.impl.io.SocketInputBuffer.<init>(SocketInputBuffer.java:70)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at org.apache.http.impl.SocketHttpClientConnection.createSessionInputBuffer(SocketHttpClientConnection.java:89)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at org.apache.http.impl.conn.DefaultClientConnection.createSessionInputBuffer(DefaultClientConnection.java:170)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at org.apache.http.impl.SocketHttpClientConnection.bind(SocketHttpClientConnection.java:112)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at org.apache.http.impl.conn.DefaultClientConnection.openCompleted(DefaultClientConnection.java:129)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:172)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:372)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:519)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:148)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:179)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:108)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at java.lang.Thread.run(Thread.java:818)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x557540cf10: Failure in SSL library, usually a protocol error
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error (external/openssl/ssl/s23_clnt.c:765 0x7f9f719358:0x00000000)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:302)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ ... 21 more

**Comment by Saren-Arterius** [comment]
Derped! Was intended to post on loopj issues.
