### ISSUE TITLE
Cannot load the image when SPDY is enabled

### ISSUE THREAD

**Issue by teddychoi** [koush/ion#607]
08-08 10:33:49.322  16096-16838/kr.co.studysearch.studysearch.app D/ion!!﹕ (0 ms) https://fbcdn-profile-a.akamaihd.net/hprofile-ak-xtp1/v/t1.0-1/p200x200/1966757_604462679641595_491366303_n.jpg?oh=3d0fdf7b7dd935fe5ecec9908fd5626e&oe=56423763&__gda__=1447238082_a510028dda576c60851125df91f85750: Executing request.
    08-08 10:33:49.327  16096-16838/kr.co.studysearch.studysearch.app V/ion!!﹕ (1 ms) https://fbcdn-profile-a.akamaihd.net/hprofile-ak-xtp1/v/t1.0-1/p200x200/1966757_604462679641595_491366303_n.jpg?oh=3d0fdf7b7dd935fe5ecec9908fd5626e&oe=56423763&__gda__=1447238082_a510028dda576c60851125df91f85750: Resolving domain and connecting to all available addresses
    08-08 10:33:49.342  16096-16838/kr.co.studysearch.studysearch.app V/ion!!﹕ (17 ms) https://fbcdn-profile-a.akamaihd.net/hprofile-ak-xtp1/v/t1.0-1/p200x200/1966757_604462679641595_491366303_n.jpg?oh=3d0fdf7b7dd935fe5ecec9908fd5626e&oe=56423763&__gda__=1447238082_a510028dda576c60851125df91f85750: attempting connection to fbcdn-profile-a.akamaihd.net/208.31.254.42:443
    08-08 10:33:49.982  16096-16838/kr.co.studysearch.studysearch.app V/ion!!﹕ (656 ms) https://fbcdn-profile-a.akamaihd.net/hprofile-ak-xtp1/v/t1.0-1/p200x200/1966757_604462679641595_491366303_n.jpg?oh=3d0fdf7b7dd935fe5ecec9908fd5626e&oe=56423763&__gda__=1447238082_a510028dda576c60851125df91f85750: checking spdy handshake
    08-08 10:34:19.357  16096-16838/kr.co.studysearch.studysearch.app E/ion!!﹕ (30032 ms) https://fbcdn-profile-a.akamaihd.net/hprofile-ak-xtp1/v/t1.0-1/p200x200/1966757_604462679641595_491366303_n.jpg?oh=3d0fdf7b7dd935fe5ecec9908fd5626e&oe=56423763&__gda__=1447238082_a510028dda576c60851125df91f85750: Connection error
    08-08 10:34:19.362  16096-16838/kr.co.studysearch.studysearch.app E/ion!!﹕ null
        java.util.concurrent.TimeoutException
                at com.koushikdutta.async.http.AsyncHttpClient$2.run(AsyncHttpClient.java:247)
                at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:708)
                at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:725)
                at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
                at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
                at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)

I'm trying to load my facebook profile photo (https://fbcdn-profile-a.akamaihd.net/hprofile-ak-xtp1/v/t1.0-1/p200x200/1966757_604462679641595_491366303_n.jpg?oh=3d0fdf7b7dd935fe5ecec9908fd5626e&oe=56423763&__gda__=1447238082_a510028dda576c60851125df91f85750), but it failed.

Workaround was to disable SPDY with

    Ion.getDefault(this).getHttpClient().getSSLSocketMiddleware().setSpdyEnabled(false);

, but I wonder why it happens.

Can anyone give me any suggestion?

**Comment by koush** [comment]
Are you using to Google Play services in your app or no?

**Comment by teddychoi** [comment]
I'm using Google Play Service.
2015. 8. 9. 오전 6:20에 "Koushik Dutta" <notifications@github.com>님이 작성:

**Comment by MarcSalvat** [comment]
I had the same problem but it was happening randomly and it was hard to debug.... I found that if i launch my app with Airplane mode (wifi off), make an ION request and turn airplaine off, ION wouldn't work unless the app was restarted with Internet access (this also happens in some other situation but I couldn't find a pattern). 

This is the error that appears:

08-23 00:06:06.834 366-2997/com.msbdev.labolsa.debug I/IONLogs﹕ (132 ms) https://xxx: Response may be served from conditional cache
08-23 00:06:28.996 366-2997/com.msbdev.labolsa.debug E/IONLogs﹕ (30023 ms) https://xxx: Connection error
08-23 00:06:29.036 366-2997/com.msbdev.labolsa.debug E/IONLogs﹕ null
java.util.concurrent.TimeoutException
at com.koushikdutta.async.http.AsyncHttpClient$2.run(AsyncHttpClient.java:247)
at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:708)
at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:725)
at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)
08-23 00:06:29.156 366-366/com.msbdev.labolsa.debug W/System.err﹕ java.util.concurrent.TimeoutException


After disabling spdy like teddy suggested, it worked fine. I've hidden the URL because it needs a client certificate but I guess it happens with any https with spdy. 

Let me know if I can help!
