### ISSUE TITLE
File Download timeout with Android API 23

### ISSUE THREAD

**Issue by philbring** [koush/ion#611]
File download with Android API 23 throws timeout.
Downloads file without any problems when using Android API < 23.
API 23 Storage permissions enabled.

Logcat output:
08-20 15:19:35.904  19680-20165/net.example.app D/ION Debug? (0 ms) http://api.example.net/v1/item/20150820/full: preparing request
08-20 15:19:35.940  19680-19680/net.example.app I/ION Debug? (0 ms) http://api.example.net/v1/item/20150820/full: Using loader: com.koushikdutta.ion.loader.HttpLoader@9dd8412
08-20 15:19:35.941  19680-19755/net.example.app D/ION Debug? (0 ms) http://api.example.net/v1/item/20150820/full: Executing request.
08-20 15:19:35.942  19680-19755/net.example.app D/ION Debug? (1 ms) http://api.example.net/v1/item/20150820/full: Reusing keep-alive socket
08-20 15:19:40.946  19680-19755/net.example.app E/ION Debug? (5005 ms) http://api.example.net/v1/item/20150820/full: Connection error
08-20 15:19:40.949  19680-19755/net.example.app E/ION Debug? null
    java.util.concurrent.TimeoutException
            at com.koushikdutta.async.http.AsyncHttpClient$2.run(AsyncHttpClient.java:247)
            at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:708)
            at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:725)
            at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
            at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
            at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)

Part of download routine:
mDownloadingFuture = Ion.with(mContext)
    .load("http://api.example.net/v1/item/20150820/full")
    .setTimeout(5000)
    .noCache()
    .progressHandler(
        new ProgressCallback() {
            @Override
            public void onProgress(long downloaded, long total) {
                Log.v(TAG, "onProgress(" + downloaded + ", " + total + ")");
            }
        })
    .write(
        new File(android.os.Environment.getExternalStorageDirectory(),
            "MyFiles/20150820-full.zip")
    )
    .withResponse()
    .setCallback(new FutureCallback<Response<File>>() {
        @Override
        public void onCompleted(Exception e, Response<File> result) {
            ...
        }
    });

**Comment by philbring** [comment]
Sorry, our proxy server throws the timeout
