### ISSUE TITLE
Not all data was consumed by Util.emitAllData

### ISSUE THREAD

**Issue by battlmonstr** [koush/ion#615]
This is a duplicate of #252
I'm opening a new issue, because I don't have a right to reopen #252 (which is closed and inactive)

Library: com.koushikdutta.ion:ion:2.1.4
Android: 5.1.1
Device: Nexus 6

stack:
```
emitter: com.koushikdutta.async.http.cache.ResponseCacheMiddleware$CachedSocket@ed045b0
FATAL EXCEPTION: ion-ion
Process: com.opera.coast, PID: 6509
java.lang.RuntimeException: Not all data was consumed by Util.emitAllData
	at com.koushikdutta.async.Util.emitAllData(Util.java:47)
	at com.koushikdutta.async.FilteredDataEmitter.onDataAvailable(FilteredDataEmitter.java:56)
	at com.koushikdutta.async.http.cache.ResponseCacheMiddleware$CachedBodyEmitter.spewInternal(ResponseCacheMiddleware.java:428)
	at com.koushikdutta.async.http.cache.ResponseCacheMiddleware$1.run(ResponseCacheMiddleware.java:172)
	at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:708)
	at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:725)
	at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
	at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
	at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)
```

**Comment by schwiz** [comment]
@battlmonstr here is a bandaid for now

        //https://github.com/koush/AndroidAsync/issues/358
        com.koushikdutta.async.Util.SUPRESS_DEBUG_EXCEPTIONS = true;

**Comment by battlmonstr** [comment]
Thank you very much.

**Comment by Saren-Arterius** [comment]
@schwiz dat bandaid, thanks!

**Comment by Saren-Arterius** [comment]
However I am getting this now
```
java.lang.AssertionError: unexpected receive stream
       at com.koushikdutta.async.http.spdy.AsyncSpdyConnection.headers(SourceFile:379)
       at com.koushikdutta.async.http.spdy.Spdy3$Reader.readSynStream(SourceFile:278)
       at com.koushikdutta.async.http.spdy.Spdy3$Reader.access$000(SourceFile:122)
       at com.koushikdutta.async.http.spdy.Spdy3$Reader$4.onDataAvailable(SourceFile:219)
       at com.koushikdutta.async.DataEmitterReader.handlePendingData(SourceFile:24)
       at com.koushikdutta.async.DataEmitterReader.onDataAvailable(SourceFile:41)
       at com.koushikdutta.async.Util.emitAllData(SourceFile:23)
       at com.koushikdutta.async.AsyncSSLSocketWrapper.onDataAvailable(SourceFile:230)
       at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(SourceFile:217)
       at com.koushikdutta.async.Util.emitAllData(SourceFile:23)
       at com.koushikdutta.async.AsyncNetworkSocket.onReadable(SourceFile:146)
       at com.koushikdutta.async.AsyncServer.runLoop(SourceFile:788)
       at com.koushikdutta.async.AsyncServer.run(SourceFile:626)
       at com.koushikdutta.async.AsyncServer.access$100(SourceFile:41)
       at com.koushikdutta.async.AsyncServer$13.run(SourceFile:568
```

**Comment by Sumeet21** [comment]
having same issue when downloading file
@koush 

logcat

        I/System.out(3317): handler: null
        I/System.out(3317): emitter: HTTP/1.1 200 OK
        I/System.out(3317): Cache-Control: private
01-04 08:44:43.850: I/System.out(3317): Content-Type: application/octet-stream
01-04 08:44:43.850: I/System.out(3317): Server: Microsoft-IIS/8.5
01-04 08:44:43.850: I/System.out(3317): X-AspNet-Version: 4.0.30319
01-04 08:44:43.850: I/System.out(3317): X-Powered-By: ASP.NET
01-04 08:44:43.850: I/System.out(3317): Date: Mon, 04 Jan 2016 13:53:44 GMT
01-04 08:44:43.850: I/System.out(3317): Content-Length: 22502
01-04 08:44:43.854: I/System.out(3317): 

01-04 08:44:43.854: E/ion-alexxo(3317): (24 ms) http://192.168.20.34:1001/ShowImagefromDB.ashx?id=151: exception during response
01-04 08:44:43.855: E/ion-alexxo(3317): Not all data was consumed by Util.emitAllData
01-04 08:44:43.855: E/ion-alexxo(3317): java.lang.RuntimeException: Not all data was consumed by Util.emitAllData
01-04 08:44:43.855: E/ion-alexxo(3317): 	at com.koushikdutta.async.Util.emitAllData(Util.java:54)
01-04 08:44:43.855: E/ion-alexxo(3317): 	at com.koushikdutta.async.FilteredDataEmitter.onDataAvailable(FilteredDataEmitter.java:56)
01-04 08:44:43.855: E/ion-alexxo(3317): 	at com.koushikdutta.async.Util.emitAllData(Util.java:23)
01-04 08:44:43.855: E/ion-alexxo(3317): 	at com.koushikdutta.async.FilteredDataEmitter.onDataAvailable(FilteredDataEmitter.java:56)
01-04 08:44:43.855: E/ion-alexxo(3317): 	at com.koushikdutta.async.http.cache.ResponseCacheMiddleware$BodyCacher.onDataAvailable(ResponseCacheMiddleware.java:379)
01-04 08:44:43.855: E/ion-alexxo(3317): 	at com.koushikdutta.async.Util.emitAllData(Util.java:23)
01-04 08:44:43.855: E/ion-alexxo(3317): 	at com.koushikdutta.async.FilteredDataEmitter.onDataAvailable(FilteredDataEmitter.java:56)
01-04 08:44:43.855: E/ion-alexxo(3317): 	at com.koushikdutta.async.http.filter.ContentLengthFilter.onDataAvailable(ContentLengthFilter.java:33)
01-04 08:44:43.855: E/ion-alexxo(3317): 	at com.koushikdutta.async.Util.emitAllData(Util.java:23)
01-04 08:44:43.855: E/ion-alexxo(3317): 	at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:146)
01-04 08:44:43.855: E/ion-alexxo(3317): 	at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:789)
01-04 08:44:43.855: E/ion-alexxo(3317): 	at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:627)
01-04 08:44:43.855: E/ion-alexxo(3317): 	at com.koushikdutta.async.AsyncServer.access$4(AsyncServer.java:616)
01-04 08:44:43.855: E/ion-alexxo(3317): 	at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:569)
01-04 08:44:43.890: W/EGL_emulation(3317): eglSurfaceAttrib not implemented
01-04 08:44:43.890: W/OpenGLRenderer(3317): Failed to set EGL_SWAP_BEHAVIOR on surface 0xdf53f180, error=EGL_SUCCESS
01-04 08:44:43.959: W/System.err(3317): java.io.FileNotFoundException: /storage/emulated/0/cache/7995_profile.jpg: open failed: ENOENT (No such file or directory)
01-04 08:44:43.960: W/System.err(3317): 	at libcore.io.IoBridge.open(IoBridge.java:452)
01-04 08:44:43.960: W/System.err(3317): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
01-04 08:44:43.960: W/System.err(3317): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
01-04 08:44:43.960: W/System.err(3317): 	at com.koushikdutta.async.stream.FileDataSink.getOutputStream(FileDataSink.java:24)
01-04 08:44:43.960: W/System.err(3317): 	at com.koushikdutta.async.stream.OutputStreamDataSink.write(OutputStreamDataSink.java:50)
01-04 08:44:43.960: W/System.err(3317): 	at com.koushikdutta.async.Util$3.onDataAvailable(Util.java:127)
01-04 08:44:43.960: W/System.err(3317): 	at com.koushikdutta.async.Util.emitAllData(Util.java:23)
01-04 08:44:43.960: W/System.err(3317): 	at com.koushikdutta.async.FilteredDataEmitter.onDataAvailable(FilteredDataEmitter.java:56)
01-04 08:44:43.960: W/System.err(3317): 	at com.koushikdutta.async.Util.emitAllData(Util.java:23)
01-04 08:44:43.960: W/System.err(3317): 	at com.koushikdutta.async.FilteredDataEmitter.onDataAvailable(FilteredDataEmitter.java:56)
01-04 08:44:43.960: W/System.err(3317): 	at com.koushikdutta.async.http.cache.ResponseCacheMiddleware$BodyCacher.onDataAvailable(ResponseCacheMiddleware.java:379)
01-04 08:44:43.960: W/System.err(3317): 	at com.koushikdutta.async.Util.emitAllData(Util.java:23)
01-04 08:44:43.960: W/System.err(3317): 	at com.koushikdutta.async.FilteredDataEmitter.onDataAvailable(FilteredDataEmitter.java:56)
01-04 08:44:43.960: W/System.err(3317): 	at com.koushikdutta.async.http.filter.ContentLengthFilter.onDataAvailable(ContentLengthFilter.java:33)
01-04 08:44:43.960: W/System.err(3317): 	at com.koushikdutta.async.Util.emitAllData(Util.java:23)
01-04 08:44:43.960: W/System.err(3317): 	at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:146)
01-04 08:44:43.960: W/System.err(3317): 	at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:789)
01-04 08:44:43.960: W/System.err(3317): 	at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:627)
01-04 08:44:43.960: W/System.err(3317): 	at com.koushikdutta.async.AsyncServer.access$4(AsyncServer.java:616)
01-04 08:44:43.960: W/System.err(3317): 	at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:569)
01-04 08:44:43.960: W/System.err(3317): Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
01-04 08:44:43.960: W/System.err(3317): 	at libcore.io.Posix.open(Native Method)
01-04 08:44:43.960: W/System.err(3317): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
01-04 08:44:43.960: W/System.err(3317): 	at libcore.io.IoBridge.open(IoBridge.java:438)
01-04 08:44:43.960: W/System.err(3317): 	... 19 more
