### ISSUE TITLE
NetworkOnMainThreadException in ion (no link to my source file and don't know where this happens.)

### ISSUE THREAD

**Issue by ChristopheVersieux** [koush/ion#633]
Hello,

I cannot reproduce this bug on my devices, and that's something I got A LOT from Play Store console (cannot reproduce or get a talk with a user)

android.os.NetworkOnMainThreadException
	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1161)
	at java.net.InetAddress.lookupHostByName(InetAddress.java:418)
	at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
	at java.net.InetAddress.getAllByName(InetAddress.java:215)
	at com.android.okhttp.HostResolver$1.getAllByName(HostResolver.java:29)
	at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:232)
	at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:124)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:272)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:382)
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106)
	at cbc.a(SourceFile:83)
	at cbc.onCompleted(SourceFile:73)
	at com.koushikdutta.async.future.SimpleFuture.a(SourceFile:107)
	at com.koushikdutta.async.future.SimpleFuture.setComplete(SourceFile:141)
	at com.koushikdutta.async.future.SimpleFuture.setComplete(SourceFile:128)
	at bvg.run(SourceFile:246)
	at bkh.run(SourceFile:57)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5343)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

**Comment by ChristopheVersieux** [comment]
Note: this looks to happen in my BroadcastReceiver:

public class MyReceiver extends BroadcastReceiver {
    @Override
    public void onReceive(final Context context, Intent intent) {
            Ion.with(context).load(url).as(new TypeToken<ApiResponse>() {
            }).setCallback(new FutureCallback<ApiResponse>() {
                @Override
                public void onCompleted(Exception e, ApiResponse result) {
                    try {
.....
