### ISSUE TITLE
SSL Exception

### ISSUE THREAD

**Issue by vayzor** [koush/ion#637]
On android 4.0.4: With a trusted certificate using SSL

W/System.err: javax.net.ssl.SSLException: Fatal alert received internal_error
W/System.err:     at org.apache.harmony.xnet.provider.jsse.SSLEngineImpl.unwrap(SSLEngineImpl.java:485)
W/System.err:     at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:383)
W/System.err:     at android.support.v7.blw.onDataAvailable(SourceFile:191)
W/System.err:     at com.koushikdutta.async.Util.emitAllData(SourceFile:23)
W/System.err:     at com.koushikdutta.async.AsyncNetworkSocket.b(SourceFile:146)
W/System.err:     at com.koushikdutta.async.AsyncServer.c(SourceFile:788)
W/System.err:     at com.koushikdutta.async.AsyncServer.b(SourceFile:626)
W/System.err:     at com.koushikdutta.async.AsyncServer.a(SourceFile:41)
W/System.err:     at android.support.v7.bmc.run(SourceFile:568)

Meanwhile on Android 4.4.4 it works perfectly.
Any idea how to fix this ?

**Comment by iampawan** [comment]
Has ur issue solved?

**Comment by vayzor** [comment]
Sadly, no :/

**Comment by iampawan** [comment]
@vayzor how did u solve?

**Comment by vayzor** [comment]
It is not solved. :( Still waiting

**Comment by iampawan** [comment]
@vayzor  ask @koush  i am getting the somehow similar issue

**Comment by simondrabble** [comment]
Also seeing this in 4.2.2
