### ISSUE TITLE
SSL exception when using proguard? please help sir

### ISSUE THREAD

**Issue by iampawan** [koush/ion#647]

**Comment by iampawan** [comment]
javax.net.ssl.SSLException
11-07 11:28:50.150 3036-3399/com.sanaroopay.payoye E/MyLogs:     at com.koushikdutta.a.l.onCompleted(Unknown Source)
11-07 11:28:50.150 3036-3399/com.sanaroopay.payoye E/MyLogs:     at com.koushikdutta.a.d.a(Unknown Source)
11-07 11:28:50.150 3036-3399/com.sanaroopay.payoye E/MyLogs:     at com.koushikdutta.a.d.c(Unknown Source)
11-07 11:28:50.150 3036-3399/com.sanaroopay.payoye E/MyLogs:     at com.koushikdutta.a.j.a(Unknown Source)
11-07 11:28:50.150 3036-3399/com.sanaroopay.payoye E/MyLogs:     at com.koushikdutta.a.j.a(Unknown Source)
11-07 11:28:50.150 3036-3399/com.sanaroopay.payoye E/MyLogs:     at com.koushikdutta.a.o.a(Unknown Source)
11-07 11:28:50.150 3036-3399/com.sanaroopay.payoye E/MyLogs:     at com.koushikdutta.a.bt.a(Unknown Source)
11-07 11:28:50.150 3036-3399/com.sanaroopay.payoye E/MyLogs:     at com.koushikdutta.a.d.b(Unknown Source)
11-07 11:28:50.150 3036-3399/com.sanaroopay.payoye E/MyLogs:     at com.koushikdutta.a.s.b(Unknown Source)
11-07 11:28:50.150 3036-3399/com.sanaroopay.payoye E/MyLogs:     at com.koushikdutta.a.s.run(Unknown Source)
11-07 11:28:50.150 3036-3399/com.sanaroopay.payoye E/MyLogs:     at com.koushikdutta.a.s.a(Unknown Source)
11-07 11:28:50.150 3036-3399/com.sanaroopay.payoye E/MyLogs:     at com.koushikdutta.a.u.run(Unknown Source)

**Comment by iampawan** [comment]
@koush please help

**Comment by iampawan** [comment]
@koush Sir Please help :(

**Comment by denison-mobimove** [comment]
?HAving same issue @lampawan were u able to fix it?

**Comment by iampawan** [comment]
@denison-mobimove  No i couldn't fix it so at last i had to change the library because of no support. Currently i am using Loopj.

**Comment by denison-mobimove** [comment]
@iampawan  thanks I used Loopj and it works fine with proguard.  but sometime I got SocketTimeOut Exception. Have you encountered this prob?
