### ISSUE TITLE
OutOfMemory when upload video's base64 String to server

### ISSUE THREAD

**Issue by anlt** [koush/ion#657]
I am trying to post a base64 string to server which was converted from a video file. And this error happend. Please, take a look.
compile 'com.koushikdutta.ion:ion:2.+'

FATAL EXCEPTION: ion-ion
java.lang.OutOfMemoryError
at java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:82)
at java.lang.StringBuilder.<init>(StringBuilder.java:67)
at libcore.net.UriCodec.encode(UriCodec.java:132)
at java.net.URLEncoder.encode(URLEncoder.java:57)
at com.koushikdutta.async.http.body.UrlEncodedFormBody.buildData(UrlEncodedFormBody.java:44)
at com.koushikdutta.async.http.body.UrlEncodedFormBody.length(UrlEncodedFormBody.java:104)
at com.koushikdutta.async.http.HttpTransportMiddleware.exchangeHeaders(HttpTransportMiddleware.java:28)
at com.koushikdutta.async.http.AsyncHttpClient.executeSocket(AsyncHttpClient.java:485)
at com.koushikdutta.async.http.AsyncHttpClient.access$300(AsyncHttpClient.java:50)
at com.koushikdutta.async.http.AsyncHttpClient$3.onConnectCompleted(AsyncHttpClient.java:287)
at com.koushikdutta.async.http.AsyncSocketMiddleware$1$2$1.onConnectCompleted(AsyncSocketMiddleware.java:247)
at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:816)
at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)

**Comment by jlhonora** [comment]
String builders are not well suited for large files such as video, you'll run out of memory very soon as you've already noticed. Try uploading the video as a Multipart file if your web service allows it ([example](https://github.com/koush/ion#post-applicationx-www-form-urlencoded-and-read-a-string))

**Comment by koush** [comment]
Correct, use multipart for this. Using a URL encoded form body is no good.
