### ISSUE TITLE
NoClassDefFoundError crash on Ion.getDefault

### ISSUE THREAD

**Issue by eygraber** [koush/ion#659]
Just got this from a crash report (using Ion 2.1.6).

Samsung GT-S7275R running 4.4.4 (rooted)

```
Fatal Exception: java.lang.NoClassDefFoundError: МӘ!ۤҙࢯC
       at com.koushikdutta.ion.Ion.(Ion.java)
       at com.koushikdutta.ion.Ion.getInstance(Ion.java:114)
       at com.koushikdutta.ion.Ion.getDefault(Ion.java:100)
       at com.my.app.util.ImageLoader.attachToApp(ImageLoader.java:45)
       at com.my.app.MyApplication.onCreate(MyApplication.java:34)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4473)
       at android.app.ActivityThread.access$1500(ActivityThread.java:144)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5146)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.ClassNotFoundException: Didn't find class "МӘ!ۤҙࢯC" on path: DexPathList[[zip file "/data/app/com.my.app.app1.apk"],nativeLibraryDirectories=[/data/app-lib/com.my.app.app-1, /vendor/lib, /system/lib]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
       at com.koushikdutta.ion.Ion.(Ion.java)
       at com.koushikdutta.ion.Ion.getInstance(Ion.java:114)
       at com.koushikdutta.ion.Ion.getDefault(Ion.java:100)
       at com.my.app.util.ImageLoader.attachToApp(ImageLoader.java:45)
       at com.my.app.MyApplication.onCreate(MyApplication.java:34)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4473)
       at android.app.ActivityThread.access$1500(ActivityThread.java:144)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5146)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by koush** [comment]
uhh wtf? did proguard do something? The class name is garble.

**Comment by eygraber** [comment]
That was my first thought, but this build has been in the wild on 40K+ devices for 3 months (and the last time I touched ProGuard was over 8 months ago).

**Comment by chiragsudani** [comment]
I am also getting same issue..

please help me how to solve it?
