### ISSUE TITLE
SSL exception when minfyEnabled - True in prelollipop devices ..Help

### ISSUE THREAD

**Issue by iampawan** [koush/ion#661]
javax.net.ssl.SSLException
11-07 11:28:50.150 3036-3399/com.sanaroopay.payoye E/MyLogs: at com.koushikdutta.a.l.onCompleted(Unknown Source)
11-07 11:28:50.150 3036-3399/com.sanaroopay.payoye E/MyLogs: at com.koushikdutta.a.d.a(Unknown Source)
11-07 11:28:50.150 3036-3399/com.sanaroopay.payoye E/MyLogs: at com.koushikdutta.a.d.c(Unknown Source)
11-07 11:28:50.150 3036-3399/com.sanaroopay.payoye E/MyLogs: at com.koushikdutta.a.j.a(Unknown Source)
11-07 11:28:50.150 3036-3399/com.sanaroopay.payoye E/MyLogs: at com.koushikdutta.a.j.a(Unknown Source)
11-07 11:28:50.150 3036-3399/com.sanaroopay.payoye E/MyLogs: at com.koushikdutta.a.o.a(Unknown Source)
11-07 11:28:50.150 3036-3399/com.sanaroopay.payoye E/MyLogs: at com.koushikdutta.a.bt.a(Unknown Source)
11-07 11:28:50.150 3036-3399/com.sanaroopay.payoye E/MyLogs: at com.koushikdutta.a.d.b(Unknown Source)
11-07 11:28:50.150 3036-3399/com.sanaroopay.payoye E/MyLogs: at com.koushikdutta.a.s.b(Unknown Source)
11-07 11:28:50.150 3036-3399/com.sanaroopay.payoye E/MyLogs: at com.koushikdutta.a.s.run(Unknown Source)
11-07 11:28:50.150 3036-3399/com.sanaroopay.payoye E/MyLogs: at com.koushikdutta.a.s.a(Unknown Source)
11-07 11:28:50.150 3036-3399/com.sanaroopay.payoye E/MyLogs: at com.koushikdutta.a.u.run(Unknown Source)

**Comment by koush** [comment]
Hm, i'm gonna need the unobfuscated stack.

**Comment by iampawan** [comment]
There is no error when the code is unobfuscated . @koush  
What i am supposed to send you?
And thanks for your reply

**Comment by iampawan** [comment]
@koush reply soon.. Thannks

**Comment by iampawan** [comment]
avax.net.ssl.SSLException: Fatal alert received handshake_failure
12-08 10:37:42.734 3720-4287/com.sanaroopay.payoye W/System.err:     at org.apache.harmony.xnet.provider.jsse.SSLEngineImpl.unwrap(SSLEngineImpl.java:485)
12-08 10:37:42.734 3720-4287/com.sanaroopay.payoye W/System.err:     at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:383)
12-08 10:37:42.734 3720-4287/com.sanaroopay.payoye W/System.err:     at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:191)
12-08 10:37:42.734 3720-4287/com.sanaroopay.payoye W/System.err:     at com.koushikdutta.async.Util.emitAllData(Util.java:23)
12-08 10:37:42.734 3720-4287/com.sanaroopay.payoye W/System.err:     at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:146)
12-08 10:37:42.734 3720-4287/com.sanaroopay.payoye W/System.err:     at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:788)
12-08 10:37:42.734 3720-4287/com.sanaroopay.payoye W/System.err:     at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
12-08 10:37:42.734 3720-4287/com.sanaroopay.payoye W/System.err:     at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
12-08 10:37:42.734 3720-4287/com.sanaroopay.payoye W/System.err:     at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)
12-08 10:37:42.964 3720-4287/com.sanaroopay.payoye W/System.err: javax.net.ssl.SSLException: Fatal alert received handshake_failure
12-08 10:37:42.964 3720-4287/com.sanaroopay.payoye W/System.err:     at org.apache.harmony.xnet.provider.jsse.SSLEngineImpl.unwrap(SSLEngineImpl.java:485)
12-08 10:37:42.964 3720-4287/com.sanaroopay.payoye W/System.err:     at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:383)
12-08 10:37:42.964 3720-4287/com.sanaroopay.payoye W/System.err:     at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:191)
12-08 10:37:42.964 3720-4287/com.sanaroopay.payoye W/System.err:     at com.koushikdutta.async.Util.emitAllData(Util.java:23)
12-08 10:37:42.964 3720-4287/com.sanaroopay.payoye W/System.err:     at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:146)
12-08 10:37:42.964 3720-4287/com.sanaroopay.payoye W/System.err:     at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:788)
12-08 10:37:42.964 3720-4287/com.sanaroopay.payoye W/System.err:     at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
12-08 10:37:42.964 3720-4287/com.sanaroopay.payoye W/System.err:     at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
12-08 10:37:42.964 3720-4287/com.sanaroopay.payoye W/System.err:     at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)


This occuring in android 4.0.4 even if proguard is disabled

**Comment by iampawan** [comment]
please help @koush

**Comment by elroid** [comment]
I'm having this issue as well. It appears only on my JellyBean test device (GalaxyNexus) and only when obfuscated. Here's the stack trace:
```
com.intohand.util.exception.NetworkException: Fatal alert received handshake_failure
	at org.apache.harmony.xnet.provider.jsse.SSLEngineImpl.unwrap(SSLEngineImpl.java:485)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:383)
	at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(SourceFile:191)
	at com.koushikdutta.async.Util.emitAllData(SourceFile:23)
	at com.koushikdutta.async.AsyncNetworkSocket.onReadable(SourceFile:146)
	at com.koushikdutta.async.AsyncServer.runLoop(SourceFile:788)
	at com.koushikdutta.async.AsyncServer.run(SourceFile:626)
	at com.koushikdutta.async.AsyncServer.access$700(SourceFile:41)
	at com.koushikdutta.async.AsyncServer$13.run(SourceFile:568)
```
and immediately after...
```
java.util.concurrent.ExecutionException: javax.net.ssl.SSLException
	at com.koushikdutta.async.future.SimpleFuture.getResultOrThrow(SourceFile:71)
	at com.koushikdutta.async.future.SimpleFuture.get(SourceFile:66)
	at com.myapp.android.action.BaseAction.load(SourceFile:116)
	at com.myapp.android.action.BaseAction.get(SourceFile:63)
	at com.myapp.android.action.UserAction$3.run(SourceFile:122)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)
Caused by: javax.net.ssl.SSLException
	at com.koushikdutta.async.AsyncSSLSocketWrapper$2.onCompleted(SourceFile:106)
	at com.koushikdutta.async.AsyncNetworkSocket.reportClose(SourceFile:172)
	at com.koushikdutta.async.AsyncNetworkSocket.close(SourceFile:180)
	at com.koushikdutta.async.AsyncSSLSocketWrapper.report(SourceFile:424)
	at com.koushikdutta.async.AsyncSSLSocketWrapper.access$000(SourceFile:30)
	at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(SourceFile:221)
	at com.koushikdutta.async.Util.emitAllData(SourceFile:23)
	at com.koushikdutta.async.AsyncNetworkSocket.onReadable(SourceFile:146)
	at com.koushikdutta.async.AsyncServer.runLoop(SourceFile:788)
	at com.koushikdutta.async.AsyncServer.run(SourceFile:626)
	at com.koushikdutta.async.AsyncServer.access$700(SourceFile:41)
	at com.koushikdutta.async.AsyncServer$13.run(SourceFile:568)
```

**Comment by elroid** [comment]
Interestingly, i've been doing some checks and seems that this *isn't* a proguard issue but rather an issue with `debuggable true` in the gradle config. If i set this to false, the issue is solved, even when `minifyEnabled true`. Since these flags are usually changed in tandem and obfuscation is usually what causes issues, this explains the misdiagnosis. The plot thickens...

**Comment by elroid** [comment]
This is a pretty serious issue. I've had to completely remove Ion the day before launch because of this issue, and you can be sure i won't consider using it again until this is addressed...

**Comment by elroid** [comment]
Any movement on this issue? I ended up removing Ion from the project in question but my next one will in fact use Lantern, so I'm concerned about running into the issue again...

**Comment by iampawan** [comment]
I removed ion im using loopj

**Comment by koush** [comment]
Got a URL i can test?

**Comment by koush** [comment]
Try disabling Conscrypt and SPDY within ion, let me know if either of those resolves it.

**Comment by Matarata94** [comment]
I removed shitty ION from my whole project coz of this issue. It cost 3 days for me 👎

**Comment by dudhatparesh** [comment]
Issue is still there with Proguard Enabled

**Comment by ChristopheVersieux** [comment]
I just got the same issue.

URL = https://api.irail.be/liveboard.php/?id=BE.NMBS.008881000&format=JSON&fast=true&lang=en:

Which works fine on newer Android versions.
