### ISSUE TITLE
Failed resolving Lcom/koushikdutta/ion/Ion$Config$1

### ISSUE THREAD

**Issue by gloffreda** [koush/ion#668]
Having this issue when trying using post method. 
Any help ?

Thanks

    Ion.with(getApplicationContext())
                    .load("http://apidflash.x.cc/users/login")
                    .setBodyParameter("userName", mEmail)
                    .setBodyParameter("passWord", mPassword)
                    .asJsonObject()
                    .setCallback(new FutureCallback<JsonObject>() {
                        @Override
                        public void onCompleted(Exception e, JsonObject result) {
                            // Result

                            try {
                                if (result.get("error").toString().equalsIgnoreCase("false")) {
                                    finish();
                                    Intent i = new Intent(getApplicationContext(), MainActivity.class);
                                    startActivity(i);
                                } else {
                                    // Result is NOT "OK"
                                    String error = result.get("message").toString();
                                    Toast.makeText(getApplicationContext(), error, Toast.LENGTH_LONG).show(); // This will show the user what went wrong with a toast
                                }
                            } catch (Exception Je) {
                                // This method will run if something goes wrong with the json, like a typo to the json-key or a broken JSON.

                                Log.e("ERRORCON", Log.getStackTraceString(Je));
                            }

                        }
                    });
12-21 17:34:29.611 18077-18758/com.spark.displaytrack I/dalvikvm: Failed resolving Lcom/koushikdutta/ion/Ion$Config$1; interface 9391 'Lcom/koushikdutta/ion/loader/AsyncHttpRequestFactory;'
12-21 17:34:29.611 18077-18758/com.spark.displaytrack W/dalvikvm: Link of class 'Lcom/koushikdutta/ion/Ion$Config$1;' failed
12-21 17:34:29.621 18077-18758/com.spark.displaytrack D/dalvikvm: DexOpt: unable to opt direct call 0xf3bb at 0x07 in Lcom/koushikdutta/ion/Ion$Config;.
12-21 17:34:29.621 18077-18758/com.spark.displaytrack W/dalvikvm: threadid=13: thread exiting with uncaught exception (group=0x4162ac08)
12-21 17:34:29.771 18077-18758/com.spark.displaytrack E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
Process: com.spark.displaytrack, PID: 18077
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:300)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.NoClassDefFoundError: com.koushikdutta.ion.Ion$Config$1
at com.koushikdutta.ion.Ion$Config.(Ion.java:556)
at com.koushikdutta.ion.Ion.(Ion.java:146)
at com.koushikdutta.ion.Ion.getInstance(Ion.java:114)
at com.koushikdutta.ion.Ion.getDefault(Ion.java:100)
at com.koushikdutta.ion.Ion.with(Ion.java:72)
at com.spark.displaytrack.LoginActivity$UserLoginTask.doInBackground(LoginActivity.java:344)
at com.spark.displaytrack.LoginActivity$UserLoginTask.doInBackground(LoginActivity.java:329)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
at java.lang.Thread.run(Thread.java:841)

**Comment by gloffreda** [comment]
To complete. I'm using Android Studio in a MAC and it worked before. 3 weeks without touching the code, and then now, first time after this time, I'm getting this error.
Thanks for your help
