### ISSUE TITLE
Ion is in unusable state after issuing a request with no network connection available

### ISSUE THREAD

**Issue by vovan888** [koush/ion#693]
Using Ion 2.1.7 on Android 5.0
Steps to reproduce:
1. Disconnect the network cable (or disable wifi)
2. Run an app that makes requests with Ion, it shows network error
3. Connect network cable again, click retry
4. The same request shows error again

The only way to make it work again is to kill the app and start it again (i.e. recreate Ion instance)

Maybe there is a way to drop default Ion instance and create it again ?

Can be related to #293 

Here is the log:

    D/checkregister: (0 ms) https://192.168.1.0:88/get.php: preparing request
    D/checkregister: (0 ms) https://192.168.1.0:88/get.php: preparing request
    I/checkregister: (0 ms) https://192.168.1.0:88/get.php: Using loader: com.koushikdutta.ion.loader.HttpLoader@31a387e2
    D/checkregister: (0 ms) https://192.168.1.0:88/get.php: Executing request.
    I/art: Debugger is active
    E/checkregister: (30019 ms) https://192.168.1.0:88/get.php: Connection error
    E/checkregister: null
                java.util.concurrent.TimeoutException
                    at com.koushikdutta.async.http.AsyncHttpClient$2.run(AsyncHttpClient.java:247)
                    at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:709)
                    at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:726)
                    at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:627)
                    at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
                    at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:569)

**Comment by SeanSWatkins** [comment]
I've been experiencing the same issue. (I know this isn't helpful, I just wanted to be subscribed to the thread)

**Comment by muhammad-naderi** [comment]
same here,

but hey, It's been almost 9 months ! any update ?
