### ISSUE TITLE
Ion Error when loading https url

### ISSUE THREAD

**Issue by arminbiz** [koush/ion#698]
I want to make a connection to instagram’s api through this address: https://instagram.com/api/ But when trying via ion, it works with some ISPs and doesn’t work with some others and throws an exception. It seems that it’s because of the address starting with https, because it works fine with http .
I’d appreciate your help Thanks for your guides in advance 

Log :

```
03-02 12:46:51.042: E/instagram_log(3770): (30241 ms) https://instagram.com/api/v1/accounts/login/: Connection error
03-02 12:46:51.045: E/instagram_log(3770):  null
03-02 12:46:51.045: E/instagram_log(3770):  java.util.concurrent.TimeoutException
03-02 12:46:51.045: E/instagram_log(3770):  at com.koushikdutta.async.http.AsyncHttpClient$2.run(AsyncHttpClient.java:247)
03-02 12:46:51.045: E/instagram_log(3770):  at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:708)
03-02 12:46:51.045: E/instagram_log(3770):  at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:725)
03-02 12:46:51.045: E/instagram_log(3770):  at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
03-02 12:46:51.045: E/instagram_log(3770):  at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
03-02 12:46:51.045: E/instagram_log(3770):  at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)
03-02 12:46:51.155: W/System.err(3770):     java.util.concurrent.TimeoutException
03-02 12:46:51.156: W/System.err(3770):     at com.koushikdutta.async.http.AsyncHttpClient$2.run(AsyncHttpClient.java:247)
03-02 12:46:51.172: W/System.err(3770):     at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:708)
03-02 12:46:51.172: W/System.err(3770):     at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:725)
03-02 12:46:51.172: W/System.err(3770):     at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
03-02 12:46:51.172: W/System.err(3770):     at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
03-02 12:46:51.172: W/System.err(3770):     at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)
```

**Comment by larrytech7** [comment]
I have this same issue and really need a way out urgently. anyone know of a more convinient library for android asynchronous requests?

**Comment by larrytech7** [comment]
I have realized that there a couple of ways we can address this. I will be compiling a possible fix towards this.
