### ISSUE TITLE
Sometimes NPE occurred when calling Ion.getDefault()

### ISSUE THREAD

**Issue by erkasraim** [koush/ion#704]
My Code in Application.onCreate()
`Ion ion = Ion.getDefault(context);
 ion.getConscryptMiddleware().enable(false);
 ion.getHttpClient().getSSLSocketMiddleware().setSpdyEnabled(false);`

> 03-28 16:33:32.530 13109-13109/net.daum.android.daum E/DaumApp: null
                                                                java.lang.NullPointerException: uri
                                                                    at com.koushikdutta.ion.IonBitmapRequestBuilder$1.<init>(IonBitmapRequestBuilder.java:30)
                                                                    at com.koushikdutta.ion.IonBitmapRequestBuilder.<clinit>(IonBitmapRequestBuilder.java:28)
                                                                    at com.koushikdutta.ion.Ion.<init>(Ion.java:149)
                                                                    at com.koushikdutta.ion.Ion.getInstance(Ion.java:114)
                                                                    at com.koushikdutta.ion.Ion.getDefault(Ion.java:100)
                                                                    at net.daum.android.daum.DaumApplication.initIonLibrary(DaumApplication.java:274)
                                                                    at net.daum.android.daum.DaumApplication.onCreate(DaumApplication.java:102)
                                                                    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
                                                                    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4551)
                                                                    at android.app.ActivityThread.access$1500(ActivityThread.java:163)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:157)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5335)
                                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:515)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
                                                                    at dalvik.system.NativeStart.main(Native Method)

Bitmap cache guess when I seem to have a problem.
Because, It does not occur when clear app data.

**Comment by erkasraim** [comment]
Find problem. error occur anther place.

It went confusing.

IonBitmapRequestBuilder.FUTURE_BITMAP_NULL_URI 
is static value. and create Exception on Application.onCreate()

stack trace is always print it.
