### ISSUE TITLE
connection closed before response completed

### ISSUE THREAD

**Issue by ozrozcn** [koush/ion#718]
Hi, 

When i add  cookie as header with addHeader method and setStringBody together, i can not send response.

My cookie is like above, .AspNet.ExternalCookie=NHQqfDY8Yi6CWOmUGezroPVon18Egs9P2XUOl7I2GWmgs4YPErrROxufJkTJfXPUBvKoXk9aftxnfxrJVocPjSjxrhN94E_RXHu3IloFhJ-KSPDdqExFRr6QMtGYPBdiCShCEWwHrG8bpDCFhTp6PEMb_PJwK0s0FAPgr-LyM-giMRzstz1kS2c0CYZq2H0g8vEwH_dg0G0pl0yz90Mj5CG96JDjfEziYZSHYac0JMa7MmMFUsHBgPaolBIbcqVgnyjx9_AzPptAdOA1jea-50P0G7cqNwYe709ISpmFImmRUydfTScEUoijAjaFlFDEAdYdgt2smNyrwRfybKDFesWdEK0l-66gzBTA64QGsU621EyASyvaO-oBjB9HnEympFSbFMcNgNbhyDtzvBBz0IzKpzvP30YfQaRtAgvyLpk9YT2saVjZzAiVK9K1KArClW7a6lhH9cc_XG01BtOd4O9xfsOeujYEJTqAjGLgV6sBEKYxgeV8CJjDEMcb5Gm

But, when i set the cookie short string like "asd", i can send response also. Is it related with length of cookie?

Ion.with(get())
                    .load(getGetURL(prefix, postfix))
                    .setLogging("SERVICE ION", Log.DEBUG)
                    .setHeader("Cookie", cookie)
                    .setHeader("Content-Type", "application/json")
                    .addHeader("Authorization", access_token)
                    .asString()
                    .withResponse().....

and error after about two minutes;

`(120259 ms) http://v1.api.jestiniyap.bilgetech.biz/Account/RegisterExternal: exception during response
connection closed before response completed.
com.koushikdutta.async.http.ConnectionClosedException: connection closed before response completed.
    at com.koushikdutta.async.http.AsyncHttpResponseImpl$2.onCompleted(AsyncHttpResponseImpl.java:54)
    at com.koushikdutta.async.AsyncNetworkSocket.reportEnd(AsyncNetworkSocket.java:236)
    at com.koushikdutta.async.AsyncNetworkSocket.reportEndPending(AsyncNetworkSocket.java:248)
    at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:165)
    at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:789)
    at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:627)
    at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
    at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:569)
 Caused by: java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)
    at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:588)
    at libcore.io.IoBridge.recvfrom(IoBridge.java:564)
    at java.nio.SocketChannelImpl.readImpl(SocketChannelImpl.java:342)
    at java.nio.SocketChannelImpl.read(SocketChannelImpl.java:304)
    at com.koushikdutta.async.SocketChannelWrapper.read(SocketChannelWrapper.java:24)
    at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:134)
    at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:789) 
    at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:627) 
    at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41) 
    at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:569) 
 Caused by: android.system.ErrnoException: recvfrom failed: ECONNRESET (Connection reset by peer)
    at libcore.io.Posix.recvfromBytes(Native Method)
    at libcore.io.Posix.recvfrom(Posix.java:181)
    at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:245)
    at libcore.io.IoBridge.recvfrom(IoBridge.java:561)
    at java.nio.SocketChannelImpl.readImpl(SocketChannelImpl.java:342) 
    at java.nio.SocketChannelImpl.read(SocketChannelImpl.java:304) 
    at com.koushikdutta.async.SocketChannelWrapper.read(SocketChannelWrapper.java:24) 
    at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:134) 
    at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:789) 
    at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:627) 
    at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41) 
    at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:569) `

**Comment by mohitkumar0571** [comment]
This may be helpful
[Android Networking Complete networking](https://github.com/amitshekhariitbhu/AndroidNetworking)

**Comment by muhammad-naderi** [comment]
+1
same issue here
did you find any solution ?

**Comment by ozrozcn** [comment]
yes i have a solution. it is to change the network lib to volley...

**Comment by koush** [comment]
@muhammad-naderi are you also hitting an IIS server or something else?

**Comment by muhammad-naderi** [comment]
Yes I do
But sending the exact same request from postman has no problem 
So it gotta do something with the size of header in the library

**Comment by koush** [comment]
fixed https://github.com/koush/AndroidAsync/commit/be28a1583e2bd4b9c3f2a1ecb292ceaf1088b934
