### ISSUE TITLE
Out of memory issue for GIF

### ISSUE THREAD

**Issue by CodeBoyChd** [koush/ion#756]
I am getting the out of memory for the gifs
-----------------------------------------------

java.lang.OutOfMemoryError
at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:601)
at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:434)
at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:840)
at android.content.res.Resources.createFromResourceStream(Resources.java:2513)
at android.content.res.Resources.loadDrawable(Resources.java:2165)
at android.content.res.MiuiResources.loadDrawable(MiuiResources.java:393)
at android.content.res.Resources.loadDrawable(Resources.java:2072)
at android.content.res.Resources.getDrawable(Resources.java:710)
at android.support.v7.widget.ResourcesWrapper.getDrawable(ResourcesWrapper.java:128)
at android.support.v7.widget.TintResources.getDrawable(TintResources.java:45)
at com.koushikdutta.ion.IonDrawable.tryGetPlaceholderResource(IonDrawable.java:430)
at com.koushikdutta.ion.IonDrawable.updateLayers(IonDrawable.java:297)
at com.koushikdutta.ion.IonImageViewRequestBuilder.setIonDrawable(IonImageViewRequestBuilder.java:105)
at com.koushikdutta.ion.IonImageViewRequestBuilder.intoImageView(IonImageViewRequestBuilder.java:180)
at com.koushikdutta.ion.IonImageViewRequestBuilder.load(IonImageViewRequestBuilder.java:72)

**Comment by rayworks** [comment]
@CodeBoyChd 
I think it has something to do with the placeholder you provided. Decoding a huge placeholder resource in the default way causes this problem. And certainly the code could be improved.
