### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by mightyfrog** [koush/ion#765]
I don't know how to reproduce it but crashlytics reports this exception every once a while.

Fatal Exception: java.lang.ClassCastException: java.util.Collections$UnmodifiableRandomAccessList cannot be cast to com.koushikdutta.async.e.l
       at com.koushikdutta.async.http.Headers.toStringBuilder(SourceFile:114)
       at com.koushikdutta.async.http.Headers.toPrefixString(SourceFile:133)
       at com.koushikdutta.async.http.AsyncHttpResponseImpl.toString(SourceFile:167)
       at java.lang.StringBuilder.append(StringBuilder.java:202)
       at com.koushikdutta.async.Util.emitAllData(SourceFile:49)
       at com.koushikdutta.async.FilteredDataEmitter.onDataAvailable(SourceFile:56)
       at com.koushikdutta.async.Util.emitAllData(SourceFile:23)
       at com.koushikdutta.async.FilteredDataEmitter.onDataAvailable(SourceFile:56)
       at com.koushikdutta.async.http.cache.ResponseCacheMiddleware$CachedBodyEmitter.sendCachedDataOnNetworkThread(SourceFile:460)
       at com.koushikdutta.async.http.cache.ResponseCacheMiddleware$CachedBodyEmitter$1.run(SourceFile:428)
       at com.koushikdutta.async.AsyncServer.lockAndRunQueue(SourceFile:709)
       at com.koushikdutta.async.AsyncServer.runLoop(SourceFile:723)
       at com.koushikdutta.async.AsyncServer.run(SourceFile:5627)
       at com.koushikdutta.async.AsyncServer$13.run(SourceFile:569)

**Comment by paopao-yu** [comment]
I met the same problem: 
Fatal Exception: java.lang.ClassCastException: java.util.Collections$UnmodifiableRandomAccessList cannot be cast to com.koushikdutta.async.util.TaggedList
       at com.koushikdutta.async.http.Headers.toStringBuilder(Headers.java:114)
       at com.koushikdutta.async.http.Headers.toPrefixString(Headers.java:132)
       at com.koushikdutta.async.http.AsyncHttpResponseImpl.toString(AsyncHttpResponseImpl.java:167)
       at java.lang.String.valueOf(String.java:2683)
       at java.lang.StringBuilder.append(StringBuilder.java:129)
       at com.koushikdutta.async.Util.emitAllData(Util.java:49)
       at com.koushikdutta.async.FilteredDataEmitter.onDataAvailable(FilteredDataEmitter.java:56)
       at com.koushikdutta.async.Util.emitAllData(Util.java:23)
       at com.koushikdutta.async.FilteredDataEmitter.onDataAvailable(FilteredDataEmitter.java:56)
       at com.koushikdutta.async.http.cache.ResponseCacheMiddleware$CachedBodyEmitter.sendCachedDataOnNetworkThread(ResponseCacheMiddleware.java:460)
       at com.koushikdutta.async.http.cache.ResponseCacheMiddleware$CachedBodyEmitter$1.run(ResponseCacheMiddleware.java:428)
       at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:739)
       at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:757)
       at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:657)
       at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44)
       at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:599)
