### ISSUE TITLE
Crash on htc 4.2.2 while calling webservice

### ISSUE THREAD

**Issue by cisankit** [koush/ion#773]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     java.lang.ExceptionInInitializerError
                                                                         at com.cis.sharelocation.LoginActivity.callLoginService(LoginActivity.java:71)
                                                                         at com.cis.sharelocation.LoginActivity.access$100(LoginActivity.java:26)
                                                                         at com.cis.sharelocation.LoginActivity$1.onClick(LoginActivity.java:50)
                                                                         at android.view.View.performClick(View.java:4231)
                                                                         at android.view.View$PerformClick.run(View.java:17537)
                                                                         at android.os.Handler.handleCallback(Handler.java:725)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                         at android.os.Looper.loop(Looper.java:158)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5751)
                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:511)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1083)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:850)
                                                                         at dalvik.system.NativeStart.main(Native Method)
                                                                      Caused by: java.lang.NoClassDefFoundError: com.koushikdutta.ion.Ion$1
                                                                         at com.koushikdutta.ion.Ion.<clinit>(Ion.java:256)
                                                                         at com.cis.sharelocation.LoginActivity.callLoginService(LoginActivity.java:71) 
                                                                         at com.cis.sharelocation.LoginActivity.access$100(LoginActivity.java:26) 
                                                                         at com.cis.sharelocation.LoginActivity$1.onClick(LoginActivity.java:50) 
                                                                         at android.view.View.performClick(View.java:4231) 
                                                                         at android.view.View$PerformClick.run(View.java:17537) 
                                                                         at android.os.Handler.handleCallback(Handler.java:725) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:92) 
                                                                         at android.os.Looper.loop(Looper.java:158) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5751) 
                                                                         at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1083) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:850) 
                                                                         at dalvik.system.NativeStart.main(Native Method)

**Comment by chiragsudani** [comment]
I am also getting same issue..

looking for solution..

**Comment by super0xie** [comment]
Same here

**Comment by koush** [comment]
Looks like your ion library is missing.

**Comment by super0xie** [comment]
https://stackoverflow.com/a/28722345/5220959
This answer solved my issue
