### ISSUE TITLE
javax.net.ssl.SSLHandshakeException: Cannot verify DH params

### ISSUE THREAD

**Issue by shiburagi** [koush/ion#783]
10-19 17:18:27.033 31581-31581/<packagename> W/System.err: javax.net.ssl.SSLException: Error occured in delegated task:javax.net.ssl.SSLException: Unexpected exception
10-19 17:18:27.033 31581-31581/<packagename> W/System.err:     at com.android.org.conscrypt.HandshakeProtocol.fatalAlert(HandshakeProtocol.java:316)
10-19 17:18:27.033 31581-31581/<packagename> W/System.err:     at com.android.org.conscrypt.HandshakeProtocol.wrap(HandshakeProtocol.java:268)
10-19 17:18:27.034 31581-31581/<packagename> W/System.err:     at com.android.org.conscrypt.SSLEngineImpl.wrap(SSLEngineImpl.java:693)
10-19 17:18:27.034 31581-31581/<packagename> W/System.err:     at javax.net.ssl.SSLEngine.wrap(SSLEngine.java:438)
10-19 17:18:27.034 31581-31581/<packagename> W/System.err:     at com.koushikdutta.async.AsyncSSLSocketWrapper.write(AsyncSSLSocketWrapper.java:386)
10-19 17:18:27.034 31581-31581/<packagename> W/System.err:     at com.koushikdutta.async.AsyncSSLSocketWrapper.handleHandshakeStatus(AsyncSSLSocketWrapper.java:276)
10-19 17:18:27.034 31581-31581/<packagename> W/System.err:     at com.koushikdutta.async.AsyncSSLSocketWrapper.access$000(AsyncSSLSocketWrapper.java:30)
10-19 17:18:27.034 31581-31581/<packagename> W/System.err:     at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:213)
10-19 17:18:27.034 31581-31581/<packagename> W/System.err:     at com.koushikdutta.async.Util.emitAllData(Util.java:23)
10-19 17:18:27.034 31581-31581/<packagename> W/System.err:     at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:152)
10-19 17:18:27.034 31581-31581/<packagename> W/System.err:     at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:820)
10-19 17:18:27.035 31581-31581/<packagename> W/System.err:     at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:657)
10-19 17:18:27.035 31581-31581/<packagename> W/System.err:     at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44)
10-19 17:18:27.035 31581-31581/<packagename> W/System.err:     at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:599)
10-19 17:18:27.035 31581-31581/<packagename> W/System.err: Caused by: com.android.org.conscrypt.AlertException: javax.net.ssl.SSLException: Unexpected exception
10-19 17:18:27.035 31581-31581/<packagename> W/System.err:     at com.android.org.conscrypt.HandshakeProtocol.fatalAlert(HandshakeProtocol.java:316)
10-19 17:18:27.035 31581-31581/<packagename> W/System.err:     at com.android.org.conscrypt.ClientHandshakeImpl.processServerHelloDone(ClientHandshakeImpl.java:497)
10-19 17:18:27.036 31581-31581/<packagename> W/System.err:     at com.android.org.conscrypt.ClientHandshakeImpl$1.run(ClientHandshakeImpl.java:283)
10-19 17:18:27.036 31581-31581/<packagename> W/System.err:     at com.android.org.conscrypt.DelegatedTask.run(DelegatedTask.java:36)
10-19 17:18:27.036 31581-31581/<packagename> W/System.err:     at com.koushikdutta.async.AsyncSSLSocketWrapper.handleHandshakeStatus(AsyncSSLSocketWrapper.java:272)
10-19 17:18:27.036 31581-31581/<packagename> W/System.err: 	... 8 more
10-19 17:18:27.036 31581-31581/<packagename> W/System.err: Caused by: javax.net.ssl.SSLException: Unexpected exception
10-19 17:18:27.036 31581-31581/<packagename> W/System.err: 	... 13 more
10-19 17:18:27.037 31581-31581/<packagename> W/System.err: Caused by: com.android.org.conscrypt.AlertException: javax.net.ssl.SSLHandshakeException: Cannot verify DH params
10-19 17:18:27.037 31581-31581/<packagename> W/System.err:     at com.android.org.conscrypt.HandshakeProtocol.fatalAlert(HandshakeProtocol.java:305)
10-19 17:18:27.038 31581-31581/<packagename> W/System.err:     at com.android.org.conscrypt.ClientHandshakeImpl.processServerHelloDone(ClientHandshakeImpl.java:476)
10-19 17:18:27.038 31581-31581/<packagename> W/System.err: 	... 11 more
10-19 17:18:27.039 31581-31581/<packagename> W/System.err: Caused by: javax.net.ssl.SSLHandshakeException: Cannot verify DH params
10-19 17:18:27.039 31581-31581/<packagename> W/System.err: 	... 13 more

I can't figure out the root problem for this exception, is there any configuration that I need to set or declare because when I use different/other library for sending the request, I able to get the response. May I know if there any solution for this problem??

**Comment by sjwoodr** [comment]
I'm having the same issue, but it only seems to happen in Android 4.x phones, not 5.x or anything newer.

**Comment by shiburagi** [comment]
yes, that is the issue..

**Comment by sjwoodr** [comment]
I solved it yesterday.  Well, not really... but I found a workaround:

1. Remove Ion from your project
2. Integrate https://github.com/loopj/android-async-http into it

I really did not want to get rid of Ion, but this problem was a deal-breaker for me since I have a bunch of customers with older Android 4.x phones and I couldn't leave them with a broken app.  :(

Gson + AndroidAsyncHttp gave me everything that I really needed that I was using from Ion anyway.

**Comment by shiburagi** [comment]
for me, remove completely ion and use OkHttp library...haha

**Comment by choudharypranay** [comment]
This happens due to a particular windows update(My WebSocket server is deployed in IIS). I as not able to find exactly which windows update is causing this. Uninstalling all windows updates after 3/8/2016 solved the issue.

**Comment by paopao-yu** [comment]
I got the same problem too

**Comment by muhammad-naderi** [comment]
any update on this ?
