### ISSUE TITLE
TimeOutException

### ISSUE THREAD

**Issue by muhammad-naderi** [koush/ion#787]
Hi, 

Using your awesome library, I have an app in which I connect to two different sets of webservices, on two machines.
The problem is that sometimes, Ion throws TimeOutException, while I'm positively sure that there is no problem with endpoints since all of them have passed numerous Load and performance tests.

Unfortunately I can not report how exactly one can reproduce the problem, 
but some data on how most of the times problem occurs:
- mostly when I'm between debugging sessions, I come across a bug (in webservice calls) I change the code in Android Studio, and run the application, the very next time that I call the webservice there is a good chance that I get a TimeOutException. 

somehow I feel a great connection with my issue and https://github.com/koush/ion/issues/197 

here is the stack trace:

```
(30029 ms) http://192.168.1.101/shygunvalidation/api/Validation/GetVersion: Connection error
null
                                                                                      java.util.concurrent.TimeoutException
                                                                                          at com.koushikdutta.async.http.AsyncHttpClient$2.run(AsyncHttpClient.java:246)
                                                                                          at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:739)
                                                                                          at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:757)
                                                                                          at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:657)
                                                                                          at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44)
                                                                                          at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:599)


```

**Comment by mihir97** [comment]
Is there any fix for this?
Facing the same issue frequently on some devices.

**Comment by Tuan-T-Nguyen** [comment]
Up, still happen

**Comment by malik082009** [comment]
@koush you need to address this issue. it happens randomly
