### ISSUE TITLE
SSL issue when GPS conscrypt isn't available on Android N

### ISSUE THREAD

**Issue by koush** [koush/ion#832]
reported by @rsfez

```
06-19 14:28:16.542 24207-24301/XXX W/IonConscrypt: Conscrypt initialization failed.
                                                                     com.google.android.gms.common.GooglePlayServicesRepairableException: Google Play Services not available
                                                                         at com.google.android.gms.common.zzo.zzah(Unknown Source)
                                                                         at com.google.android.gms.common.zze.zzas(Unknown Source)
                                                                         at com.google.android.gms.security.ProviderInstaller.installIfNeeded(Unknown Source)
                                                                         at com.koushikdutta.ion.conscrypt.ConscryptMiddleware.initialize(ConscryptMiddleware.java:58)
                                                                         at com.koushikdutta.ion.conscrypt.ConscryptMiddleware.initialize(ConscryptMiddleware.java:75)
                                                                         at com.koushikdutta.ion.conscrypt.ConscryptMiddleware.getSocket(ConscryptMiddleware.java:117)
                                                                         at com.koushikdutta.async.http.AsyncHttpClient.executeAffinity(AsyncHttpClient.java:301)
                                                                         at com.koushikdutta.async.http.AsyncHttpClient.access$100(AsyncHttpClient.java:51)
                                                                         at com.koushikdutta.async.http.AsyncHttpClient$1.run(AsyncHttpClient.java:190)
                                                                         at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:740)
                                                                         at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:758)
                                                                         at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:658)
                                                                         at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44)
                                                                         at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:600)


06-19 14:28:16.614 24207-24301/XXX W/System.err: javax.net.ssl.SSLHandshakeException: Handshake failed
06-19 14:28:16.614 24207-24301/XXX W/System.err:     at com.android.org.conscrypt.OpenSSLEngineImpl.unwrap(OpenSSLEngineImpl.java:441)
06-19 14:28:16.614 24207-24301/XXX W/System.err:     at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:1270)
06-19 14:28:16.614 24207-24301/XXX W/System.err:     at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:194)
06-19 14:28:16.614 24207-24301/XXX W/System.err:     at com.koushikdutta.async.Util.emitAllData(Util.java:23)
06-19 14:28:16.614 24207-24301/XXX W/System.err:     at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:152)
06-19 14:28:16.614 24207-24301/XXX W/System.err:     at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:821)
06-19 14:28:16.614 24207-24301/XXX W/System.err:     at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:658)
06-19 14:28:16.614 24207-24301/XXX W/System.err:     at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44)
06-19 14:28:16.614 24207-24301/XXX W/System.err:     at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:600)
06-19 14:28:16.614 24207-24301/XXX W/System.err: Caused by: javax.net.ssl.SSLProtocolException: SSL handshake terminated: ssl=0x7551ba6c00: Failure in SSL library, usually a protocol error
06-19 14:28:16.614 24207-24301/XXX W/System.err: error:10000460:SSL routines:OPENSSL_internal:reason(1120) (external/boringssl/src/ssl/s3_pkt.c:641 0x7571b3c2e0:0x00000001)
06-19 14:28:16.614 24207-24301/XXX W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake_bio(Native Method)
06-19 14:28:16.614 24207-24301/XXX W/System.err:     at com.android.org.conscrypt.OpenSSLEngineImpl.unwrap(OpenSSLEngineImpl.java:426)
06-19 14:28:16.614 24207-24301/XXX W/System.err: 	... 8 more
```

**Comment by koush** [comment]
Fixed with https://github.com/koush/AndroidAsync/commit/10abb692d0fecb51a14ddba209a3f1adb0c77316

createSSLEngine(host,port) MUST be used on Android N+.

**Comment by koush** [comment]
Turned out to actually be a SPDY bug. The SNI thing was a red herring.

https://github.com/koush/ion/commit/c5a3c864fd49c2bd149de0d65b265679426ff4ad

**Comment by koush** [comment]
SPDY is deprecated anyways, so time to turn it off.

**Comment by rsfez** [comment]
Thank you!
