### ISSUE TITLE
Peer not trusted by any of the system trust managers.

### ISSUE THREAD

**Issue by Faisal-Naseer** [koush/ion#833]
while using your library I am getting error

> 06-24 16:58:47.344 8807-8807/com.technologics.developer.motorcityarabia W/System.err: java.util.concurrent.ExecutionException: com.koushikdutta.async.AsyncSSLException: Peer not trusted by any of the system trust managers.
> 06-24 16:58:47.344 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at com.koushikdutta.async.future.SimpleFuture.getResultOrThrow(SimpleFuture.java:71)
> 06-24 16:58:47.344 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at com.koushikdutta.async.future.SimpleFuture.get(SimpleFuture.java:66)
> 06-24 16:58:47.344 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at com.technologics.developer.motorcityarabia.OfferBrandsActivity$1.onResponse(OfferBrandsActivity.java:154)
> 06-24 16:58:47.344 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
> 06-24 16:58:47.344 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at android.os.Handler.handleCallback(Handler.java:733)
> 06-24 16:58:47.344 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
> 06-24 16:58:47.344 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at android.os.Looper.loop(Looper.java:136)
> 06-24 16:58:47.354 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5135)
> 06-24 16:58:47.354 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
> 06-24 16:58:47.354 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
> 06-24 16:58:47.354 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
> 06-24 16:58:47.354 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
> 06-24 16:58:47.354 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at dalvik.system.NativeStart.main(Native Method)
> 06-24 16:58:47.354 8807-8807/com.technologics.developer.motorcityarabia W/System.err: Caused by: com.koushikdutta.async.AsyncSSLException: Peer not trusted by any of the system trust managers.
> 06-24 16:58:47.354 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at com.koushikdutta.async.AsyncSSLSocketWrapper.handleHandshakeStatus(AsyncSSLSocketWrapper.java:322)
> 06-24 16:58:47.354 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at com.koushikdutta.async.AsyncSSLSocketWrapper.write(AsyncSSLSocketWrapper.java:401)
> 06-24 16:58:47.364 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at com.koushikdutta.async.AsyncSSLSocketWrapper.handleHandshakeStatus(AsyncSSLSocketWrapper.java:276)
> 06-24 16:58:47.364 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at com.koushikdutta.async.AsyncSSLSocketWrapper.access$000(AsyncSSLSocketWrapper.java:30)
> 06-24 16:58:47.364 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:213)
> 06-24 16:58:47.364 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at com.koushikdutta.async.Util.emitAllData(Util.java:23)
> 06-24 16:58:47.364 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:152)
> 06-24 16:58:47.364 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:820)
> 06-24 16:58:47.364 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:657)
> 06-24 16:58:47.364 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44)
> 06-24 16:58:47.364 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:599)
> 06-24 16:58:47.364 8807-8807/com.technologics.developer.motorcityarabia W/System.err: Caused by: javax.net.ssl.SSLException: hostname <www.motorscity.com> has been denied
> 06-24 16:58:47.374 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at com.koushikdutta.async.AsyncSSLSocketWrapper.handleHandshakeStatus(AsyncSSLSocketWrapper.java:306)
> 06-24 16:58:47.374 8807-8807/com.technologics.developer.motorcityarabia W/System.err: 	... 10 more
> 06-24 16:59:53.574 8807-8807/com.technologics.developer.motorcityarabia W/System.err: java.util.concurrent.ExecutionException: com.koushikdutta.async.AsyncSSLException: Peer not trusted by any of the system trust managers.
> 06-24 16:59:53.574 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at com.koushikdutta.async.future.SimpleFuture.getResultOrThrow(SimpleFuture.java:71)
> 06-24 16:59:53.574 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at com.koushikdutta.async.future.SimpleFuture.get(SimpleFuture.java:66)
> 06-24 16:59:53.574 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at com.technologics.developer.motorcityarabia.OfferBrandsActivity$1.onResponse(OfferBrandsActivity.java:154)
> 06-24 16:59:53.584 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
> 06-24 16:59:53.584 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at android.os.Handler.handleCallback(Handler.java:733)
> 06-24 16:59:53.584 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
> 06-24 16:59:53.584 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at android.os.Looper.loop(Looper.java:136)
> 06-24 16:59:53.584 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5135)
> 06-24 16:59:53.594 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
> 06-24 16:59:53.594 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
> 06-24 16:59:53.594 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
> 06-24 16:59:53.594 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
> 06-24 16:59:53.594 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at dalvik.system.NativeStart.main(Native Method)
> 06-24 16:59:53.594 8807-8807/com.technologics.developer.motorcityarabia W/System.err: Caused by: com.koushikdutta.async.AsyncSSLException: Peer not trusted by any of the system trust managers.
> 06-24 16:59:53.594 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at com.koushikdutta.async.AsyncSSLSocketWrapper.handleHandshakeStatus(AsyncSSLSocketWrapper.java:322)
> 06-24 16:59:53.594 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at com.koushikdutta.async.AsyncSSLSocketWrapper.write(AsyncSSLSocketWrapper.java:401)
> 06-24 16:59:53.604 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at com.koushikdutta.async.AsyncSSLSocketWrapper.handleHandshakeStatus(AsyncSSLSocketWrapper.java:276)
> 06-24 16:59:53.604 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at com.koushikdutta.async.AsyncSSLSocketWrapper.access$000(AsyncSSLSocketWrapper.java:30)
> 06-24 16:59:53.604 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:213)
> 06-24 16:59:53.604 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at com.koushikdutta.async.Util.emitAllData(Util.java:23)
> 06-24 16:59:53.604 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:152)
> 06-24 16:59:53.604 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:820)
> 06-24 16:59:53.604 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:657)
> 06-24 16:59:53.604 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44)
> 06-24 16:59:53.614 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:599)
> 06-24 16:59:53.614 8807-8807/com.technologics.developer.motorcityarabia W/System.err: Caused by: javax.net.ssl.SSLException: hostname <www.motorscity.com> has been denied
> 06-24 16:59:53.614 8807-8807/com.technologics.developer.motorcityarabia W/System.err:     at com.koushikdutta.async.AsyncSSLSocketWrapper.handleHandshakeStatus(AsyncSSLSocketWrapper.java:306)
> 06-24 16:59:53.614 8807-8807/com.technologics.developer.motorcityarabia W/System.err: 	... 10 more
> 06-24 17:02:54.404 8807-9232/com.technologics.developer.motorcityarabia W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.
> 06-24 17:03:17.724 8807-8813/? D/dalvikvm: Debugger has detached; object registry had 6655 entries
> 06-24 17:03:17.724 8807-8807/? I/dalvikvm: ignoring registerObject request in thread=1
> 06-24 17:03:17.724 8807-8807/? I/dalvikvm: ignoring registerObject request in thread=1
> 

I am trying to load this image into Ion
url = "https://www.motorscity.com/img/brand/165x165x0-1414590207Chevrolet_logo.png";

Bitmap bmImg = Ion.with(this)
                                        .load(url).asBitmap().get();
                                Drawable d = new BitmapDrawable(getResources(), bmImg);

**Comment by koush** [comment]
ion version?

**Comment by Faisal-Naseer** [comment]
compile 'com.koushikdutta.ion:ion:2.+'

**Comment by koush** [comment]
android version? and are you linked to google play services?

**Comment by Faisal-Naseer** [comment]
Yes I am using google play services in my app..min sdk 17 max sdk 25. It
was working fine a few days ago I ve invalidated caches and it stopped
working.

**Comment by koush** [comment]
What android version can I test on I mean? If you can specify an emulator, that would be helpful.

**Comment by Faisal-Naseer** [comment]
I am testing it on real device huawei y625 android 4.4

**Comment by koush** [comment]
Working fine on a 4.4 emulator here.

can you set the version to ion version 2.2.1 and try again?

**Comment by codus-me** [comment]
I have encountered this problem. version 2.2.1
My certificate is generated by https://www.sslforfree.com/.
Websocket server hosted at wss://qpu.codus.me:5000
`AsyncHttpClient.getDefaultInstance().websocket("wss://qpu.codus.me:5000", "",callback)`

Work fine on HUAWEI P10 Plus, Android 7.0
Not work on SONY Xperia M5 E5653, Android 5.1
Not work on Redmi Note 4, Android 6.0.1
Not work on LG nexus 5, Android 6.0.1
Not work on OPPO A39, Android 5.1
Not work on Samsung G900I, Android 5.0

**Comment by codus-me** [comment]
I have encountered this problem. version 2.2.1
My certificate is generated by https://www.sslforfree.com/.
Websocket server hosted at wss://qpu.codus.me:5000
`AsyncHttpClient.getDefaultInstance().websocket("wss://qpu.codus.me:5000", "",callback)`

Work fine on HUAWEI P10 Plus, Android 7.0
Not work on SONY Xperia M5 E5653, Android 5.1
Not work on Redmi Note 4, Android 6.0.1
Not work on LG nexus 5, Android 6.0.1
Not work on OPPO A39, Android 5.1
Not work on Samsung G900I, Android 5.0
