### ISSUE TITLE
Not all data was consumed by Util.emitAllData

### ISSUE THREAD

**Issue by scally-p** [koush/ion#835]
Hello @koush , I am trying to download an image from a url and i get **Not all data was consumed by Util.emitAllData** along with its stack trace. I realized that i am able to download images in the root uploads folder(eg. **domain/uploads**). However, i am unable to download images within another folder in the same uploads directory. 
Hence the error only occurs in nested folders in the uploads directory, but no the root **uploads** folder

**Comment by scally-p** [comment]
Need help ASAP

**Comment by rhvieira** [comment]
I have the same error, 'com.koushikdutta.ion:ion:2.+'.

E/MyLogs: Not all data was consumed by Util.emitAllData
                                                                   java.lang.RuntimeException: Not all data was consumed by Util.emitAllData
                                                                       at com.koushikdutta.async.Util.emitAllData(Util.java:54)
                                                                       at com.koushikdutta.async.FilteredDataEmitter.onDataAvailable(FilteredDataEmitter.java:56)
                                                                       at com.koushikdutta.async.Util.emitAllData(Util.java:23)
                                                                       at com.koushikdutta.async.FilteredDataEmitter.onDataAvailable(FilteredDataEmitter.java:56)
                                                                       at com.koushikdutta.async.http.cache.ResponseCacheMiddleware$BodyCacher.onDataAvailable(ResponseCacheMiddleware.java:385)
                                                                       at com.koushikdutta.async.Util.emitAllData(Util.java:23)
                                                                       at com.koushikdutta.async.FilteredDataEmitter.onDataAvailable(FilteredDataEmitter.java:56)
                                                                       at com.koushikdutta.async.http.filter.ContentLengthFilter.onDataAvailable(ContentLengthFilter.java:33)
                                                                       at com.koushikdutta.async.Util.emitAllData(Util.java:23)
                                                                       at com.koushikdutta.async.AsyncSSLSocketWrapper.onDataAvailable(AsyncSSLSocketWrapper.java:233)
                                                                       at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:220)
                                                                       at com.koushikdutta.async.Util.emitAllData(Util.java:23)
                                                                       at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:152)
                                                                       at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:821)
                                                                       at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:658)
                                                                       at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44)
                                                                       at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:600)

**Comment by koush** [comment]
can you give me some sample code?

**Comment by scally-p** [comment]
Hello,

Below is the requested sample code. Like i indicated in the ticket, the
error only occurs when trying to download a file within a *sub folder* of
the main *uploads *folder

public static void downloadImage(final Context context, final
ArrayList<String> imageArrayList, final int index) {

        File imagesDir = new File(Environment.getExternalStorageDirectory()
+ "/ProjectX/Images");
        String currentImageName = imageArrayList.get(index);

        if (new File(imagesDir.getPath() + "/" +
currentImageName).exists()) {

            Log.d("ProjectX", "Downloading image " + (index + 1) + " of " +
imageArrayList.size());
            Log.d("ProjectX", "Image Already Exists");

            if (index + 1 == imageArrayList.size()) {
                downloadAudios(context);
            } else {
                downloadImage(context, imageArrayList, index + 1);
            }
        } else {

            Log.d("ProjectX", "Downloading image " + (index + 1) + " of " +
imageArrayList.size());
            Ion.with(context)
                    .load(StaticUtils.URL_IMAGES + currentImageName)
                    .setLogging("My Ion Log", Log.ERROR)
                    .write(new File(imagesDir.getPath() + "/" +
currentImageName))
                    .setCallback(new FutureCallback<File>() {
                        @Override
                        public void onCompleted(Exception e, File result) {

                            if (e == null) {
                                if (index + 1 == imageArrayList.size()) {
                                    downloadAudios(context);
                                } else {
                                    downloadImage(context, imageArrayList,
index + 1);
                                }
                            } else {
                                downloadAudios(context);
                            }
                        }
                    });
        }
    }

**Comment by koush** [comment]
@scally-p 

So 
```java
File imagesDir = new File(Environment.getExternalStorageDirectory()
+ "/ProjectX/Images");
```

It will fail with this sample directory?

**Comment by scally-p** [comment]
Nah, that is not what i meant.
The issue happens when i am downloading from a nested directory *from the
server.*
So, assuming i am downloading a file from *http://domain/uploads/photo.jpg
<http://domain/uploads/photo.jpg>,  *this download will successfully work
with the code snippet earlier.
However, download fails with earlier sent error log when i try to download
from a url like this *http://domain/uploads/images/photo.jpg
<http://domain/uploads/images/photo.jpg>*

Hope it is clearer now.
​

**Comment by koush** [comment]
I see. Gotcha.

**Comment by ravenfeld** [comment]
You must create the ProjectX/Images directory

imagesDir.mkdirs();

**Comment by Kipropkorir** [comment]
@scally-p Did you get a solution to this?? I need one

**Comment by zhiwenzheng** [comment]
E/AndroidRuntime: FATAL EXCEPTION: ion-ion
    Process: e.zhiwen.drive, PID: 21192
    java.lang.RuntimeException: Not all data was consumed by Util.emitAllData
        at com.koushikdutta.async.Util.emitAllData(Util.java:54)
        at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:163)
        at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:869)
        at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:717)
        at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:46)
        at com.koushikdutta.async.AsyncServer$11.run(AsyncServer.java:671)
I/Toast: Show toast from OpPackageName:e.zhiwen.drive, PackageName:e.zhiwen.drive
Application terminated.



The app use https proxy,  when the proxy server return "400 BAD REQUEST", this happens.
It is reproducible.
