### ISSUE TITLE
HTTPS requests report expire certs when Digicert and Firefox accept it just fine.

### ISSUE THREAD

**Issue by r2DoesInc** [koush/ion#858]
> 6862-27187/co.mclear.sizer W/System.err: javax.net.ssl.SSLHandshakeException: Chain validation failed
> 11-22 19:04:21.670 26862-27187/co.mclear.sizer W/System.err:     at com.google.android.gms.org.conscrypt.SSLUtils.toSSLHandshakeException(:com.google.android.gms@11746448:2)
> 11-22 19:04:21.671 26862-27187/co.mclear.sizer W/System.err:     at com.google.android.gms.org.conscrypt.ConscryptEngine.convertException(:com.google.android.gms@11746448:1)
> 11-22 19:04:21.671 26862-27187/co.mclear.sizer W/System.err:     at com.google.android.gms.org.conscrypt.ConscryptEngine.readPlaintextData(:com.google.android.gms@11746448:3)
> 11-22 19:04:21.671 26862-27187/co.mclear.sizer W/System.err:     at com.google.android.gms.org.conscrypt.ConscryptEngine.unwrap(:com.google.android.gms@11746448:45)
> 11-22 19:04:21.671 26862-27187/co.mclear.sizer W/System.err:     at com.google.android.gms.org.conscrypt.ConscryptEngine.unwrap(:com.google.android.gms@11746448:72)
> 11-22 19:04:21.671 26862-27187/co.mclear.sizer W/System.err:     at com.google.android.gms.org.conscrypt.ConscryptEngine.unwrap(:com.google.android.gms@11746448:2)
> 11-22 19:04:21.671 26862-27187/co.mclear.sizer W/System.err:     at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:194)
> 11-22 19:04:21.671 26862-27187/co.mclear.sizer W/System.err:     at com.koushikdutta.async.Util.emitAllData(Util.java:23)
> 11-22 19:04:21.671 26862-27187/co.mclear.sizer W/System.err:     at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:152)
> 11-22 19:04:21.671 26862-27187/co.mclear.sizer W/System.err:     at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:789)
> 11-22 19:04:21.671 26862-27187/co.mclear.sizer W/System.err:     at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:627)
> 11-22 19:04:21.671 26862-27187/co.mclear.sizer W/System.err:     at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
> 11-22 19:04:21.671 26862-27187/co.mclear.sizer W/System.err:     at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:569)
> 11-22 19:04:21.674 26862-27187/co.mclear.sizer W/System.err: Caused by: java.security.cert.CertificateException: Chain validation failed
> 11-22 19:04:21.674 26862-27187/co.mclear.sizer W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:610)
> 11-22 19:04:21.674 26862-27187/co.mclear.sizer W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:444)
> 11-22 19:04:21.674 26862-27187/co.mclear.sizer W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:464)
> 11-22 19:04:21.674 26862-27187/co.mclear.sizer W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:508)
> 11-22 19:04:21.675 26862-27187/co.mclear.sizer W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:401)
> 11-22 19:04:21.675 26862-27187/co.mclear.sizer W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:375)
> 11-22 19:04:21.675 26862-27187/co.mclear.sizer W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:318)
> 11-22 19:04:21.675 26862-27187/co.mclear.sizer W/System.err:     at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:102)
> 11-22 19:04:21.675 26862-27187/co.mclear.sizer W/System.err:     at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:104)
> 11-22 19:04:21.675 26862-27187/co.mclear.sizer W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
> 11-22 19:04:21.675 26862-27187/co.mclear.sizer W/System.err:     at com.google.android.gms.org.conscrypt.Platform.checkTrusted(:com.google.android.gms@11746448:2)
> 11-22 19:04:21.675 26862-27187/co.mclear.sizer W/System.err:     at com.google.android.gms.org.conscrypt.Platform.checkServerTrusted(:com.google.android.gms@11746448:6)
> 11-22 19:04:21.675 26862-27187/co.mclear.sizer W/System.err:     at com.google.android.gms.org.conscrypt.ConscryptEngine.verifyCertificateChain(:com.google.android.gms@11746448:5)
> 11-22 19:04:21.675 26862-27187/co.mclear.sizer W/System.err:     at com.google.android.gms.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
> 11-22 19:04:21.675 26862-27187/co.mclear.sizer W/System.err:     at com.google.android.gms.org.conscrypt.SslWrapper.readDirectByteBuffer(:com.google.android.gms@11746448)
> 11-22 19:04:21.675 26862-27187/co.mclear.sizer W/System.err:     at com.google.android.gms.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(:com.google.android.gms@11746448)
> 11-22 19:04:21.675 26862-27187/co.mclear.sizer W/System.err:     at com.google.android.gms.org.conscrypt.ConscryptEngine.readPlaintextDataHeap(:com.google.android.gms@11746448:4)
> 11-22 19:04:21.675 26862-27187/co.mclear.sizer W/System.err: 	... 11 more
> 11-22 19:04:21.676 26862-27187/co.mclear.sizer W/System.err: Caused by: java.security.cert.CertPathValidatorException: timestamp check failed
> 11-22 19:04:21.676 26862-27187/co.mclear.sizer W/System.err:     at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:127)
> 11-22 19:04:21.676 26862-27187/co.mclear.sizer W/System.err:     at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:215)
> 11-22 19:04:21.676 26862-27187/co.mclear.sizer W/System.err:     at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:143)
> 11-22 19:04:21.677 26862-27187/co.mclear.sizer W/System.err:     at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79)
> 11-22 19:04:21.677 26862-27187/co.mclear.sizer W/System.err:     at java.security.cert.CertPathValidator.validate(CertPathValidator.java:301)
> 11-22 19:04:21.677 26862-27187/co.mclear.sizer W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:606)
> 11-22 19:04:21.677 26862-27187/co.mclear.sizer W/System.err: 	... 27 more
> 11-22 19:04:21.677 26862-27187/co.mclear.sizer W/System.err: Caused by: java.security.cert.CertificateExpiredException: **Certificate expired at Tue May 02 12:04:00 EDT 2017 (compared to Wed Nov 22 19:04:21 EST 2017)**
> 11-22 19:04:21.677 26862-27187/co.mclear.sizer W/System.err:     at com.android.org.conscrypt.OpenSSLX509Certificate.checkValidity(OpenSSLX509Certificate.java:234)
> 11-22 19:04:21.677 26862-27187/co.mclear.sizer W/System.err:     at sun.security.provider.certpath.BasicChecker.verifyTimestamp(BasicChecker.java:194)
> 11-22 19:04:21.677 26862-27187/co.mclear.sizer W/System.err:     at sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:144)
> 11-22 19:04:21.677 26862-27187/co.mclear.sizer W/System.err:     at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:119)
> 11-22 19:04:21.677 26862-27187/co.mclear.sizer W/System.err: 	... 32 more
> 11-22 19:04:21.681 26862-26862/co.mclear.sizer W/System.err: javax.net.ssl.SSLHandshakeException: Chain validation failed
> 11-22 19:04:21.682 26862-26862/co.mclear.sizer W/System.err:     at com.google.android.gms.org.conscrypt.SSLUtils.toSSLHandshakeException(:com.google.android.gms@11746448:2)
> 11-22 19:04:21.682 26862-26862/co.mclear.sizer W/System.err:     at com.google.android.gms.org.conscrypt.ConscryptEngine.convertException(:com.google.android.gms@11746448:1)
> 11-22 19:04:21.682 26862-26862/co.mclear.sizer W/System.err:     at com.google.android.gms.org.conscrypt.ConscryptEngine.readPlaintextData(:com.google.android.gms@11746448:3)
> 11-22 19:04:21.682 26862-26862/co.mclear.sizer W/System.err:     at com.google.android.gms.org.conscrypt.ConscryptEngine.unwrap(:com.google.android.gms@11746448:45)
> 11-22 19:04:21.682 26862-26862/co.mclear.sizer W/System.err:     at com.google.android.gms.org.conscrypt.ConscryptEngine.unwrap(:com.google.android.gms@11746448:72)
> 11-22 19:04:21.682 26862-26862/co.mclear.sizer W/System.err:     at com.google.android.gms.org.conscrypt.ConscryptEngine.unwrap(:com.google.android.gms@11746448:2)
> 11-22 19:04:21.682 26862-26862/co.mclear.sizer W/System.err:     at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:194)
> 11-22 19:04:21.682 26862-26862/co.mclear.sizer W/System.err:     at com.koushikdutta.async.Util.emitAllData(Util.java:23)
> 11-22 19:04:21.682 26862-26862/co.mclear.sizer W/System.err:     at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:152)
> 11-22 19:04:21.682 26862-26862/co.mclear.sizer W/System.err:     at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:789)
> 11-22 19:04:21.682 26862-26862/co.mclear.sizer W/System.err:     at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:627)
> 11-22 19:04:21.682 26862-26862/co.mclear.sizer W/System.err:     at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
> 11-22 19:04:21.682 26862-26862/co.mclear.sizer W/System.err:     at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:569)
> 11-22 19:04:21.682 26862-26862/co.mclear.sizer W/System.err: Caused by: java.security.cert.CertificateException: Chain validation failed
> 11-22 19:04:21.682 26862-26862/co.mclear.sizer W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:610)
> 11-22 19:04:21.682 26862-26862/co.mclear.sizer W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:444)
> 11-22 19:04:21.682 26862-26862/co.mclear.sizer W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:464)
> 11-22 19:04:21.682 26862-26862/co.mclear.sizer W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:508)
> 11-22 19:04:21.682 26862-26862/co.mclear.sizer W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:401)
> 11-22 19:04:21.682 26862-26862/co.mclear.sizer W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:375)
> 11-22 19:04:21.682 26862-26862/co.mclear.sizer W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:318)
> 11-22 19:04:21.682 26862-26862/co.mclear.sizer W/System.err:     at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:102)
> 11-22 19:04:21.683 26862-26862/co.mclear.sizer W/System.err:     at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:104)
> 11-22 19:04:21.683 26862-26862/co.mclear.sizer W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
> 11-22 19:04:21.683 26862-26862/co.mclear.sizer W/System.err:     at com.google.android.gms.org.conscrypt.Platform.checkTrusted(:com.google.android.gms@11746448:2)
> 11-22 19:04:21.683 26862-26862/co.mclear.sizer W/System.err:     at com.google.android.gms.org.conscrypt.Platform.checkServerTrusted(:com.google.android.gms@11746448:6)
> 11-22 19:04:21.683 26862-26862/co.mclear.sizer W/System.err:     at com.google.android.gms.org.conscrypt.ConscryptEngine.verifyCertificateChain(:com.google.android.gms@11746448:5)
> 11-22 19:04:21.683 26862-26862/co.mclear.sizer W/System.err:     at com.google.android.gms.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
> 11-22 19:04:21.683 26862-26862/co.mclear.sizer W/System.err:     at com.google.android.gms.org.conscrypt.SslWrapper.readDirectByteBuffer(:com.google.android.gms@11746448)
> 11-22 19:04:21.683 26862-26862/co.mclear.sizer W/System.err:     at com.google.android.gms.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(:com.google.android.gms@11746448)
> 11-22 19:04:21.683 26862-26862/co.mclear.sizer W/System.err:     at com.google.android.gms.org.conscrypt.ConscryptEngine.readPlaintextDataHeap(:com.google.android.gms@11746448:4)
> 11-22 19:04:21.683 26862-26862/co.mclear.sizer W/System.err: 	... 11 more
> 11-22 19:04:21.683 26862-26862/co.mclear.sizer W/System.err: Caused by: java.security.cert.CertPathValidatorException: timestamp check failed
> 11-22 19:04:21.683 26862-26862/co.mclear.sizer W/System.err:     at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:127)
> 11-22 19:04:21.683 26862-26862/co.mclear.sizer W/System.err:     at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:215)
> 11-22 19:04:21.683 26862-26862/co.mclear.sizer W/System.err:     at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:143)
> 11-22 19:04:21.683 26862-26862/co.mclear.sizer W/System.err:     at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79)
> 11-22 19:04:21.683 26862-26862/co.mclear.sizer W/System.err:     at java.security.cert.CertPathValidator.validate(CertPathValidator.java:301)
> 11-22 19:04:21.683 26862-26862/co.mclear.sizer W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:606)
> 11-22 19:04:21.683 26862-26862/co.mclear.sizer W/System.err: 	... 27 more
> 11-22 19:04:21.683 26862-26862/co.mclear.sizer W/System.err: Caused by: java.security.cert.CertificateExpiredException: **Certificate expired at Tue May 02 12:04:00 EDT 2017 (compared to Wed Nov 22 19:04:21 EST 2017)**
> 11-22 19:04:21.683 26862-26862/co.mclear.sizer W/System.err:     at com.android.org.conscrypt.OpenSSLX509Certificate.checkValidity(OpenSSLX509Certificate.java:234)
> 11-22 19:04:21.683 26862-26862/co.mclear.sizer W/System.err:     at sun.security.provider.certpath.BasicChecker.verifyTimestamp(BasicChecker.java:194)
> 11-22 19:04:21.683 26862-26862/co.mclear.sizer W/System.err:     at sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:144)
> 11-22 19:04:21.683 26862-26862/co.mclear.sizer W/System.err:     at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:119)
> 11-22 19:04:21.683 26862-26862/co.mclear.sizer W/System.err: 	... 32 
> 
> > more

**Comment by atnegrete** [comment]
Any lucking fixing this?
