### ISSUE TITLE
Connection refused error on Mobile/Cellular connections

### ISSUE THREAD

**Issue by pepie** [koush/ion#871]
Hello,

I seem to be running into a weird issue when HTTP calls are not being completed, when the device is using cellular data.
The calls works perfectly over wifi, but consistently fails once wifi is turned off.
Is this an Ion issue, or am I missing something?
Any advice would be greatly appreciated.

Ion Library version: 2.2.1
Setup:
```
Ion
.with(ctx)
.load(url)
.setHeader("Authorization","<some token>")
.setHeader("Content-Type", "application/json")
.as(new TypeToken<CustomClass>() {})
.setCallback(new FutureCallback<EventList>() {
    @Override
    public void onCompleted(Exception e, EventList response) {
        //process response
    }
);
```

Error Log:
```
`-*-ION-*-: (487 ms) http://<url>: Resolving domain and connecting to all available addresses
-*-ION-*-: (0 ms) http://<api url here>: Executing request.
-*-ION-*-: (14 ms) http://<api url here>: Resolving domain and connecting to all available addresses
-*-ION-*-: (509 ms) http://<api url here>: attempting connection to <mydomain.info>/<ip address>
-*-ION-*-: (19 ms) http://<api url here>: attempting connection to <mydomain.info>/<ip address>
-*-ION-*-: (5586 ms) http://<api url here>: socket connected
-*-ION-*-: (5591 ms) http://<api url here>: Connection error
-*-ION-*-: Connection refused
    java.net.ConnectException: Connection refused
    at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
    at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:742)
    at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:834)
    at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:658)
    at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44)
    at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:600)`
```
Steps To Repeat:
- Turn on wifi load activity which calls API (success)
- Turn off wifi and ensure mobile data is turned on
- reload activity which calls API (* connection refused)

Note: 
Network status is verified before the call is made.
```public Boolean isOnline(){
        try{
            connectivityManager = (ConnectivityManager) context.getSystemService(
                    Context.CONNECTIVITY_SERVICE
            );
            NetworkInfo networkInfo = connectivityManager.getActiveNetworkInfo();
            connected = networkInfo != null && networkInfo.isAvailable() && networkInfo.isConnected();
            return connected;
        }catch(Exception e){
            Log.d(NetworkStatus.class.getName(), "Connection exception: " + e.getMessage());
        }

        return connected;
    }
```

Again, everything works fine when wifi is enabled.
Any help would be greatly appreciated.

Thanks in advance!

**Comment by pepie** [comment]
This issue is resolved.
In case anyone else run into this:
I was using port 8890 for my api, and it turned out that port is a special port - on mobile network (Sprint).
Seems strange, but changing to another port fixed the problem.

I'm Galaxy S7 Edge, Sprint.
