### ISSUE TITLE
Conscrypt initialization failed

### ISSUE THREAD

**Issue by ShaBax** [koush/ion#874]
can you please explain this log ?
`03-29 23:27:27.518 28346-28346/? D/Home: getcategoryUrl:http://192.168.0.136:3000/category
03-29 23:27:27.581 28346-28386/? W/IonConscrypt: Conscrypt initialization failed.
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/security/ProviderInstaller;
        at com.koushikdutta.ion.conscrypt.ConscryptMiddleware.initialize(ConscryptMiddleware.java:58)
        at com.koushikdutta.ion.conscrypt.ConscryptMiddleware.initialize(ConscryptMiddleware.java:75)
        at com.koushikdutta.ion.conscrypt.ConscryptMiddleware.getSocket(ConscryptMiddleware.java:103)
        at com.koushikdutta.async.http.AsyncHttpClient.executeAffinity(AsyncHttpClient.java:301)
        at com.koushikdutta.async.http.AsyncHttpClient.access$100(AsyncHttpClient.java:51)
        at com.koushikdutta.async.http.AsyncHttpClient$1.run(AsyncHttpClient.java:190)
        at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:740)
        at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:758)
        at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:658)
        at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44)
        at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:600)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.security.ProviderInstaller" on path: DexPathList[[zip file "/data/app/net.elektrasoft.foodstreet-1/base.apk", zip file "/data/app/net.elektrasoft.foodstreet-1/split_lib_dependencies_apk.apk", zip file "/data/app/net.elektrasoft.foodstreet-1/split_lib_slice_0_apk.apk", zip file "/data/app/net.elektrasoft.foodstreet-1/split_lib_slice_1_apk.apk", zip file "/data/app/net.elektrasoft.foodstreet-1/split_lib_slice_2_apk.apk", zip file "/data/app/net.elektrasoft.foodstreet-1/split_lib_slice_3_apk.apk", zip file "/data/app/net.elektrasoft.foodstreet-1/split_lib_slice_4_apk.apk", zip file "/data/app/net.elektrasoft.foodstreet-1/split_lib_slice_5_apk.apk", zip file "/data/app/net.elektrasoft.foodstreet-1/split_lib_slice_6_apk.apk", zip file "/data/app/net.elektrasoft.foodstreet-1/split_lib_slice_7_apk.apk", zip file "/data/app/net.elektrasoft.foodstreet-1/split_lib_slice_8_apk.apk", zip file "/data/app/net.elektrasoft.foodstreet-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/net.elektrasoft.foodstreet-1/lib/x86, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at com.koushikdutta.ion.conscrypt.ConscryptMiddleware.initialize(ConscryptMiddleware.java:58) 
        at com.koushikdutta.ion.conscrypt.ConscryptMiddleware.initialize(ConscryptMiddleware.java:75) 
        at com.koushikdutta.ion.conscrypt.ConscryptMiddleware.getSocket(ConscryptMiddleware.java:103) 
        at com.koushikdutta.async.http.AsyncHttpClient.executeAffinity(AsyncHttpClient.java:301) 
        at com.koushikdutta.async.http.AsyncHttpClient.access$100(AsyncHttpClient.java:51) 
        at com.koushikdutta.async.http.AsyncHttpClient$1.run(AsyncHttpClient.java:190) 
        at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:740) 
        at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:758) 
        at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:658) 
        at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44) 
        at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:600) 
    	Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.security.ProviderInstaller
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 12 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available`

**Comment by numericOverflow** [comment]
I've got the same error, for a different calling app. Anyone figure out the cause yet?

**Comment by hammi1** [comment]
I have this same issue when I use Ion to retrieve data from a widget, but the _same code_ in my MainActivity works absolutely fine. Any ideas?

**Comment by rahulas** [comment]
Ion.getDefault(mInstance).getConscryptMiddleware().enable(false);

Include above line in your application class.

**Comment by acefalobi** [comment]
Did this work?

**Comment by JJOL** [comment]
Thank you kindly Sir! @rahulas

**Comment by JukieChen** [comment]
> Ion.getDefault(mInstance).getConscryptMiddleware().enable(false);
> 
> Include above line in your application class.

what is "mInstance" for?

**Comment by bautrey37** [comment]
Adding that line caused the response to not do anything.
