### ISSUE TITLE
Android 8.1 request failed, ConnectionClosedException: connection closed before response completed.

### ISSUE THREAD

**Issue by yue001** [koush/ion#881]
I get a exception on  Android 8.1(Below 8.1 is OK) , but when I request with HttpURLConnection, it response success;
The exceptio as bolew, Please have a look and let me know if there is a solution, thank you very mach;

`    com.koushikdutta.async.http.ConnectionClosedException: connection closed before response completed.
        at com.koushikdutta.async.http.AsyncHttpResponseImpl$2.onCompleted(AsyncHttpResponseImpl.java:54)
        at com.koushikdutta.async.AsyncSSLSocketWrapper.report(AsyncSSLSocketWrapper.java:438)
        at com.koushikdutta.async.AsyncSSLSocketWrapper.access$100(AsyncSSLSocketWrapper.java:30)
        at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:224)
        at com.koushikdutta.async.Util.emitAllData(Util.java:23)
        at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:152)
        at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:821)
        at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:658)
        at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44)
        at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:600)
     Caused by: javax.net.ssl.SSLException: java.io.EOFException: Read error
        at com.android.org.conscrypt.SSLUtils.toSSLException(SSLUtils.java:295)
        at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1093)
        at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:851)
        at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:678)
        at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:644)
        at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:194)
        at com.koushikdutta.async.Util.emitAllData(Util.java:23) 
        at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:152) 
        at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:821) 
        at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:658) 
        at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44) 
        at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:600) 
     Caused by: java.io.EOFException: Read error
        at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
        at com.android.org.conscrypt.SslWrapper.readDirectByteBuffer(SslWrapper.java:492)
        at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1052)
        at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataHeap(ConscryptEngine.java:1072)
        at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1044)
        at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:805)
        at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:678) 
        at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:644) 
        at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:194) 
        at com.koushikdutta.async.Util.emitAllData(Util.java:23) 
        at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:152) 
        at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:821) 
        at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:658) 
        at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44) 
        at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:600) `

**Comment by yue001** [comment]
I have found the reason in AndroidAsync issues, It seems like a issue of android 8.1 ,
[https://github.com/koush/AndroidAsync/issues/594](https://github.com/koush/AndroidAsync/issues/594#ref-issue-309495958)

**Comment by yanctrindade** [comment]
How solve this on ion ? I didn't get. How to set the new buffer on ion ?
