### ISSUE TITLE
sometimes get ssl handshake exception even though ssl verification is disabled

### ISSUE THREAD

**Issue by zhiwenzheng** [koush/ion#900]
```
2019-04-12 14:25:56.438 7534-7534/e.zhiwen.drive E/Flow Drive: listdir ~/media/image
    javax.net.ssl.SSLHandshakeException: Handshake failed
        at com.android.org.conscrypt.OpenSSLEngineImpl.unwrap(OpenSSLEngineImpl.java:441)
        at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:1270)
        at com.koushikdutta.async.AsyncSSLSocketWrapper$6.onDataAvailable(AsyncSSLSocketWrapper.java:296)
        at com.koushikdutta.async.Util.emitAllData(Util.java:23)
        at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:163)
        at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:869)
        at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:717)
        at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:46)
        at com.koushikdutta.async.AsyncServer$11.run(AsyncServer.java:671)
     Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:563)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:444)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:401)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:375)
        at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:318)
        at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:102)
        at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:104)
        at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:202)
        at com.android.org.conscrypt.OpenSSLEngineImpl.verifyCertificateChain(OpenSSLEngineImpl.java:666)
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake_bio(Native Method)
        at com.android.org.conscrypt.OpenSSLEngineImpl.unwrap(OpenSSLEngineImpl.java:426)
        at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:1270) 
        at com.koushikdutta.async.AsyncSSLSocketWrapper$6.onDataAvailable(AsyncSSLSocketWrapper.java:296) 
        at com.koushikdutta.async.Util.emitAllData(Util.java:23) 
        at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:163) 
        at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:869) 
        at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:717) 
        at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:46) 
        at com.koushikdutta.async.AsyncServer$11.run(AsyncServer.java:671) 
     Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:563) 
        at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:444) 
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:401) 
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:375) 
        at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:318) 
        at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:102) 
        at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:104) 
        at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:202) 
        at com.android.org.conscrypt.OpenSSLEngineImpl.verifyCertificateChain(OpenSSLEngineImpl.java:666) 
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake_bio(Native Method) 
        at com.android.org.conscrypt.OpenSSLEngineImpl.unwrap(OpenSSLEngineImpl.java:426) 
        at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:1270) 
        at com.koushikdutta.async.AsyncSSLSocketWrapper$6.onDataAvailable(AsyncSSLSocketWrapper.java:296) 
        at com.koushikdutta.async.Util.emitAllData(Util.java:23) 
        at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:163) 
        at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:869) 
        at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:717) 
        at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:46) 
        at com.koushikdutta.async.AsyncServer$11.run(AsyncServer.java:671) 
2019-04-12 14:25:56.455 7534-7534/e.zhiwen.drive I/Toast: Show toast from OpPackageName:e.zhiwen.drive, PackageName:e.zhiwen.drive
```

**Comment by zhiwenzheng** [comment]
use the code below to disable ssl verification

 val trustAllCerts = arrayOf<TrustManager>(object : X509TrustManager {
            @Throws(CertificateException::class)
            override fun checkClientTrusted(chain: Array<java.security.cert.X509Certificate>, authType: String) {
            }

            @Throws(CertificateException::class)
            override fun checkServerTrusted(chain: Array<java.security.cert.X509Certificate>, authType: String) {
            }

            override fun getAcceptedIssuers(): Array<java.security.cert.X509Certificate> {
                return arrayOf()
            }
        })

        val sslMiddleWare = Ion.getDefault(this).httpClient.sslSocketMiddleware
        sslMiddleWare.setTrustManagers(trustAllCerts)

        val sslContext = SSLContext.getInstance("TLS")
        sslContext.init(null, trustAllCerts, null)

        sslMiddleWare.setSSLContext(sslContext)

        sslMiddleWare.setHostnameVerifier(object : HostnameVerifier {
            override fun verify(hostname: String, session: SSLSession): Boolean {
                return true
            }
        })

**Comment by zhiwenzheng** [comment]
a more comprehensive log

```
2019-04-12 14:25:56.438 7534-7534/e.zhiwen.drive E/Flow Drive: listdir ~/media/image
    javax.net.ssl.SSLHandshakeException: Handshake failed
        at com.android.org.conscrypt.OpenSSLEngineImpl.unwrap(OpenSSLEngineImpl.java:441)
        at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:1270)
        at com.koushikdutta.async.AsyncSSLSocketWrapper$6.onDataAvailable(AsyncSSLSocketWrapper.java:296)
        at com.koushikdutta.async.Util.emitAllData(Util.java:23)
        at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:163)
        at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:869)
        at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:717)
        at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:46)
        at com.koushikdutta.async.AsyncServer$11.run(AsyncServer.java:671)
     Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:563)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:444)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:401)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:375)
        at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:318)
        at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:102)
        at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:104)
        at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:202)
        at com.android.org.conscrypt.OpenSSLEngineImpl.verifyCertificateChain(OpenSSLEngineImpl.java:666)
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake_bio(Native Method)
        at com.android.org.conscrypt.OpenSSLEngineImpl.unwrap(OpenSSLEngineImpl.java:426)
        at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:1270) 
        at com.koushikdutta.async.AsyncSSLSocketWrapper$6.onDataAvailable(AsyncSSLSocketWrapper.java:296) 
        at com.koushikdutta.async.Util.emitAllData(Util.java:23) 
        at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:163) 
        at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:869) 
        at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:717) 
        at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:46) 
        at com.koushikdutta.async.AsyncServer$11.run(AsyncServer.java:671) 
     Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:563) 
        at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:444) 
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:401) 
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:375) 
        at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:318) 
        at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:102) 
        at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:104) 
        at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:202) 
        at com.android.org.conscrypt.OpenSSLEngineImpl.verifyCertificateChain(OpenSSLEngineImpl.java:666) 
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake_bio(Native Method) 
        at com.android.org.conscrypt.OpenSSLEngineImpl.unwrap(OpenSSLEngineImpl.java:426) 
        at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:1270) 
        at com.koushikdutta.async.AsyncSSLSocketWrapper$6.onDataAvailable(AsyncSSLSocketWrapper.java:296) 
        at com.koushikdutta.async.Util.emitAllData(Util.java:23) 
        at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:163) 
        at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:869) 
        at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:717) 
        at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:46) 
        at com.koushikdutta.async.AsyncServer$11.run(AsyncServer.java:671) 
2019-04-12 14:25:56.455 7534-7534/e.zhiwen.drive I/Toast: Show toast from OpPackageName:e.zhiwen.drive, PackageName:e.zhiwen.drive
```

**Comment by zhiwenzheng** [comment]
![Screenshot_2019-04-12_15-54-19](https://user-images.githubusercontent.com/9572755/56021258-8c4fbb80-5d3b-11e9-9674-c783f89f61ff.png)

normally the stacktrace like this

**Comment by zhiwenzheng** [comment]
```
        try {
            proxies = ProxySelector.getDefault().select(URI.create(request.getUri().toString()));
        }
        catch (Exception e) {
            // uri parsing craps itself sometimes.
            return;
        }
```
find proxy failed, and ion make request without proxy instead of fail the request

**Comment by zhiwenzheng** [comment]
https proxy config lost.

**Comment by zhiwenzheng** [comment]
You can close this issue, the problem is in my code.
The process may be killed by android, and when recreated, the activity where I init ION is bypassed. I should put ION init code in appliction object.
