### ISSUE TITLE
Unable to download in Android 11 : Not all data was consumed by Util.emitAllData

### ISSUE THREAD

**Issue by sonika-srivastava** [koush/ion#945]
Getting the following runtime exception while downloading file in Android 11.

 java.lang.RuntimeException: Not all data was consumed by Util.emitAllData
	at com.koushikdutta.async.Util.emitAllData(Util.java:54)
	at com.koushikdutta.async.FilteredDataEmitter.onDataAvailable(FilteredDataEmitter.java:56)
	at com.koushikdutta.async.Util.emitAllData(Util.java:23)
	at com.koushikdutta.async.FilteredDataEmitter.onDataAvailable(FilteredDataEmitter.java:56)
	at com.koushikdutta.async.http.cache.ResponseCacheMiddleware$BodyCacher.onDataAvailable(ResponseCacheMiddleware.java:385)
	at com.koushikdutta.async.Util.emitAllData(Util.java:23)
	at com.koushikdutta.async.FilteredDataEmitter.onDataAvailable(FilteredDataEmitter.java:56)
	at com.koushikdutta.async.http.filter.ContentLengthFilter.onDataAvailable(ContentLengthFilter.java:33)
	at com.koushikdutta.async.Util.emitAllData(Util.java:23)
	at com.koushikdutta.async.AsyncSSLSocketWrapper.onDataAvailable(AsyncSSLSocketWrapper.java:233)
	at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:220)
	at com.koushikdutta.async.Util.emitAllData(Util.java:23)
	at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:152)
	at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:821)
	at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:658)
	at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44)
	at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:600)

This is on Maven version 3.1.0

Any fix for the same?
All the downloads in our commercial app uses Ion library. So need urgent help.

**Comment by Yazeed0712** [comment]
> Getting the following runtime exception while downloading file in Android 11.
> 
> java.lang.RuntimeException: Not all data was consumed by Util.emitAllData
> at com.koushikdutta.async.Util.emitAllData(Util.java:54)
> at com.koushikdutta.async.FilteredDataEmitter.onDataAvailable(FilteredDataEmitter.java:56)
> at com.koushikdutta.async.Util.emitAllData(Util.java:23)
> at com.koushikdutta.async.FilteredDataEmitter.onDataAvailable(FilteredDataEmitter.java:56)
> at com.koushikdutta.async.http.cache.ResponseCacheMiddleware$BodyCacher.onDataAvailable(ResponseCacheMiddleware.java:385)
> at com.koushikdutta.async.Util.emitAllData(Util.java:23)
> at com.koushikdutta.async.FilteredDataEmitter.onDataAvailable(FilteredDataEmitter.java:56)
> at com.koushikdutta.async.http.filter.ContentLengthFilter.onDataAvailable(ContentLengthFilter.java:33)
> at com.koushikdutta.async.Util.emitAllData(Util.java:23)
> at com.koushikdutta.async.AsyncSSLSocketWrapper.onDataAvailable(AsyncSSLSocketWrapper.java:233)
> at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:220)
> at com.koushikdutta.async.Util.emitAllData(Util.java:23)
> at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:152)
> at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:821)
> at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:658)
> at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44)
> at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:600)
> 
> This is on Maven version 3.1.0
> 
> Any fix for the same?
> All the downloads in our commercial app uses Ion library. So need urgent help.

**Comment by Yazeed0712** [comment]
> Getting the following runtime exception while downloading file in Android 11.
> 
> java.lang.RuntimeException: Not all data was consumed by Util.emitAllData
> at com.koushikdutta.async.Util.emitAllData(Util.java:54)
> at com.koushikdutta.async.FilteredDataEmitter.onDataAvailable(FilteredDataEmitter.java:56)
> at com.koushikdutta.async.Util.emitAllData(Util.java:23)
> at com.koushikdutta.async.FilteredDataEmitter.onDataAvailable(FilteredDataEmitter.java:56)
> at com.koushikdutta.async.http.cache.ResponseCacheMiddleware$BodyCacher.onDataAvailable(ResponseCacheMiddleware.java:385)
> at com.koushikdutta.async.Util.emitAllData(Util.java:23)
> at com.koushikdutta.async.FilteredDataEmitter.onDataAvailable(FilteredDataEmitter.java:56)
> at com.koushikdutta.async.http.filter.ContentLengthFilter.onDataAvailable(ContentLengthFilter.java:33)
> at com.koushikdutta.async.Util.emitAllData(Util.java:23)
> at com.koushikdutta.async.AsyncSSLSocketWrapper.onDataAvailable(AsyncSSLSocketWrapper.java:233)
> at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:220)
> at com.koushikdutta.async.Util.emitAllData(Util.java:23)
> at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:152)
> at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:821)
> at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:658)
> at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44)
> at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:600)
> 
> This is on Maven version 3.1.0
> 
> Any fix for the same?
> All the downloads in our commercial app uses Ion library. So need urgent help.

Panda Retail Company employee
