### ISSUE TITLE
java.lang.BootstrapMethodError / java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by zwirne** [koush/ion#948]
Hey,

my project was working well for 4 years with ion, thx for that!
But now I'm facing an "Class not found error" which I do not understand.

When doing this call like in the example:

Ion.with(getContext())
.load(url)
.asString()
.withResponse()
.setCallback(new FutureCallback<Response<String>>() {
    @Override
    public void onCompleted(Exception e, Response<String> result) {
        // print the response code, ie, 200
        System.out.println(result.getHeaders().code());
        // print the String that was downloaded
        System.out.println(result.getResult());
    }
});

This is the error I'm getting:

java.lang.BootstrapMethodError: Exception from call site #43 bootstrap method
        at com.koushikdutta.async.future.SimpleFuture.setCallback(SimpleFuture.java:212)
        at com.koushikdutta.ion.IonRequestBuilder.resolveAndLoadRequest(IonRequestBuilder.java:390)
        at com.koushikdutta.ion.IonRequestBuilder.getLoaderEmitter(IonRequestBuilder.java:354)
        at com.koushikdutta.ion.IonRequestBuilder.getLoaderEmitter(IonRequestBuilder.java:317)
        at com.koushikdutta.ion.IonRequestBuilder.execute(IonRequestBuilder.java:690)
        at com.koushikdutta.ion.IonRequestBuilder.execute(IonRequestBuilder.java:643)
        at com.koushikdutta.ion.IonRequestBuilder.asJsonObject(IonRequestBuilder.java:696)
        at com.myproject.wizard.WizardStep1_TownSelection.loadData(WizardStep1_TownSelection.java:117)
        at com.myproject.wizard.WizardStep1_TownSelection.onCreate(WizardStep1_TownSelection.java:73)
        at android.app.Activity.performCreate(Activity.java:7074)
        at android.app.Activity.performCreate(Activity.java:7065)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2796)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2921)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1639)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6662)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: java.lang.NoClassDefFoundError: Invalid descriptor: LL.
        at com.koushikdutta.async.future.SimpleFuture.setCallback(SimpleFuture.java:212) 
        at com.koushikdutta.ion.IonRequestBuilder.resolveAndLoadRequest(IonRequestBuilder.java:390) 
        at com.koushikdutta.ion.IonRequestBuilder.getLoaderEmitter(IonRequestBuilder.java:354) 
        at com.koushikdutta.ion.IonRequestBuilder.getLoaderEmitter(IonRequestBuilder.java:317) 
        at com.koushikdutta.ion.IonRequestBuilder.execute(IonRequestBuilder.java:690) 
        at com.koushikdutta.ion.IonRequestBuilder.execute(IonRequestBuilder.java:643) 
        at com.koushikdutta.ion.IonRequestBuilder.asJsonObject(IonRequestBuilder.java:696) 
        at com.myproject.wizard.WizardStep1_TownSelection.loadData(WizardStep1_TownSelection.java:117) 
        at com.myproject.wizard.WizardStep1_TownSelection.onCreate(WizardStep1_TownSelection.java:73) 
        at android.app.Activity.performCreate(Activity.java:7074) 
        at android.app.Activity.performCreate(Activity.java:7065) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2796) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2921) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1639) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:176) 
        at android.app.ActivityThread.main(ActivityThread.java:6662) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 

Do you have any suggestions?

Thanks for your help.
zwirne

**Comment by zwirne** [comment]
The problem was the gradle version.
Solved by changing to 4.0.1 --> https://github.com/koush/ion/issues/928
